### ISSUE TITLE
Bar resizes the "system info" panel constantly

### ISSUE THREAD

**Issue by WTechNinja** [LBCrion/sfwbar#10]
The bar looks like it's vibrating, because part of the panel is resizing itself constantly.
![barresizing](https://user-images.githubusercontent.com/64444934/146680903-c22e0bb9-7c2f-46f4-85fc-b2fe0954e8d5.gif)

**Comment by LBCrion** [comment]
This is due to the default config. I updated configs in git to avoid this. The reason for this is a constantly changing number on a network traffic monitor. The width of that label keeps changing. New default config adds a 1cm min width for values, so it should be more stable.

**Comment by WTechNinja** [comment]
Thanks, it's fixed.
