### ISSUE TITLE
qustion on config and plugin files

### ISSUE THREAD

**Issue by mrsteve0924** [LBCrion/sfwbar#100]
i see you suggest to copy the config file from /usr/share/sfwbar/ to ~/.config/sfwbar/.  I assume to prevent any changes from being overwritten when updating.  i also made edits to some plugin files.  will it work if i copy those to ~/.config/sfwbar/ as well?

**Comment by LBCrion** [comment]
Do you mean .widget or .source config files? Yes,  you can just copy these
to ~/.config/sfwbar and modify as needed.

**Comment by mrsteve0924** [comment]
right widgets.  i've been playing around with a few different panels and i'm getting them all mixed up.  thanks!
