### ISSUE TITLE
Bug with Exec()?

### ISSUE THREAD

**Issue by 01micko** [LBCrion/sfwbar#102]
I think this is a hangover from the conversion from `popen` ? Before that the firewall widget worked as expected.

If I have a `pipechar` (`|`)  in my shell call it doesn't seem to work. 

debug

```
07:49:44.96 include: firewall.widget -> /root/.config/sfwbar/firewall.widget
07:49:44.96 scanner: Status = 0.000000 (vstate: 1)
07:49:44.96 expr: "If(Status>10,"security-high","security-low")" = "security-low" (vstate: 1)
07:49:44.97 scanner: Status = 0.000000 (vstate: 1)
07:49:44.97 module: calling function `str`
07:49:44.97 scanner: Status = 0.000000 (vstate: 1)
07:49:44.97 expr: ""Firewall "+If(Status>10,"on","off")+" "+Str(Status,0)" = "Firewall off 0" (vstate: 1)
```

config

```
scanner {
  Exec("itables -L -n | wc -l") {
    Status = Grab(First)
  }
}

define On = "on"
define Off = "off"
define OnIcon = "security-high"
define OffIcon = "security-low"
define Ico = If(Status > 10,OnIcon,OffIcon)
define State = If(Status > 10,On,Off)

function("firewall_menu") {
  MenuClear "fw_opts"
  PipeRead "buildmenu.sh f"
  Menu "fw_opts"
}

layout {
  image {
    value = Ico
    interval = 5000
    tooltip = "Firewall " + State + " " + Str(Status,0) #### the Str(Status,0) is my debug
    action[1] = "firewall_ng"
    action[3] = Function "firewall_menu"
    css = "* { min-height: 30px; min-width: 30px; padding: 4px; }"
  }
}
```

**Comment by 01micko** [comment]
BTW, I am using latest git.

**Comment by LBCrion** [comment]
Can you please try using ``Exec("/ bin/sh -c itables -L -n | wc -l")``, I suspect the solution would be to change the code to add that prefix automatically to restore the original behaviour.

**Comment by 01micko** [comment]
Close.

This one works

`Exec("/bin/sh -c \"iptables -L -n | wc -l\"")`

**Comment by LBCrion** [comment]
Is it worth automating this behavior? On one hand this would retain compatibility with popen, on the other hand, it would always spawn a shell, even if the executable doesn't need it. I would prefer to keep the new behavior and let users manually add sh -c if needed, as it's more efficient for scenarios where shell isn't needed.

**Comment by 01micko** [comment]
> Is it worth automating this behavior?

No.

As long as it's documented than it's fine as is.
