### ISSUE TITLE
border for menus?

### ISSUE THREAD

**Issue by jonleivent** [LBCrion/sfwbar#103]
Is there a way to add a border for menus?  Do you have a full list of the css properties that sfwbar responds to?  The only examples of css properties for menus in the configs are #menu_item, alone and with image and label.

BTW: the alsa_widget is doing great, and my sfwbar cpu usage is down.  I added long intervals to a few other things, such as the clock (updates once per minute now).  However, I did see another crash, but didn't have my systemd core file collector daemon running at the time.  It had something to do with MapAppId, which I was trying to use to get a thunderbird icon working.  I fixed that instead by adding symlink to the right icon in my ~/.icons folder.

**Comment by jonleivent** [comment]
The closest I can get with #menu_item below is to add a border to each item, but what I'd like is a border around the full menu and not each item.
```
#menu_item {
  border-radius: 3px;
  border-color: @theme_fg_color;
  border-style: solid;
  border-width: 1px;
}
```

**Comment by jonleivent** [comment]
This is closer to what I want:
```
#menu_item {
  border-left: 1px solid @theme_fg_color;
  border-right: 1px solid @theme_fg_color;
}
```

**Comment by jonleivent** [comment]
Thanks!

**Comment by LBCrion** [comment]
Closing this for now. If you still need help with it, please feel free to reopen.
