### ISSUE TITLE
Icon changing in systray crashes sfwbar

### ISSUE THREAD

**Issue by yukijoou** [LBCrion/sfwbar#105]
Running sfwbar 1.0 beta 11 from the AUR in labwc. When toggling the mozc input method with fcitx5 (changes the tray icon), sfwbar regularly SIGSEGVs. This seems to also occur on other icon changes in the systray, but it's harder to notice as they are rarer, changing input method is something i can do a few hundred times per session.

**Comment by LBCrion** [comment]
Would you be able to check if this happens in the git version as well? You should be able to install it in arch as sfwbar-git. I suspect it may be a bug fixed in 760b3d6f5ea815da7bb01f37dd0d59d11f61f0a8

**Comment by yukijoou** [comment]
Seems like it's fixed in the git version! Though it also breaks changing icons altogether: the input method indicator doesn't update when I change input methods now…

A simpler test to reproduce the issue is to use something like nm-applet, and disable network connections: the icon won't reflect the change.

I'll stay on this version though, no change is better than a crash for sure, thanks for your work!

**Comment by LBCrion** [comment]
I just updated the git version, icons should update again now.

**Comment by yukijoou** [comment]
whoops! Yep, it works, thank you so much!
