### ISSUE TITLE
filter = workspace not working

### ISSUE THREAD

**Issue by jonleivent** [LBCrion/sfwbar#107]
using v1.0_beta12 with labwc compositor

`filter = workspace` in a taskbar does not work, but `filter = output` does work.

**Comment by LBCrion** [comment]
Filter = workspace isn't supported with labwc, since the necessary wayland
protocols don't exist yet. At the moment,  this feature requires a separate
ipc, such as those provided by sway or hyprland.

**Comment by jonleivent** [comment]
Sorry, I should have realized that.
