### ISSUE TITLE
Can't open winops menu

### ISSUE THREAD

**Issue by Flrian** [LBCrion/sfwbar#108]
Right clicking a taskbar item to open the winops menu doesn't work for me anymore after updating to the latest commit. 
I did a git bisect and:
`90d6b99658858b71f1a240abe7113cc3516f9645 is the first bad commit`

**Comment by LBCrion** [comment]
Can you please post the config file you're using? I'll try to check this
once I'm back form my break in a couple of days.

**Comment by LBCrion** [comment]
I just pushed a fix for this issue.  Can you try the latest git version
when you get a chance please?

**Comment by LBCrion** [comment]
Oops, some code needed removing as part of this fix. Should be fixed now.

**Comment by LBCrion** [comment]
Looking at the stack trace this is unrelated.  I just pushed what I think
should be a fix.  Can you try running the latest version please? I don't
have a system with an external monitor right now.

**Comment by LBCrion** [comment]
This is actually a different bug! Should be fixed in got as well now.

**Comment by LBCrion** [comment]
Interesting, the event in sway doesn't actually look like a crash. More like an orderly exit. Does this occur when you disconnect a monitor? Is this the last monitor connected or are there other monitors still connected when this happens?

**Comment by LBCrion** [comment]
I added a small cleanup in case the last monitor is disconnected. Not sure if this may help.

**Comment by LBCrion** [comment]
Cool. If it's working now, I expect turning off the monitor was indeed treated as a disconnect. I guess the intermittent mirror failure with labwc is still happening?

**Comment by LBCrion** [comment]
No problem at all! I really appreciate all the help with this one. I don't get much opportunity to test this codepath, since I do almost all of the development on a train.

**Comment by mozlima** [comment]
Hi, please keep action on grid too
like:
```
	grid {
		style ="clock"
		action[1] = Exec "gsimplecal"
		label {
			....
		}
		label {
			....
		}
	}
```

Now only works if set in each label

```
	grid {
		style ="clock"
		label {
			action[1] = Exec "gsimplecal"
			....
		}
		label {
			action[1] = Exec "gsimplecal"
			....
		}
	}
```

**Comment by LBCrion** [comment]
This should be fixed in the latest git version. Thank you for flagging!
