### ISSUE TITLE
Include flatpak apps in startmenu.widget

### ISSUE THREAD

**Issue by Flrian** [LBCrion/sfwbar#109]
If its not too complicated, would it be possible to include apps installed via flatpak in the startmenu widget?

**Comment by LBCrion** [comment]
I think this is a matter of checking the flatpack desktop entry directory.
I don't use flatpack myself,  so will need some help.  Can you please check:
1) the value of $XDG_DATA_DIRS variable on your system.
2) the contents of  /var/lib/flatpak/exports/share/applications directory?

**Comment by LBCrion** [comment]
Hi @Flrian, I updated the startmenu.widget to respect the XDG_DATA_DIRS variable. Can you try the latest git version to see if it correctly handles the flatpak applications for you now?

**Comment by LBCrion** [comment]
Symlinks shouldn't prevent this from working. Can you please check if sfwbar is picking up the updated widget from git? You can by running ``sfwbar -d -g startmenu.widget`` and then check if the widget file it loads contains XDG_DATA_DIRS. It should be easy enough to get XDG_DATA_HOME working as well once we get this one sorted.

**Comment by LBCrion** [comment]
That's odd. Can you try running the python script on it's own to see if there are any issues in it?

[test.txt](https://github.com/LBCrion/sfwbar/files/12562420/test.txt)

**Comment by LBCrion** [comment]
Ok, I see the issue. flatpack uses '=' in the Exec parameters and this has been messing with tag parsing. It should now be fixed in git. Would you mind giving it another try?

**Comment by LBCrion** [comment]
This should now be fixed with proper Exec command line parsing. I also added handling of XDG_CONFIG_HOME to tidy things up. Hopefully the current git should work.
