### ISSUE TITLE
How to change the colour of the bar itself? Is transparency supported?

### ISSUE THREAD

**Issue by milochadam** [LBCrion/sfwbar#11]
I would like to make the dark mode version but I don't know how to specify background colour for the sfwbar itself. Also, I would like to modify transparency. Is it possilble to do or is it viable to implement?

**Comment by LBCrion** [comment]
You can specify either of these via css style sheet. For transparency, add the following:

window {
background: transparent;
}

You may also remove button borders and shadows to make transparent bar look nice:

button {
background: transparent;
border: none;
box-shadow: none;
}

In the last release window style will apply to both the bar window and the switcher window. I added the naming in the main branch to allow specifying css for window#sfwbar and window#switcher to separately style the two.

For the dark theme, you can specify background-color: #......; in the window css node to set the background color.

I'd love to see the result. Would be good to have more examples of what can be achieved with various configs!

**Comment by milochadam** [comment]
Currently looks like this:
![image](https://user-images.githubusercontent.com/27895477/147854340-a9e86abb-27bf-4053-a4ba-4d872f3cc35b.png)

The missing icon in the middle is of a dummy widget I use as a spacer. How can I hide the icon?
Discord icon in the tray is also missing for some reason.
Discord's and Steam's menu looks like this:
![image](https://user-images.githubusercontent.com/27895477/147854434-53403c41-f8fc-4fff-850c-e98d157dbedd.png)
How can I change their style?

**Comment by LBCrion** [comment]
For a spacer widget, I suggest using a blank label:

label {
 css = "* { -GtkWidget-hexpand: true; }"
 value =""
}

Discord sends an icon name of discord1_1, but at least on gentoo the discord application doesn't have an icon with this name. I suggest grabbing an svg icon for discord from the web and saving it to a file discord1_1 (without an extension) in ~/.config/sfwbar/

**Comment by milochadam** [comment]
Creating `discord1_1` didn't work. Could you tell me how you know it's looking for `discord1_1`?

**Comment by LBCrion** [comment]
if you run sfwbar -d with the current git version and start discord, you should get a lot of output, but one line should be sni :x.xx: property IconName = <something>, the filename for the discord icon is <something> in this example. It may be easier to dump debug output into a file with sfwbar -d 2>tempfile and then look for this string in the text file.

**Comment by milochadam** [comment]
The output of `< /tmp/sfwbar.log grep discord` is
```
22:50:31,75 sni: host org.kde.StatusNotifierHost-248582: item registered: :1.404 /org/ayatana/NotificationItem/discord1
22:50:31,84 image: discord1_16 @ -1
22:50:31,85 image: discord1_16 @ 16
```
Creating discord1_16 fixed it.

The last thing I'm missing for styles is tray menu colours, would you mind giving me a pointer what styles are responsible for this (if you know of course)? I'm speaking of the image I posted in a comment above:
![image](https://user-images.githubusercontent.com/27895477/147854434-53403c41-f8fc-4fff-850c-e98d157dbedd.png)

**Comment by LBCrion** [comment]
For Gtk menus, the relevant css nodes are menu and menuitem. i.e.

menu, menuitem {
background: #222222;
}

menuitem * label {
color: #cccccc;
}

You may need to remove color: #000000; from the label section in css, since it will override your menu text color back to black.

**Comment by milochadam** [comment]
![image](https://user-images.githubusercontent.com/27895477/147879291-758cb758-72fc-4905-8f47-f1004078cad4.png)

**Comment by LBCrion** [comment]
It looks like discord specifies the icon location via a IconThemePath property (which isn't part of the freedesktop SNI specification). The latest git main branch should handle this icon without needing to save a file in a local directory.

**Comment by milochadam** [comment]
Unfortunately Discord icon still doesn't load without files in `~/.config/sfwbar`

**Comment by LBCrion** [comment]
Would you mind checking if the debug output shows property IconThemePath for discord if you run sfwbar with -d? If it does, can you check the contents of the directory it points to (you need to keep discord running while checking).

**Comment by milochadam** [comment]
```
06:48:47,71 sni :1.41: property IconThemePath = /tmp/.org.chromium.Chromium.jAB8us
06:50:24,16 sni: received signal NewIconThemePath from :1.41
```
and
```
06:48:47,71 sni: host org.kde.StatusNotifierHost-11089: item registered: :1.41 /org/ayatana/NotificationItem/discord1
06:48:47,71 sni :1.41: property Id = discord1
06:48:47,71 sni :1.41: property Title = discord
06:48:47,71 sni :1.41: property IconName = discord1_3
06:48:47,78 image: discord1_3 @ -1
06:48:47,78 image: discord1_3 @ 16
06:50:24,16 sni :1.41: property IconName = discord1_4
06:50:24,16 sni :1.41: property IconName = discord1_4
06:50:24,26 image: discord1_4 @ 16
```
When there was a Discord icon there was a discord1_3.png but when there is no Discord icon (when there is a new notification or I read all new messages I suppose) "No such file or directory"

**Comment by LBCrion** [comment]
Ok, we need to handle the NewIconThemePath signal. Added this in the latest git.
