### ISSUE TITLE
Udiskie tray interaction

### ISSUE THREAD

**Issue by igorepst** [LBCrion/sfwbar#112]
Hello @LBCrion.
I have an issue with `udiskie` interaction in tray, using `sway` 1.8.1, `udiskie` 2.5.0 and `sfwbar` with latest commit `f66f110`. 
I run `udiskie --smart-tray &` from a script running as `exec` in `sway` (actually it doesn't matter much as this command may be run from terminal after `sfwbar` is started and get the same behavior).
1. Smart tray option means that the tray icon is hidden until a removable device is connected. However in `sfwbar` it is shown immediately
2. More important is that although the device is mounted/unmounted correctly, the managed devices list in `udiskie` tray menu doesn't change. If the device is connected after running the program, the menu shows no devices. If `udiskie` is restarted with USB connected, the tray shows connected device. If the device is pulled out of the USB, the tray still shows previously connected device. "Quit" and checkbox options in tray doesn't work either, although device operations (`unmount`/`unpower`) work.

I tried with `waybar` to compare, and there both issues do not exist. What's probably interesting, is that if `waybar` runs as an executable from a terminal when `sfwbar` runs as well (I have `bar {swaybar_command sfwbar}` in `sway`), operations on the tray of `udiskie` on `waybar` seem to reinitialize something in `sfwbar`, causing it to update and then the second issue disappears.
Could you, please, take a look? Thanks in advance

**Comment by LBCrion** [comment]
For the first issue, this looks like a matter of showing vs hiding the passive tray items. sfwbar shows them by default, while waybar hides them. Can you please try adding the following snippet to the CSS stylesheet of sfwbar, to see if it gives you the desired behavior? 
```
button#tray_passive {
  -GtkWidget-visible: false;
}
```

**Comment by LBCrion** [comment]
For (2), It looks like we need to call AboutToShow on the menu before calling GetLayout to get an update menu. Can you test the latest git version to see if it works as expected now?

**Comment by igorepst** [comment]
I will for sure a bit later. Thank you for your work

**Comment by igorepst** [comment]
@LBCrion Thank you very much for the fix and for the speed of it! Both issues are resolved fully with the help of the latest commit and the CSS
