### ISSUE TITLE
how to dynamically add/remove elements from layout?

### ISSUE THREAD

**Issue by bdantas** [LBCrion/sfwbar#115]
I love sfwbar and use it daily with my Tiny Core Linux box running labwc. I packaged sfwbar for the official TCL x86_64 repo so that other users can enjoy it too.

Quick question: Is there a way to dynamically add/remove elements (e.g., a button or widget) from the bar, short of editing ~/.config/sfwbar/sfwbar.config then doing `pkill sfwbar; sfwbar &`? My hope is to be able to do this without the bar completely disappearing at any point.

P.S. When running Xorg with fluxbox, I used to accomplish this with `yad --notification` and writing to an associated named pipe. Alas, yad does not support support this functionality in wayland.

**Comment by keshto** [comment]
Maybe include what your use case is to see if there is another way of accomplishing what you want?

**Comment by bdantas** [comment]
At home I have a subnet whose addresses go through VPN tunnel, and a subnet whose addresses bypass the VPN tunnel. When I would run X with fluxbox, a shell script runs every few seconds and, based on local IP address, shows "vpn off" or "vpn on" icon.

I guess the bottomline is that sfwbar is not setup in such a way that icons can be added/changed from shell scripts directly, right? If so, I think the solution is to convert the script into a custom widget that accomplishes the same thing.

**Comment by LBCrion** [comment]
There are a few ways to accomplish this. If you want to continue using your script, you can use RT signals to communicate state changes to sfwbar. I.e. in your script, i.e. ``pkill --signal RTMIN+5 sfwbar`` when vpn is on and ``pkill --signal RTMIN+6 sfwbar`` when it's off.

In your config you can then add:
```
TriggerAction "SIGRTMIN+5" SetValue "vpn_widget", "vpn: on"
TriggerAction "SIGRTMIN+6" SteValue "vpn_widget", "vpn: off"

layout {
  ...
  label "vpn_widget" { }
  ...
}
```

This config will create an empty label with a widget id of "vpn_widget" and  update its value upon receiving signals RTMIN+5 and RTMIN+6.

**Comment by LBCrion** [comment]
Of course I originally wrote sfwbar's predecessor because I hate the idea of having to repeatedly run scripts to update my taskbar! So, there is a better way to do this:

```
module("network")

layout {
  ...
  label {
    value = If(NetInfo("interface") = "vpn_interface", "vpn: on", "vpn: off")
    trigger = "network"
  }
  ...
}
```

This will use sfwbar's network module to monitor to current network interface (based on the default gateway) and update a label depending on whether it's an interface belonging to your vpn. You will need to replace ``vpn_interface`` with a correct value of course.

If you prefer to use your IP as a deciding input, you can use that as well:

`` value = If(NetInfo("ip") = "a.b.c.d", "vpn: on", "vpn: off")``

You can also add an action to your label to toggle the vpn i.e.:
`` action[RightClick] = Exec "toggle-vpn-script"``

**Comment by LBCrion** [comment]
And to answer you original question: you can add and remove widgets on the fly!

Let's take the following example: 
```
layout {
  ...
  grid "MyGrid" {
     label  "MyLabel" {
       value = "test"
     }
   }
...
}
```

We can delete the label using an action ``ClearWidget "MyLabel"`` and add it back using an action:
``Config "layout { grid 'MyGrid' { label 'MyLabel' { value = 'test' } } }"``

The above is a bit of a heavy handed approach, as it literally tears down and rebuilds the widgets on the fly. In most cases, hiding a widget may be enough. This can be done with: ``SetStyle "MyLabel", "hidden"`` to hide a widget and ``SetStyle "MyLabel", "MyStyle"`` to restore it. This assumes you have a hidden CSS style defined. It's defined in most of the default configs, but you can always define it in the CSS section:

```
#CSS
...
#hidden {
  -GtkWidget-visible: false;
}

#MyStyle {
  color: red; 
}
```

**Comment by bdantas** [comment]
Wow, thank you for the wealth of information! I actually like the idea of independent scripts updating the task bar. Funny how people are different that way. I like all your proposed solutions but my favorite is the RT signals approach.

I prefer to update an icon rather than a string on the panel. Can you help me figure out why this in sfwbar.config isn't working?

```
TriggerAction "SIGRTMIN+5" SetValue "vpn_widget", "/opt/scripts/icons/locked.png"
TriggerAction "SIGRTMIN+6" SetValue "vpn_widget", "/opt/scripts/icons/unlocked.png"

layout {
  include("showdesktop.widget")
  button "vpn_widget" { }
```

**Comment by bdantas** [comment]
Aha! It was a simple syntax issue (a missing comma). This works:

```
TriggerAction "SIGRTMIN+5", SetValue "vpn_widget", "/opt/scripts/icons/locked.png"
TriggerAction "SIGRTMIN+6", SetValue "vpn_widget", "/opt/scripts/icons/unlocked.png"

layout {
  button "vpn_widget" { }
  ...
```
Is it possible to SetValue and SetTooltip with same signal? If so I can't seem to figure it out.

**Comment by Consolatis** [comment]
> Is it possible to change the button's icon (SetValue) and tooltip (SetTooltip) with same signal? If not, no biggie. The above is already a beautiful solution :)

I think you can use a function for that: https://github.com/LBCrion/sfwbar/blob/main/doc/sfwbar.rst#actions + https://github.com/LBCrion/sfwbar/blob/main/doc/sfwbar.rst#functions

**Comment by bdantas** [comment]
Yes, that will do nicely. Thank you both for you all your help!

**Comment by bdantas** [comment]
Wow, anytime my script runs `pkill -RTMIN+6 sfwbar` to change vpn icon, sfwbar changes the icon but also closes my web browser (brave-browser). This is very unexpected behavior. How do I tell sfwbar to please not close any windows when it receives RT signals?

**Comment by LBCrion** [comment]
That shouldn't be happening.  Can you post your config file please?

**Comment by bdantas** [comment]
Sure thing:
```
Set Term = "havoc"

TriggerAction "SIGRTMIN+5", SetValue "vpn_widget", "/opt/scripts/media/spikey.png"
TriggerAction "SIGRTMIN+6", SetValue "vpn_widget", "/opt/scripts/media/lock.png"
TriggerAction "SIGRTMIN+7", SetValue "printer_widget", "/opt/scripts/media/printer-white.png"            
TriggerAction "SIGRTMIN+8", SetValue "printer_widget", "/opt/scripts/media/printer-green.png"
TriggerAction "SIGRTMIN+9", SetValue "printer_widget", ""            
TriggerAction "SIGRTMIN+10", SetValue "printer_widget", "/opt/scripts/media/printer-red.png"        

# Window Placer
placer {
  xorigin = 5  # place the first window at X% from the left
  yorigin = 5  # place the first window at X% from the top
  xstep = 5    # step by X% of desktop horizontally
  ystep = 5    # step by X% of desktop vertically
  children = true
}

# Task Switcher
switcher {
  interval = 700
  icons = true
  labels = false
  cols = 5
}

function("SfwbarInit") {
  SetBarId "bar-0"
  SetLayer "top"
}

include("winops.widget")

# Panel layout

# Window Placer
placer {
  xorigin = 5  # place the first window at X% from the left
  yorigin = 5  # place the first window at X% from the top
  xstep = 5    # step by X% of desktop horizontally
  ystep = 5    # step by X% of desktop vertically
  children = true
}

# Task Switcher
switcher {
  interval = 700
  icons = true
  labels = false
  cols = 5
}

function("SfwbarInit") {
  SetBarId "bar-0"
  SetLayer "top"
}

include("winops.widget")

# Panel layout

layout {
  include("showdesktop.widget")
  #include("startmenu.widget")

  #button {
  #  style = "launcher"
  #  value = $Term
  #  action = Exec $Term
  #}

  #button {
  #  style = "launcher"
  #  value = "brave-browser"
  #  action = "brave-browser"
  #}

  pager {
    style = "pager"
    rows = 1
    preview = true
    numeric = true
  }

  taskbar {
    rows = 1
    css = "* { -GtkWidget-hexpand: true; }" # stretch horizontally
    icons = true
    labels = true
    action[3] = Menu "winops"
    action[2] = Close
  }

  #include("idle.widget")
  include("cpu.widget")
  include("memory.widget")

  tray {
    rows = 1
  }

  include("battery-svg.widget")
  include("bluez.widget")
  include("network-module.widget")
  button "vpn_widget" { style = "launcher" tooltip = "vpn status" }
# Select pulse-module or alsa-module based on your sound configuration
# include("pulse-module.widget")
  include("alsa-module.widget")
  include("mpd-intmod.widget")
  include("sway-lang.widget")
  button "printer_widget" { style = "launcher" tooltip = "printer status" }
  grid {
    css = "* { padding-left: 5px; padding-right: 5px; }"
    label {
      value = Time("%a %b %e")
      loc(1,1)
      action[LeftClick] = Exec "calendar-toggle"
    }
    label {
      value = Time("%l:%M %p")
      loc(1,2)
      action[LeftClick] = Exec "calendar-toggle"
    }
  }
}

#CSS
@define-color theme_text_color white;
@define-color theme_bg_color black;
@define-color theme_fg_color white;
@define-color borders rgba(256,256,256,0.3);

window#sfwbar {
  -GtkWidget-direction: top;
  background-color: rgba(0,0,0,0.6);
}

grid#layout {
  -GtkWidget-direction: right;
  min-height: 30px;
}

grid {
  padding: 0px;
  margin: 0px;
}

tooltip {
  background-color: @theme_bg_color;
}

image {
  min-width: 18px;
  min-height: 18px;
  box-shadow: none;
  border: none;
  border-image: none;
  background-image: none;
  background: none;
  -gtk-icon-shadow: none;
}

button {
  box-shadow: none;
  border-image: none;
  background-image: none;
  background: none;
  outline-style: none;
}

menu {
  background-color: black;
  border: 1px solid @borders;
  padding: 3px;
}

menu arrow {
  background-color: rgba(0,0,0,0);
  color: @theme_text_color;
}

menuitem {
  color: @theme_text_color;
  padding: 2px;
}

menu image {
  padding-right: 5px;
}

progressbar trough {
  background-color: rgba(256, 256, 256, 0.5);
  border-color: rgba(256,256,256,0.5);
}

#hidden {
  -GtkWidget-visible: false;
}

button#taskbar_normal grid {
  -GtkWidget-hexpand: false;
}

button#taskbar_normal image,
button#taskbar_active image,
button#taskbar_normal:hover image {
  min-width: 24px;
  min-height: 24px;
}

button#taskbar_normal label,
button#taskbar_active label,
button#taskbar_normal:hover label {
  padding: 0px 0px 0px 5px;
  -GtkWidget-hexpand: false;
}

button#taskbar_normal,
button#taskbar_active,
button#taskbar_normal:hover {
  padding: 0px 5px 0px 5px;
  border-radius: 4px;
  background-color: rgba(119,119,119,0.2);
  border-color: rgba(119,119,119,0.3);
  -GtkWidget-hexpand: false;
}

button#taskbar_active {
  background-color: rgba(255,255,255,0.2);
  border-color: rgba(255,255,255,0.4);
}

button#taskbar_normal:hover,
button#taskbar_active:hover {
  background-color: rgba(176,176,176,0.22);
  border-color: rgba(234,234,234,0.44);
}

button#pager_normal,
button#pager_visible,
button#pager_focused {
  padding: 0px 5px 0px 5px;
  border-radius: 4px;
  background-color: rgba(119,119,119,0);
  border-color: rgba(119,119,119,0);
}

button#pager_focused {
  background-color: rgba(119,119,119,0.2);
  border: none;
}

button#pager_preview {
  border-radius: 0;
  border-color: #000000;
  border-width: 0.25mm;
  color: #777777;
  min-width: 5cm;
  min-height: 2.8125cm;
}

grid#switcher_active image,
grid#switcher_active {
  min-width: 60px;
  min-height: 60px;
  border-image: none;
  padding: 6px;
  background-color: #777777;
  border: 0px;
  box-shadow: none;
  border-radius: 1.25mm;
  -GtkWidget-hexpand: true;
}

grid#switcher_normal image,
grid#switcher_normal {
  min-width: 60px;
  min-height: 60px;
  padding: 6px;
  -GtkWidget-direction: right;
  -GtkWidget-hexpand: true;
}

window#switcher { 
  background-color: rgba(0,0,0,0);
  padding: 6px; 
  -GtkWidget-hexpand: true;
}

grid#switcher { 
  border-radius: 6px;
  background-color: @theme_bg_color;
  border: 1px solid @borders;
  padding: 6px;
  box-shadow: none;
  -GtkWidget-hexpand: true;
}

button#tray_active,
button#tray_passive,
button#tray_attention {
  padding: 0px 1px 0px 0px;
  border: none;
  margin: 0px;
  -GtkWidget-valign: center;
}

button#startmenu image,
button#module image{
  -ScaleImage-color: @theme_text_color;
}

button#module,
button#launcher,
button#showdesktop,
button#startmenu {
  padding: 0px 3px 0px 3px;
  border: none;
  -GtkWidget-valign: center;
}

button#startmenu {
  border: 1px solid;
  border-radius: 4px;
}

button#startmenu image {
  min-width: 18px;
  min-height: 18px;
  padding: 1px;
}

chart#cpu_chart {
  background: rgba(127,127,127,0.3);
  min-width: 9px;
  margin: 2px;
  border: 1px solid @borders;
  color: red;
}

progressbar#memory {
  -GtkWidget-direction: top;
  min-width: 9px;
  border: 1px solid @borders;
  margin: 2px;
}

progressbar#memory trough {
  min-height: 2px;
  min-width: 9px;
  border: none;
  border-radius: 0px;
  background: rgba(127,127,127,0.3);
}

progressbar#memory progress {
  -GtkWidget-hexpand: true;
  min-width: 9px;
  border-radius: 0px;
  border: none;
  margin: 0px;
  background-color: alpha(green,0.9);
}

label#sway_lang {
  margin-left: 3px;
  margin-right: 5px;
}

label {
  font: 12px Sans;
  color: @theme_text_color;
  text-shadow: none;
}

* {
  -GtkWidget-vexpand: true;
}
```

**Comment by bdantas** [comment]
sfwbar may be innocent. When I direct brave-browser's stdout and stderr to a log file, I consistently see this as the last line of the log: 
```
/usr/local/bin/brave-browser: line 48:  8224 Real-time signal 6      "$HERE/brave" "$@"
```
Why is brave catching this signal, which is clearly directed at sfwbar? Very odd.

**Comment by LBCrion** [comment]
I think I see what is happening. I'm guessing your Brave window has an sfwbar page open (or was launched to open sfwbar page) and pkill matches it and sends RTMIN+6 to brave as well. Brave doesn't have a handler for the signal and shuts down.  Can you try replacing ``pkill --signal RTMIN+6 sfwar`` with ``pkill -x --signal RTMIN+6 sfwbar``

**Comment by bdantas** [comment]
> I'm guessing your Brave window has an sfwbar page open (or was launched to open sfwbar page)
 
Haha, yes. Now I see that the problem happens with when I click on a link in my email client to come to sfwbar's Github page. I can confirm that the problem is solved by using `pkill -x -RTMIN+6 sfwbar`. I'm relieved the very strange behavior turned out to have such a banal explanation :)

**Comment by LBCrion** [comment]
Phew. This nearly gave me a heart attach. I certainly don't expect such an
inconsiderate behavior from sfwbar.

**Comment by Consolatis** [comment]
Also started to think about what labwc could have done to cause this.
Seems like browsing any website with "sfwbar" in the title can be very dangerous for the browser :p

**Comment by bdantas** [comment]
> Seems like browsing any website with "sfwbar" in the title can be very dangerous for the browser :p
 
Very dangerous, but my browser can handle it because it's _brave_ :p

Seriously, though, thanks for all your help. I will test and report on the new battery widget later. Now I need to stop "playing" on the computer lest the wife and the boss get upset.

**Comment by bdantas** [comment]
@LBCrion  - Sorry to bother again. At this point I know how to use file scanner to read a file's contents for a tooltip. But for my application the tooltip changes very seldom--once or twice a day. Instead of using `interval` for the scanner, is there a way to run scanner only when a certain RT signal is sent to sfwbar?

**Comment by bdantas** [comment]
P.S. I figured out how to associate RT signal with a function. But in function I am only able to set tooltip to a literal string, when I need tooltip to be read from file.

**Comment by LBCrion** [comment]
Scanner only reads the contents of the file when a variable value is needed
in an expression (i.e. when a widget updates a value referencing a
variable), you can replace:
interval = x
with:
trigger = "RTMIN+Y"
in your widget definition and the scanner will only read the file upon
receiving an RT signal.

**Comment by LBCrion** [comment]
Just saw that this is for a tooltip. Tooltips don't update on an interval
or a trigger, they update on demand (whenever tooltip is displayed), but
then they get refreshed a lot (whenever you move a pointer within a
widget). To update a tooltip on an RT signal you can do the following:

TriggerAction "RTMIN+X", Eval "MyTooltipVar", "Value: " + $MyScannerVar
...
  tooltip = $MyTooltipVar

This will change the value of MyTooltipVar on receiving the RT signal and
this value will be displayed in the tooltip.

**Comment by bdantas** [comment]
> you can replace: interval = x with: trigger = "RTMIN+Y" in your widget definition and the scanner will only read the file upon receiving an RT signal.
 
That's exactly the missing piece I was looking for. Now I think I have all the parts I need to make a beautiful custom widget. Thank you!

**Comment by bdantas** [comment]
Hmm, when I change ~/.config/sfwbar/misc.widget from this
```
scanner {
  exec("sh -c 'cat /tmp/misc-widget-icon'") {
    desired_icon = RegEx("(.*)")
  }
}

layout {
  button {
    value = $desired_icon
    interval = 1000
    style = "launcher"
    tooltip = "misc"
  }
}
```
to this:
```
scanner {
  exec("sh -c 'cat /tmp/misc-widget-icon'") {
    desired_icon = RegEx("(.*)")
  }
}

layout {
  button {
    value = $desired_icon
    trigger = "RTMIN+10"
    style = "launcher"
    tooltip = "misc"
  }
}
```
The widget does not respond to RTMIN+10. Do I need to configure something about RTMIN+10 in sfwbar.config as well?

**Comment by LBCrion** [comment]
Yes, the ``trigger=`` approach only works for value and style,  for tooltip you need to use the Eval approach in: https://github.com/LBCrion/sfwbar/issues/115#issuecomment-1817935513

**Comment by bdantas** [comment]
I tried using this approach with value (to change icon on signal) as shown in my previous post) and it didn't work.

**Comment by bdantas** [comment]
More tinkering led to the solution. In `misc.widget` I needed to change
interval = x
to
trigger = "**SIG**RTMIN+Y"

The full name of the signal is required. This is working as expected in `~/.config/sfwbar/misc.widget`:
```
scanner {
  exec("sh -c 'cat /tmp/misc-widget-icon'") {
    desired_icon = RegEx("(.*)")
  }
}

layout {
  button {
    value = $desired_icon
    trigger = "SIGRTMIN+10"
    style = "launcher"
    tooltip = "misc"
  }
}
```
Nothing special is needed in ~/.config/sfwbar/sfwbar.config, only this in the desired place:
```
  include("misc.widget")
```

**Comment by bdantas** [comment]
> Tooltips don't update on an interval or a trigger, they update on demand (whenever tooltip is displayed), but then they get refreshed a lot (whenever you move a pointer within a widget).
 
That's perfect, actually. It's just polling for a changed icon every second that was bothering me in the original version of my custom widget.

So here is the final version, which updates the icon whenever RTMIN+10 is received, and updates the tooltip whenever I hover over the icon:

```
scanner {
  exec("sh -c 'cat /tmp/misc-widget-icon'") {
    desired_icon = RegEx("(.*)")
  }
  exec("sh -c 'cat /tmp/misc-widget-tooltip'") {
    desired_tooltip = RegEx("(.*)")
  }
}

layout {
  button {
    value = $desired_icon
    trigger = "SIGRTMIN+10"
    style = "launcher"
    tooltip = $desired_tooltip
  }
}
```
Now that it is working, it seems amazing that sfwbar enables this result with such a succinct configuration.
