### ISSUE TITLE
Can't see udiskie in tray anymore

### ISSUE THREAD

**Issue by igorepst** [LBCrion/sfwbar#116]
Hi, @LBCrion . 
Continuing #112 and probably as a consequence of #113, I cannot see `udiskie` in tray anymore, neither with `--tray` nor with `--smart-tray`, and with commented out section of

    button#tray_passive {
     -GtkWidget-visible: false;
    }

If additional information is needed, I will gladly provide it.

Edit: sorry, upon further investigation, I found out that `libappindicator-gtk3` should be installed to show a tray icon, which is a bit strange, as `udiskie` has the very same version of 2.5.0-1 that it had when you helped with #112, and then the icon was showing... But nevermind...

Completely unrelated question, if possible. I would like, say, add an action to the built-in widget, defined as `include("battery-svg.widget")`. Do I need to assign an ID to it? If so, how?

Thank you in advance

**Comment by LBCrion** [comment]
The easiest way to modify a default widget is to copy it into your sfwbar config directory and modify it. So, just copy battery-svg.widget (usually from ``/usr/share/sfwbar/``) to your config dir (usually ``$HOME/.config/sfwbar``) and add an action to it.

I am planning a simplified widget addressing mechanism to allow easier widget modifications, but it's not there yet.

**Comment by igorepst** [comment]
Fine, thank you!
