### ISSUE TITLE
how to make battery.widget tooltip show both percentage and time remaining?

### ISSUE THREAD

**Issue by bdantas** [LBCrion/sfwbar#117]
I took a look at /usr/local/share/sfwbar/battery.widget and see that it is mostly python, which is not my forte.

Widget's default is to show only battery percentage in the tooltip. How do I make it show both percentage and estimated time remaining before battery runs out? 50% can mean "no problem" or "rush to an outlet now!" depending on battery's age ;)

**Comment by Consolatis** [comment]
Generic approaches:

`upower -d`  + some parsing (`while read -r key value; do test "$key" = "percentage" && do_something_with_value; done` should work fine). This requires a running dbus session and upowerd though.

Alternative: bash example, could be used to update the Python one (I think its only missing `current_now`).

```bash
#!/bin/bash

BAT=/sys/class/power_supply/BAT0
if test "$(< "$BAT/status")" != "Charging"; then
	min_remaining=$(bc <<< "scale=2; $(< "$BAT/charge_now") / $(< "$BAT/current_now") * 60")
	printf "%.0f minutes remaining\n" "$min_remaining"
fi
```

**Comment by bdantas** [comment]
Hello again, Consolatis. Thanks for the pointers. I was able to write a shell script that runs every few seconds and outputs what I would like to be shown as a tooltip to a file called /tmp/battery-status:
```
$ cat /tmp/battery-status
82% 4h 33m
```
I made a mistake--my sfwbar.config is actually a copy of t2.config, so the battery widget is called battery-svg.widget

Pardon the noob question, but how would I edit battery-svg.widget so that it works the same as usual, except that it displays the current contents of a file (/tmp/battery-status in this case) as the tooltip?

**Comment by LBCrion** [comment]
You can copy battery-svg.widget in your config directory (usually from ``/usr/share/sfwbar`` to ``$HOME/.config/sfwbar``) and then edit it. I can add a scan variable for current now, so you can void running scripts.

That said, this is a good idea and the only reason I've never added this by default is because my ancient laptop doesn't support it.  I added it to the latest git version now. If you can test it, it would be much appreciated.

**Comment by bdantas** [comment]
Thank you for adding this. I will be happy to test it later today.

In meantime can you please help me figure out how to edit `$HOME/.config/sfwbar/battery-svg.widget` (which starts as an exact copy `/usr/share/sfwbar/battery-svg.widget`) so that it uses a file's contents as its tooltip? It is a useful general principle and a helpful stepping stone for this noobie's understanding of sfwbar.

**Comment by bdantas** [comment]
Hi LBCrion. No luck with the new battery-svg.widget. With new widget on my system as `~/.config/sfwbar/battery-svg.widget`, no battery icon at all shows up after restarting sfwbar or after a reboot.

**Comment by bdantas** [comment]
I figured out how to edit the original battery-svg.widget to get tooltip from a file. I'll post relevant parts (very top and very bottom of the file) here in case it is helpful to other noobs:
```
scanner {
  tooltip_text = file("/tmp/battery-status") {
    tooltip_text = RegEx("(.*)")
  }
}
set XBatteryLevel = If(!Ident(BSDCtl),XBatteryLeft / XBatteryTotal * 100,BSDCtl("hw.acpi.battery.level.life"))
...
layout {
  style = "module"
  button "XBatteryModule" {
    action[0] = PipeRead If(!Ident(BSDCtl),XBatteryInit,"")
    value = $XBatterySvg
    style = If(!Ident($XBatteryState) & !Ident(BSDCtl),"hidden","module")
    tooltip = $tooltip_text
    interval = 1000
  }
}
```
I'm still up for testing your new widget, though.

**Comment by LBCrion** [comment]
Scanner is indeed the way to read files. For tooltip, your approach works quite well, the file will be read whenever sfwbar updates the tooltip.

For periodic updates, you can also use ``Exec`` instead of ``File`` in the scanner and run script directly from sfwbar. This is better suited for cases where you update value from the script rather than a tooltip.

**Comment by LBCrion** [comment]
When you try the new battery-svg.widget, does sfwbar report any errors in the terminal?

**Comment by bdantas** [comment]
Yes, it does. "python not found". Which reminded me that when I packaged sfwbar for TCL, I had to change `python` to `python3` in the battery* and startmenu* widgets. My bad.
 
Once I change `python` to `python3` in this new version of battery-svg.widget, the widget works but is reporting "95% 0h7m", which is not believable. What `acpi` reports is closer to the time I actually get from this battery:
```
$ acpi -b
Battery 0: Discharging, 95%, 07:58:07 remaining
```
I think the time calculation may need to be revised.

**Comment by LBCrion** [comment]
Oops. I forgot to multiply by 60. It should be fixed now.

**Comment by bdantas** [comment]
I can confirm that it works like a charm now.

LBCrion and Consolatis, I love your software. labwc + sfwbar is the Dream Team. I expected my Wayland box to be just an uncomfortable-to-use testing environment but, thanks to your two projects, I actually like it better than my Xorg + fluxbox daily driver!

Thanks for all your help. Happy hacking!
