### ISSUE TITLE
placing bar at the corner of the screen?

### ISSUE THREAD

**Issue by pablo-888** [LBCrion/sfwbar#118]
Sorry if i've missed something obvious but I only see options for having the bar at the bottom, top, left, and right. Assuming i've set my bar to not take the full width of the monitor, is there an option to place it at the the bottom-right or bottom-left rather than the center?. Thanks.

**Comment by LBCrion** [comment]
This functionality is indeed currently missing. The good news, it should be easy to implement. Give me a couple of days and I'll try to add it.

**Comment by LBCrion** [comment]
I pushed support for this into the current git. You should now be able to use ``-GtkWidget-halign`` and ``-GtkWidget-valign`` properties for the window node to control the bar alignment.

I.e. the below CSS snippet should put the bar on the bottom of the screen and align it to the left corner.
```
window#sfwbar {
  -GtkWidget-direction: bottom;
  -GtkWidget-halign: start;
}
```

**Comment by pablo-888** [comment]
Perfect. Thank you!
