### ISSUE TITLE
how to prevent windows from opening behind sfwbar?

### ISSUE THREAD

**Issue by bdantas** [LBCrion/sfwbar#119]
I have sfwbar going across the top. My config is a minimally tweaked version of /usr/local/share/t2.config. Some windows are opening partly behind the bar, causing top of those windows to be obscured. It's a pain to constantly have to drag windows down so that I can see all of them. Also, dmenu opens behind the bar, causing it to be completely obscured when the menu is going horizontally.

Is there a way to prevent anything from ever opening behind sfwbar? In other words, is it possible to make the bar's space to be considered completely unavailable as far as wayland/compositor is concerned? I'm on labwc.

P.S. I discovered that windows that open away from bar can also be placed behind the bar by dragging. When I try it, the window first snaps into place just below the bar but if I continue to drag then it unsnaps and goes behind the bar.

**Comment by LBCrion** [comment]
You can move the bar to the bottom layer by changing ``SetLayer "top"`` to ``SetLayer "bottom"`` in the ``SfwbarInit`` function. You can also leave the bar on the top layer and add ``SetExclusiveZone "auto"`` to the ``SfwbarInit`` function. This should prevent the compositor from opening new windows under the bar (but you may still be able to move them under the bar manually).

**Comment by bdantas** [comment]
I like your second idea (keeping bar on top layer but preventing compositor from opening windows behind it). But, alas, compositor keeps doing it even though my `SfwbarInit` function looks like this now:
```function("SfwbarInit") {
  SetBarId "bar-0"                                                              
  SetLayer "top"                                       
  SetExclusiveZone "auto"                                                       
}   
```
 
I tried just restarting `sfwbar` and I also tried a full reboot. Windows still opening behind the bar :/

**Comment by LBCrion** [comment]
I don't believe these is a guaranteed way to prevent the compositor from placing the window over or under the bar. The layer shell protocol doesn't guarantee that the exclusive zone is actually not occluded by other windows. To quote the protocol:
```
Requests that the compositor avoids occluding an area with other surfaces. The compositor's use of this information is implementation-dependent - do not assume that this region will not actually be occluded.
```
 @Consolatis - do you know if there is  a way in labwc to force strict interpretation of layer shell exclusive zones? (i.e. guarantee non-occlusion)

**Comment by bdantas** [comment]
@Consolatis - This issue affects sfwbar whether it is running in labwc version 0.6.5 or labwc latest git (7aa1dc1).

**Comment by Consolatis** [comment]
labwc only prevents automatic placement of windows in the exclusive zone, e.g. when maximized / snapped to edge / regions.
New windows are spawned in the center with the client requested size (unless started maximized / fullscreen). This means that when using a smaller screen resolution - smaller than the client requested window height - a new window might end up over / under a panel. Feel free to open an issue about this at the labwc repo, I don't think we can do much about a new client window overlapping a bottom panel in this case but we may be able to adjust it for top panels with exclusive zone.

Personally I always prefer the "bottom" layer + "exclusive zone".

**Comment by bdantas** [comment]
Sounds good. For now I'll move sfwbar to bottom layer as you guys suggest, so I can see the whole window. But I'll open an issue at labwc repo because it looks weird for newly-opened windows to obscure part of the panel. Thanks, guys.
