### ISSUE TITLE
possible for both taskbar and window tabs to be fixed width?

### ISSUE THREAD

**Issue by bdantas** [LBCrion/sfwbar#120]
Hello again, LBCrion. I have sfwbar across the top, using lightly tweaked version of `t2.config`. I like how the taskbar stays a constant width, so that the status icons (wifi, battery, volume, etc) are always in the same place.
 
However, I've noticed that the width of the individual windows' tabs varies according to number of windows. If only one window exists, its tab is as wide as the entire taskbar. If two windows exist, each tab is half the entire taskbar. Etc.
 
Is there a way for the taskbar to have a constant width and individual windows' tabs to also have a constant width, similar to the way most web browsers (e.g., firefox and chromium-based browsers) handle tab width? In this situation, if only a single window exists, there would be unused space between its tab and the status icons.

**Comment by LBCrion** [comment]
Taskbar is a homogeneous grid, so all items in it have the same width. In practice, this usually means that they will fill up all available space, since one of them items is inevitably a browser with a very long title. If you want taskbar items to take less space, you will need to limit the max length of window titles. You can do it using ``title_width`` property in the taskbar widget. I.e. ``title_width = 10``, will only display 10 characters of any window title (the titles will be ellipsized).

**Comment by bdantas** [comment]
> In practice, this usually means that they will fill up all available space, since one of them items is inevitably a browser with a very long title.
 
This makes sense but it doesn't explain what I'm seeing (or I'm not understanding correctly). After a reboot and before opening any windows, I open only a terminal. There are only 4 characters in the window title yet the item fills up all available space: [screenshot](https://gnuser.ddns.net/public/screenshot001.jpg). What am I missing?

**Comment by LBCrion** [comment]
This would indicate that taskbar items are set to expand.  Do you by any
chance have -GtkWidget-hexpand set to true for CSS nodes taskbar_normal or
taskbar_active?

**Comment by bdantas** [comment]
Aha! I did. So I changed the relevant section to this:
```
  taskbar {
    rows = 1
    css = "* { -GtkWidget-hexpand: false; }" # stretch horizontally
    icons = true
    labels = true
    action[3] = Menu "winops"
    action[2] = Close
    title_width = 10
  }
```
 
Problem now is that the entire taskbar is no longer fixed width, causing the status icons to slide around depending on how many windows are open: [screenshot](https://gnuser.ddns.net/public/screenshot002.jpg). Is there a way for the window tabs to be a fixed width like this, and also for the entire taskbar to stay the same width so that the status icons don't slide around?

**Comment by bdantas** [comment]
Oh, and I just realized if I have only one window open titled _foot_, the window's tab is very narrow. Maybe what I'm looking for is not implemented, which is fine but would be nice to know so that I don't chase my tail.
 
I guess the solution I'm looking for would entail settings like this (in pseudocode):
```
minimum_title_width = 10
maximum_title_width = 10
taskbar_fixed_length = true
```

**Comment by bdantas** [comment]
A picture is worth a thousand words. Here is another of my machines, running X and fluxbox. Is this taskbar behavior possible to achieve with sfwbar? Notice the fixed width of the window tabs and the fixed location of the status icons in the top right: [fluxbox1](https://gnuser.ddns.net/public/fluxbox1.jpg) [fluxbox2](https://gnuser.ddns.net/public/fluxbox2.jpg)

**Comment by LBCrion** [comment]
Since the taskbar is now limited in width,  you need something to take up the extra space.  Add the following widget to your config, right after the taskbar:

```
label {
    css = "* { -GtkWidget-hexpand: true; }"
  }
```
This will add an empty label that week expand to take up the free space.

**Comment by bdantas** [comment]
That's really clever. Thank you.

**Comment by LBCrion** [comment]
Btw, I see a couple of "sfw" icons in your screenshot. This means the icons is missing. One looks to be an icon for the foot terminal (this is usually installed in /usr/share/icons/hicolor/scalable/apps/), the other is a module just before clock - do you know which module that is?

**Comment by bdantas** [comment]
Wow, good eye. That's my custom "miscellaneous" widget that several of my shell scripts use to briefly show an icon using RT signals. I have other, more specific, custom widgets that are hidden when inactive, but I like seeing the misc_widget's placeholder when it's not in use. So the `sfw` icon you are seeing is there by design. It's what shows up when a button has no value. I think it looks cool.

**Comment by bdantas** [comment]
For foot terminal I will hunt down the missing icon. Thanks for the heads up.

**Comment by bdantas** [comment]
The last loose end for me is figuring out a way for windows with very short titles (e.g., "foot") to reach `title_width` (which in my case is set to 10). Can you think of a hack that would pad short window titles (e.g., by appending spaces to window titles before trimming them down to title_width)? If not, please add a `minimum_title_width` setting to user wishlist :)

**Comment by bdantas** [comment]
I played around with sfwbar settings some more. It seems that window tabs are kept same width, but only reach`title_width` (which is 10 in my case) if at least one window has title width 10 or more. In other words, if all window titles are short (say, 3-5 characters), then the widest window tab will be 5 characters wide. 
 
Can you add `minimum_title_width` setting to user wishlist? Idea is that `title_width = 10` would work as it currently does (preventing window tabs from going over 10 characters). New setting `minimum_title_width = 10` would ensure window tabs have that width even if all windows have a title that's shorter than that.

**Comment by LBCrion** [comment]
You can use min-width css property on css nodes with taskbar_normal and
taskbar_active names to specify minimum width.  There is an inconsistency
on units,  since min width is specified in pixels and max width in
characters,  but unless you use a monospace font,  max width will not be
pixel constant anyway.

**Comment by bdantas** [comment]
Wow, yes. That was the missing piece!
 
For other users'  reference, here are the relevant parts of ~/.config/sfwbar/sfwbar.config that were needed to achieve the look I desired:
 ```
 taskbar {
    css = "* { -GtkWidget-hexpand: false; }" # stretch horizontally
    title_width = 15
  }
  label {
    css = "* { -GtkWidget-hexpand: true; }"
  }
---snip---
#taskbar_normal,                   
#taskbar_active {                                                               
  min-width: 148px;                                                
}     
```
That was tough! Thank you, LBCrion. I would not have been able to figure this out without your help.

**Comment by bdantas** [comment]
> Related:
> 
> * [Width for taskbar items #54](https://github.com/LBCrion/sfwbar/issues/54)
> 
> I'd suggest uploading screenshots to the issues themselves rather than linking them, that prevents them being gone when the host you use to upload is offline at some point + they show up directly in the issue.
 
@Consolatis - You are absolutely right, that would be a much better approach. I will do it that way going forward.

**Comment by LBCrion** [comment]
> That was tough! Thank you, LBCrion. I would not have been able to figure this out without your help.

I think that's the biggest problem I have with sfwbar right now. Configuration is not simple. The problem is, I can't figure out a way to simplify the config while preserving the flexibility.

**Comment by Consolatis** [comment]
> The problem is, I can't figure out a way to simplify the config while preserving the flexibility.

Yeah, that's a tough one.
Other than having examples for every possible use-case in the man page / some other kind of documentation or creating some really fancy GUI editor (which would likely be way overkill) I don't really see a way to make configuration easier. The flexibility of sfwbar is what makes it so awesome in my opinion so doing anything that reduces the flexibility might backfire.

I'll keep recommending sfwbar with the restriction of "if you are fine spending some time to set up your config or a satisfied with one of the example ones" :)

Maybe what could be done is to ship more "look-alike" example configs and then pointing new users to them?

**Comment by bdantas** [comment]
> I think that's the biggest problem I have with sfwbar right now. Configuration is not simple. The problem is, I can't figure out a way to simplify the config while preserving the flexibility.
 
I think the sfwbar documentation is excellent, as are the example config files. For it to be as flexible as it is, sfwbar will necessarily be somewhat complex. I don't think this is a weakness.

One observation is that the documentation discusses individual low-level settings, while the example config files provide a finished end result and are therefore extremely high-level. Perhaps it would be helpful to show how to combine low-level settings to achieve a handful of _mid-level_ goals (e.g., how to achieve taskbar items of fixed width) somewhere in the documentation?
