### ISSUE TITLE
Battery charge display not working in FreeBSD

### ISSUE THREAD

**Issue by elgithubo** [LBCrion/sfwbar#124]
I am working on a laptop (XMG Ultra E21).

The battery icon looks like this (lightening icon):
![20231118_15h19m52s_grim](https://github.com/LBCrion/sfwbar/assets/15913459/6a0aa859-d12f-49fe-857d-e246d0157e2e)

The tooltip just says "nan%".

No errors are sent to console.

**Comment by LBCrion** [comment]
Can you try changing ``BSDCtl("hw.acpi.battery.level.life")`` to ``BSDCtl("hw.acpi.battery.life")`` in the first line of battery-svg.widget 

And thank you for flagging all of these! I don't have FreeBSD running on bare metal, and can't test these widgets in a VM.

**Comment by elgithubo** [comment]
That fixed the battery icon, but not the tooltip.

Thank you for that very nice piece of software!

**Comment by LBCrion** [comment]
Cool, for tooltip, can you try changing line 57, from:
``tooltip = Str(100*XBatteryLeft/XBatteryTotal) + "%"``
to:
``tooltip = Str(XBatteryLevel) + "%"``

**Comment by elgithubo** [comment]
Amazing, now the tooltip works, too.
Thank you!

**Comment by LBCrion** [comment]
Just curious, does it show time remaining on your system?

**Comment by elgithubo** [comment]
no it doesn't.
it just says "75%", nothing else.
unfortunately my screenshot tool (grim) is obviously not capable of screenshotting tooltips, so I have to describe it...

**Comment by elgithubo** [comment]
```
elgrande@elfreebsdo1:~ % sysctl hw.acpi.battery
hw.acpi.battery.info_expire: 5
hw.acpi.battery.units: 1
hw.acpi.battery.state: 0
hw.acpi.battery.rate: 0
hw.acpi.battery.time: -1
hw.acpi.battery.life: 76
elgrande@elfreebsdo1:~ %
```

**Comment by LBCrion** [comment]
Ok,  .time=-1 which means the battery doesn't expose information necessary
to compute the remaining time. I have the same on my laptop.

**Comment by elgithubo** [comment]
I think this is solved with beta14 at latest.
At least I have a tooltip now.
So I am closing the issue.
Please reopen in case it is required.
