### ISSUE TITLE
how to force tooltip to update?

### ISSUE THREAD

**Issue by bdantas** [LBCrion/sfwbar#126]
One of my custom widgets keeps me informed about print job's progress. Tooltip changes from "job sent to printer", to "printer processing job", etc.

Currently, I have to keep wiggling the mouse over the custom widget's icon in order for the tooltip to update. Is there a way to force the tooltip to redraw itself while the mouse is hovering motionless over the widget's icon?

**Comment by bdantas** [comment]
I figured it out after much trial and error. Sorry for the noise.

This is `~/.config/sfwbar/misc.widget`:
```
scanner {
  exec("sh -c 'cat /tmp/misc-widget-icon'") {
    desired_icon = RegEx("(.*)")
  }
  exec("sh -c 'cat /tmp/misc-widget-tooltip'") {
    desired_tooltip = RegEx("(.*)")
  }
}

layout {
  button "misc_button" {
    value = $desired_icon
    style = "launcher"
    tooltip = $desired_tooltip
  }
}
```
This goes in `~/.config/sfwbar/sfwbar.config`:
```
TriggerAction "SIGRTMIN+10", Function "update_misc_widget"
function("update_misc_widget") {
  SetValue "misc_button", $desired_icon
  SetTooltip "misc_button", $desired_tooltip
}
...
  include("misc.widget")
```

**Comment by LBCrion** [comment]
Nice! I think the scanner may be optimised a bit to:

scanner {
  File("/tmp/misc-widget-icon") {
    desired_icon = Grab()
  }
  File("/tmp/misc-widget-tooltip") {
    desired_tooltip = Grab()
  }
}


Using file instead of exec avoids spawning a new shell process with
all the associated overhead when all we need is the contents of a
file.

RegEx("(.*)") can be replaced with Grab(), since all we need is the
entire contents of the file. This avoids a call to the regular
expression engine and just copies a string.

**Comment by bdantas** [comment]
Thank you for those nice optimizations! I have updated the widget accordingly.
 
The only tweak I had to make for the optimizations to work was to eliminate trailing new lines from `/tmp/misc-widget-icon` and `/tmp/misc-widget-tooltip`. In other words, shell scripts that use the `misc` widget now need to use `echo -n` rather than `echo` when writing to the `/tmp/misc-widget-*` files, like this:/
```
echo -n /usr/local/share/icons/some-nice-icon.png >/tmp/misc-widget-icon
echo -n "howdy" >/tmp/misc-widget-tooltip
pkill -RTMIN+10 -x sfwbar
```
This widget just keeps getting better and better!

**Comment by bdantas** [comment]
P.S. It seems I was just lucky that the same RT signal first triggers the scanner, then the SetTooltip action. Presumably things could happen the other way around.
 
Maybe it would be better/safer for scripts to send one signal to activate the scanner (e.g., RTMIN+10) followed by a different signal (say, RTMIN+11) to activate the SetTooltip action?

**Comment by bdantas** [comment]
I did some experiments and discovered that using a single signal is fine. The SetTooltip action seems to include re-evaluating `desired_tooltip`, so it doesn't matter if the scanner activation happens before or after the SetTooltip action.

**Comment by bdantas** [comment]
I think I found another optimization. I discovered that the `SetTooltip` action includes running the file scanner, so there is no need to trigger th file scanner separately. Therefore, this version of `misc.widget` works just as well:

```
TriggerAction "SIGRTMIN+10", Function "update_misc_widget"
function("update_misc_widget") {
  SetTooltip "misc_button", $desired_tooltip
  SetValue "misc_button", $desired_icon
}

scanner {
  File("/tmp/misc-widget-icon") {
    desired_icon = Grab()
  }
  File("/tmp/misc-widget-tooltip") {
    desired_tooltip = Grab()
  }
}

layout {
  button "misc_button" {
    value = $desired_icon
    style = "launcher"
    tooltip = $desired_tooltip
    trigger = "SIGRTMIN+99" # a signal I don't use
  }
}
```
The no-op trigger in the button definition is a bit ugly but I can live with it. If I remove the `trigger` line completely, it seems to default to `interval` (set to something short--500 ms? 1000 ms?).
 
I think this is as good as I can make it.

**Comment by LBCrion** [comment]
You can use ``interval = 0`` to stop widget from being updated in the scanner thread and rely entirely on TriggerAction for updates. Do keep in mind that this was introduced fairly recently and in old versions of sfwbar this setting will cause constant updates!

If you just need to grab the first line from a file (i.e. your file was generated with ``echo`` rather than ``echo -n``) you can use Grab(First).

**Comment by bdantas** [comment]
Thank you so much for all your help. I will incorporate both suggestions. Now we've crossed the line from making this simply work to making it beautiful. I really appreciate all your help.

**Comment by bdantas** [comment]
Just an FYI - `Grab(First)` does not seem to be working as expected. If file is generated with `echo` rather than `echo -n`, `Grab(First)` does grab the newline. This causes the icon to not show up and I can see from the tooltip that the newline was grabbed.
 
This is not a big deal because `Grab()` with `echo -n` is working. I just wanted you to know that sfwbar is not behaving as expected in this instance.

**Comment by LBCrion** [comment]
This is my bad. Grab(First) works for numeric variables, but not strings. I
should probably implement this. Other aggregators (such as sum or product)
don't make sense for strings, but First does.

**Comment by LBCrion** [comment]
Actually, I stand corrected again. I did implement Grab(First) for strings and it works as expected in my tests. Would you mind posting the config where you tried using it and it didn't work?

**Comment by bdantas** [comment]
Sure. Here is `~/.config/sfwbar/misc.widget`:
```
TriggerAction "SIGRTMIN+10", Function "update_misc_widget"
function("update_misc_widget") {
  SetTooltip "misc_button", $desired_tooltip
  SetValue "misc_button", $desired_icon
}

scanner {
  File("/tmp/misc-widget-icon") {
    desired_icon = Grab(First)
  }
  File("/tmp/misc-widget-tooltip") {
    desired_tooltip = Grab(First)
  }
}

layout {
  button "misc_button" {
    value = $desired_icon
    style = "launcher"
    tooltip = $desired_tooltip
    interval = 0
  }
}
```
Here are some shell commands:
```
$ echo "/opt/scripts/media/ok.png" >/tmp/misc-widget-icon
$ echo "hello world" >/tmp/misc-widget-tooltip
$ busyboxFull pkill -RTMIN+10 -x sfwbar
```
Here is the result:
![screenshot003](https://github.com/LBCrion/sfwbar/assets/5084088/34f61ab4-631d-4d9d-9ee9-9248373964d9)
As you can see, there is a trailing new line in the tooltip and the icon does not change as expected.
 
I believe the problem is that `Grab()` and `Grab(First)` include the final newline (in file and first line, respectively) in the grab. This is a problem because I do not have a png called `/opt/scripts/media/ok.png\n`--the file name is `/opt/scripts/media/ok.png`.
 
I think the solution is for either `Grab()` and `Grab(First)` -or- `SetTooltip` and `SetValue` to ignore the very last newline in the string.

**Comment by LBCrion** [comment]
Ok, it should work now. Grab(first) correctly grabbed the first line, but unlike regex("(.*)") it kept the trailing newline, which doesn't work well in case of filenames of course. I added code to strip the trailing newline now.

**Comment by bdantas** [comment]
Yes, I can confirm that both `Grab()` and `Grab(First)` now strip the trailing newline, which allows grabbing filenames to work as expected. Very nice! Thank you!
