### ISSUE TITLE
Error when I started sfwbar

### ISSUE THREAD

**Issue by bluebyt** [LBCrion/sfwbar#128]
sfwbar doesn't stated.

sfwbar &                  
sfwbar: error while loading shared libraries: libsfwbar.so: cannot open shared object file: No such file or directory

Here the log file of the installation.
https://rentry.co/95zgu/

**Comment by LBCrion** [comment]
It looks like the shared library is installed into /usr/local/lib by
default and this directory isn't in your default library path. You can
change the prefix when configuring meson, i.e.:
meson setup build --prefix=/usr
ninja -C build
sudo ninja -C build install

or you can launch sfwbar with: LD_LIBRARY_PATH=/usr/local/lib sfwbar

**Comment by bluebyt** [comment]
Ok I launch sfwbar with: LD_LIBRARY_PATH=/usr/local/lib sfwbar

Thanks for the quick response!

**Comment by Consolatis** [comment]
An alternative solutions is to add `/usr/local/lib` to your library path: https://github.com/wmww/gtk4-layer-shell/issues/21#issuecomment-1565971521

**Comment by LTH1097699** [comment]
Or you can symlink to /usr/lib
` sudo ln -s /usr/local/lib/libsfwbar.so /usr/lib`

**Comment by bluebyt** [comment]
Ok thanks for your help!

**Comment by LBCrion** [comment]
I think this issue is resolved (with multiple solutions!), so I will close it. Of course please do reopen it if you still have any problems with this.
