### ISSUE TITLE
Is it possible to override the default icon for individual apps?

### ISSUE THREAD

**Issue by winteriscariot** [LBCrion/sfwbar#129]
I have some custom applications that I made (using nativefier) and even though an icon gets embedded in the application when created, these applications show up using the default 'sfw' icon

Is there a way that I can override this, perhaps by creating a png or svg somewhere with the app_id of the application in question? I tried putting an icon named "spotify-nativefier-27c197.svg" in /usr/share/icons/hicolor/scalable/apps, but that hasn't done anything. (and yes I know that the official spotify app sets the icon correctly, i'm simply using this to test)

Thanks!

**Comment by Consolatis** [comment]
>  perhaps by creating a png or svg somewhere with the app_id of the application in question?

Yes, see https://github.com/LBCrion/sfwbar/blob/main/doc/sfwbar.rst#miscellaneous for a list of icon paths and a way to see the app_id.

**Comment by winteriscariot** [comment]
thank you!
