### ISSUE TITLE
1.0_beta14 not responding to RTMIN signals

### ISSUE THREAD

**Issue by bdantas** [LBCrion/sfwbar#134]
FYI - I've been using git-22f089d (from 24Nov2023), which works perfectly for all my use cases. I compiled 1.0_beta14 to test it and everything seems to work except that sfwbar does not respond to RTMIN signals (e.g., to change widgets' button icon). I haven't done a git bisect so cannot pinpoint which commit is responsible for the regression.

**Comment by LBCrion** [comment]
Looks like one of the changes made triggers case sensitive (and lower case). This should be fixed in the latest git. Can you check if it works for you please?

**Comment by bdantas** [comment]
Fixed in latest git, thank you. Everything is lower case in my triggers except for signal name. For example:
```
TriggerAction "SIGRTMIN+7", SetStyle "eject_button", "hidden"
TriggerAction "SIGRTMIN+8", SetStyle "eject_button", "launcher"
```
I think most users would assume signal name should be upper case.
