### ISSUE TITLE
alsactl.so loaded from original build dir, not /usr/local/lib

### ISSUE THREAD

**Issue by jonleivent** [LBCrion/sfwbar#135]
I have the sfwbar libs, such as alsactl.so, installed in `/usr/local/lib/x86_64-linux-gnu/sfwbar`, but I noticed that sfwbar is instead loading alsactl.so directly from the git dir where I built it.  Do you know why that could be happening?  Do you grab the full pathname for it and prefer that over the lib path?

**Comment by LBCrion** [comment]
Are you running sfwbar from the original build dir? Sfwbar will check for
modules in . and will use them if found.

**Comment by jonleivent** [comment]
It's running sfwbar from `/usr/local/bin`.  I can see that via the `/proc/PID/exe` symlink.

**Comment by jonleivent** [comment]
Could this be due to how I did the install?  I set my install prefix to a subdir of the git dir, and (as root) copy out the files installed there to `/usr/local` locations instead of doing the usual `sudo meson install ...` with no prefix (or the prefix set to the final install spot).  Does sfwbar pick up the prefix setting from the meson config, and use it to find libs?

**Comment by LBCrion** [comment]
Yes it does.  If you ran 'meson setup' with a prefix set to your build
directory,  that would drive the location where modules are picked up by
from. You can check this in your build directory in a file meson.h

**Comment by jonleivent** [comment]
That's it: `MODULE_DIR`.   Can I set prefix to one thing, then set `MODULE_DIR` to something else, or unset it?

**Comment by LBCrion** [comment]
You can run meson setup, then use sed (or any other method) to change
meson.h and then run ninja -C build etc.

**Comment by jonleivent** [comment]
Would it work if I left `MODULE_DIR` undefined?  Or defined it to be empty?  Because I don't want any hard-wired module dir - I want it to always be relative to the lib path.

**Comment by LBCrion** [comment]
Sfwbar doesn't know your lib path,  that's why it needs MODULE_DIR. If you
want modules to be relative to your lib path,  you should just set
MODILE_DIR accordingly.

**Comment by jonleivent** [comment]
OK.  I see that it uses MODULE_DIR last in get_xdg_config_file.  If I set the XDG_DATA_DIRS appropriately, that should work.

I'm looking for a workaround that won't get undone the next time I rebuild from scratch (by rm -rf'ing my git build).  So XDG_DATA_DIRS is better than editing meson.h, which I will probably forget to do next time.  I have a launch script for sfwbar where I can set XDG_DATA_DIRS.  I'll try that.

I'm not trying to be difficult.  It's just that I'm a bit anal about doing anything like `sudo make install` on my system.  The user account I use for building doesn't even have sudo privs.

**Comment by jonleivent** [comment]
I tried using XDG_DATA_DIRS, but could not get it to work, and thinking more about it, isn't a good answer for me anyway.

I know sfwbar treats these .so's as "modules", but they are libraries: executable code.  They're not app data or settings.  So I need to put them where they are as safe as other libraries, hence not in user dirs, and arrange things so they cannot be overridden by things in user dirs.  That means using `get_xdg_config_file` to find them is, for me, always going to be a security hole.  I have other security mitigations in place (which is how I caught this issue in the first place), but working around them for this isn't a good practice.

I will think about patching `module_load` so that it uses the library path instead of or before calling `get_xdg_config_file`...

**Comment by LBCrion** [comment]
I think the security angle is indeed an important consideration for modules. What do you think is the right approach here. Shall we only attempt to load modules from a module dir?

**Comment by LBCrion** [comment]
On this topic, what are your thought on security of config files? Config files can execute shell commands. In theory dropping a malicious config into CWD can be an attack vector.

**Comment by jonleivent** [comment]
For executable code, especially binaries (so not easily inspected), I think arrangements should be made so that a security minded admin can make sure it isn't user writable or easily overridden.

The bigger problem is non-binaries - config files that execute shell commands, as you pointed out.  

The linux `~/.config` is hard to secure.  Ideally, you'd like to make it unwritable by apps.  For some desktops, that's just not possible because they write stuff into it at runtime.  I stay away from those desktops (KDE, GNOME, for instance) for this reason.

But, even if you make `~/.config` unwritable, it's still under `~`, which is writable, so it can be moved aside and replaced as an attack vector.  A better option is to offer a config dir command line option, which can be set to a path that is entirely unwritable by users.  But it should be the case that there are no search options that override once there is a config dir command line option.

And don't use CWD in any built-in way.  If the user really wants to load from CWD, they should specify `./something` as their config dir or config file.  My preference would be to not hard-wire in any dir paths (and `.` is one of them), such as you're doing with MODULE_DIR and `get_xdg_config_file`.  Those become a security issue or a build vs. deploy issue, or both (as in my case).

If you do make a secure config dir an option, then that could be used for libs as well.  However, that becomes a bit of a maintenance issue as then one has to worry about those libs when installing new versions of things.  Usually, the stuff stored in a config dir won't need to be revised when a new version of execs and libs drops (or is built and installed).  The best practice with libs is probably to follow the platform's specific lib dirs.  There are many security-minded components in linux that treat those lib dirs specially.  For instance, there's that special feature that disables LD_LIBRARY_PATH and LD_PRELOAD when the exec is suid or sgid, so that libs only come from trusted dirs.  Also, AppArmor profiles typically allow mapping operations only on files under `/lib, /usr/lib, /usr/local/lib`, and AppArmor also has a "environment scrubbing" feature that checks LD_LIBRARY_PATH and LD_PRELOAD.  And SELinux does things like that as well.

If you want to maintain backward compatibility with what you already have sfwbar doing, I'd suggest adding a security command line switch that disables the use of CWD and MODULE_DIR, and loads the libs from somewhere safe.

**Comment by LBCrion** [comment]
For modules, I think we should have one path where the modules should be located. Modules are code, they are shared objects, but they are not libraries. They are not loaded by a dynamic linker, but rather through dl_open. As such I don't think they should go directly into the library directory. This is why we default to a subdirectory within a standard library directory.

Why do you think use MODULE_DIR is a bad idea? MODULE_DIR is not an environment variable, it's a C macro only used in the compilation process. I.e. we're hardcoding the module directory name in the sfwbar executable. Usually, the executable is built with a prefix set to the system standard prefix (/usr or /usr/local) and if you want to install to a different location, you use DESTDIR when running the install command to specify this. With this process, the modules go into /usr/lib[64]/sfwbar/ or /usr/local/lib[64]/sfwbar/.

I think limiting the module path just to this directory makes the most sense.

For configs, the path normally includes (in this order):
- CWD
-  directory for the config file (if specified in the command line)
- XDG user config dir (usually ~/.config/sfwbar)
- System XDG config dirs (usually /usr/share/sfwbar or /usr/local/share/sfwbar)

From this list, I think:
1. CWD is unsafe and should be removed.
2. The directory with a config specified in the command line is needed I think, if a user points to a specific config location, I would expect they want any configs loaded through "include" to be from the same location.
3. XDG user config is the default for (2), currently we probe both, but perhaps for security it would be better not to probe (3) if (2) is specified
4. This is the system location for configs. It is normally not user writable. Given the complexity of configs, I think it makes sense to have a location for the default configs (i.e. in most cases users will modify sfwbar.config and use default widgets, but if they want to modify a specific widget, they will copy this widget to their config dir (2) or (3) and make modifications there).

**Comment by jonleivent** [comment]
If you give dlopen a filename with no slashes, it uses the dynamic linker.  Hence, LD_LIBRARY_PATH and `/lib:/usr/lib`, among other things.  Anyway, I'm just saying this because using dlopen is not itself the differentiator between libs that go into standard dirs vs. not.

I completely understand not wanting the sfwbar libs at top-level in any of the standard lib dirs.  They are specific to sfwbar, and should go somewhere under a sfwbar subdir.  You could use dynamic string tokens and/or DT_RUNPATH for this (see the ld.so man page), which gives you more flexibility than MODULE_DIR does.

I didn't know about DESTDIR!  I will reconfigure not to use prefix and use DESTDIR instead.

For configs (not modules):
I agree about dropping CWD.
I agree that a directory specified on the command line should be first on the search path.  The rest can be the standard XDG places in their standard order.

**Comment by LBCrion** [comment]
I update the current git version to only load modules from MODULE_DIR and to exclude CWD from config path. Let me know if you have any other ideas of making this process more secure.

**Comment by jonleivent** [comment]
Thanks!  Haven't tried it yet, as I'm chasing down a bug in something else.  BTW - thanks again for that DESTDIR fact - one of those "how did I not know this until now?" things, of which there are embarrassingly many.

**Comment by LBCrion** [comment]
Just a heads-up, Per #151, I added `prefix/datadir` to the config search path to ensure the default configs load when sfwbar is installed with custom prefix. This is effectively added to the list of XDG_DATA_DIR's.
