### ISSUE TITLE
Overflowing widget onto surrounding widgets?

### ISSUE THREAD

**Issue by godares79** [LBCrion/sfwbar#138]
I have my launchers set up such that they grow slightly on hover:

```
button#launcher {
  min-width: 40px;
  min-height: 40px;
  padding: 0px;
}

button#launcher:hover {
  /* Specifically setup transition animation for hover */
  transition-duration: 0.1s;
  transition-timing-function: linear;
  min-width: 50px;
  min-height: 50px;
  padding: 0px;
}
```

However, expanding the width causes other elements in the bar to shift by the same amount the icon grows. This is the case both with no theme and when using other themes (ArchLabs-Dark in my case). I started with the t2.config, so lots of the CSS is still the same.

Ideally what I'd like to do is have the launcher icon just overflow on top of the launchers next to it. Do you know if that's doable? (I found the CSS overflow property, but it looks like that is GTK4 only).

(Compositor = Labwc)

Ty for creating this bar, I'm loving how flexible it is.

**Comment by LBCrion** [comment]
I don't think this can be implemented with gtk3. gtk3 widget rendering assumes non-overlapping widgets, with exception of an overlay widget. The only way I can see implementing this would be using overlay as a container for all widgets, but if we do this, we'll need to re-implement the entire widget size allocation process. 

This would probably need to wait for migration to gtk4, but that poses it's own problem - gtk4 gets rid of custom CSS properties, so we need to find another way to implement a lot of styling options.

**Comment by godares79** [comment]
No worries then, I can easily live without this. Will mark as closed.
