### ISSUE TITLE
 SetBarSensor not working.

### ISSUE THREAD

**Issue by pablo-888** [LBCrion/sfwbar#139]
If I enable it with the default config the bar segfaults immediately. The only thing I get is this: 
```
i3-ipc*input type:keyboard xkb_switch_layout nexti3-ipc*input type:keyboard xkb_switch_layout prev
(sfwbar:28290): GLib-CRITICAL **: 20:44:47.409: g_hash_table_remove_all: assertion 'hash_table != NULL' failed
```

but that message appears even when I disable autohide and the bar is working fine otherwise so I don't know if it's related at all. If I enable SetBarSensor with my own config (which is rather minimal it's basically just a small clock) it launches and I can see the 1px line like it's hidden correctly but when I hover over it the bar doesn't show up and I get these messages:
```

(sfwbar:32088): Gtk-CRITICAL **: 20:50:38.559: gtk_container_add: assertion 'GTK_IS_WIDGET (widget)' failed

(sfwbar:32088): Gtk-CRITICAL **: 20:50:38.920: gtk_container_remove: assertion 'GTK_IS_WIDGET (widget)' failed
```

the first one appears when the cursor is over the bar area and the second one appears when the cursor leaves.

(here's my own config just in case it happens to be useful 
[sfwbar.txt](https://github.com/LBCrion/sfwbar/files/13996096/sfwbar.txt)
)

**Comment by LBCrion** [comment]
It looks like you ran into two bugs for the price of one. Both should be fixed in the latest git. Can you please try to see if it works for you now?
