### ISSUE TITLE
Workspaces are not sorted as numbers

### ISSUE THREAD

**Issue by milochadam** [LBCrion/sfwbar#14]
![image](https://user-images.githubusercontent.com/27895477/148850870-40ba9b56-e2c2-4687-b01b-392c54c4930c.png)

**Comment by LBCrion** [comment]
I added a new option to control this in the main branch. pager widget now has a 'numeric' property. It's set to true by default, which sorts workspaces as numbers, if set to false, it will sort workspaces as strings.

**Comment by milochadam** [comment]
Thank you :)
