### ISSUE TITLE
Don't hardcode `python` path

### ISSUE THREAD

**Issue by b1rger** [LBCrion/sfwbar#146]
In Debian, Python 3 is in `/usr/bin/python3` - I'm patching the path currently when creating the swfbar package, but it would be great if that was a compile time option. On the other hand #123 sounds like implementing the widgets using Python might be dropped, so if thats the plan, consider this issue void

**Comment by b1rger** [comment]
Well, I guess what you actually want is the using any executable in the widget, not limited to python? As long as the widget knows how to handle the output, the script can be python, perl, shell or even a compiled binary. So maybe in the widget it would be enough to point to an executable...

That doesn't solve the problem with `python` vs `python3` though, because even if you move the python code to a separate script, it will have to point to a python interpreter. I think the recommended behavior [is to use python3](https://peps.python.org/pep-0394/) and IIRC fedora also [follows this recommendation](https://fedoraproject.org/wiki/Changes/Move_usr_bin_python_into_separate_package) but maybe other package maintainers can comment on that

(In scripts, there is usually a [shebang](https://en.wikipedia.org/wiki/Shebang_(Unix)) in the first line which says which interpreter should be used to run the script, so for a python3 script it would be `#!/usr/bin/python3`. And because `python3` could be installed in other locations, nowadays for [portability its recommended](https://en.wikipedia.org/wiki/Shebang_(Unix)#Program_location) to use `#!/usr/bin/env python3`)

**Comment by LBCrion** [comment]
Looking into it, python3 executable is supported by pretty much all distributions. I updated the configs to use `/usr/bin/env pthon3`.

**Comment by LBCrion** [comment]
This bug, along with #145 and #147 should be fixed in 1.0beta15. Do you think these are ok to close now?

**Comment by b1rger** [comment]
> This bug, along with #145 and #147 should be fixed in 1.0beta15. Do you think these are ok to close now?

Sure. I still think that separate script files, instead of embedding the Python code, would be nicer (that would make it possilbe to replace without having recompile, one could write Python scripts with Python syntax highlighting, the scripts could be tested easier), but the issue at hand has been solved with using `/usr/bin/env`!
