### ISSUE TITLE
Panel can no longer be set to float

### ISSUE THREAD

**Issue by pocco81** [LBCrion/sfwbar#149]
Hello! the trick mentioned on #93 to separate the panel from the edge of the screen does not work (at least as of the latest git).

Setting the following in the default `sfwbar.config` (for example), has no effect:

```
window#showbar{
    background: rgba(0,0,0,0);
}
window#showbar box{
    margin: 10px;
}
```

**Comment by LBCrion** [comment]
Just to check, does your bar have name "showbar"? That's what the example in #93 assumes (i.e. it's created with `layout "showbar" {`). The default name for a bar is `sfwbar`. So you can either explicitly name your bar and use that name in the CSS or leave it as default and use `#sfwbar`, i.e. `window#sfwbar`.

**Comment by pocco81** [comment]
Ok so that "worked", however, I would like to _not_ make my bar transparent. In that case, without adding the first `window#sfwbar {}` snippet, the bar just looks as thick as the margin specifies. How can I make it "keep" its color while keeping the bar floating at the same time?

**Comment by LBCrion** [comment]
try this:
```
window#sfwbar {
  background:  rgba(0,0,0,0);
}

window#sfwbar box {
  margin: 10px;
  background: @theme_bg_color;
}
```
This will set the bar window background to be transparent and the main box background to your theme background color. (You can replace `@theme_bg_color` with another color if you prefer of course.

**Comment by pocco81** [comment]
I mean, it's adding 10px to both the top and the bottom of the bar's _box_, but if I make the box transparent, it makes the whole bar transparent.

What I'm trying to achieve is: put 10px below the bar, without making the whole bar transparent.

**Comment by LBCrion** [comment]
The layout in this case goes as following. You have a window with a transparent background. The window contains a box, which has a theme default background and a margin of 10px on all sides. (If you prefer to specify the margin only for some sides, you can do it, i.e. `margin-bottom: 10px;`). The background applies to contents on the box, including it's padding, but excluding margin. So the 10px margin stay transparent. Here's how this looks on my machine:

![20240222_19h29m10s_grim](https://github.com/LBCrion/sfwbar/assets/76477076/8a09358e-8d67-4539-855e-8c35c9b31502)

**Comment by pocco81** [comment]
Do you mind sharing your config?

**Comment by LBCrion** [comment]
Sure. It's pretty much the default config with the above changes.
[config.txt](https://github.com/LBCrion/sfwbar/files/14382778/config.txt)

**Comment by pocco81** [comment]
ok, I got it to work now. Defining it at the top of the `#CSS` section (like you) did the trick.

In the process I think I found a bug: setting the panel to autohide after any amount of time and setting the `margin` (specifically `margin-bottom` of `window#sfwbar box`) anything greater than 0, causes the panel to hide after entering triggering the panel to show (i.e. moving your cursor so the side of the screen where the bar is) and moving it to the panel's actual box.

Like, you can't click anything because it hides as soon as you enter the panel's box.

**Comment by LBCrion** [comment]
I'll need to have a look at this.  I haven't tested this use case before,
so some code tweaking may indeed be needed.

**Comment by LBCrion** [comment]
This should be fixed in the latest git version.

**Comment by pocco81** [comment]
Yep, it's working now.
