### ISSUE TITLE
The bar is always on top even if an application is in full-screen mode

### ISSUE THREAD

**Issue by milochadam** [LBCrion/sfwbar#15]
Below is an example with a YouTube video:
![image](https://user-images.githubusercontent.com/27895477/149021915-b7621a53-b0e6-4497-a5fa-40ecff65b264.png)
Similar thing happens with a game in "full screen windowed" mode.

Is it possible for the bar to be at the bottom, similarly to the sway's default bar? A small reason for wanting that behaviour is consistency between bars, it would solve the issue and it should also work for screenshotting a region -- right now the bar steals focus of `grim` utility.
Another solution that would work is to be able to toggle auto-hide bar - usually it's irritating but for the few cases it's fine.

**Comment by LBCrion** [comment]
You can currently toggle the bar by either sending it a SIGUSR2 signal (i.e. killall -SIGUSR2 sfwbar) or by toggling bar mode in sway, i.e: bindsym $mod+c bar mode toggle.
I'll look into adding a config option to specify top/bottom layer for the bar.

**Comment by LBCrion** [comment]
You can now set default layer for the bar using the init function:

Function("SfwBarInit") {
SetLayer("bottom")
}

You can also set a default monitor using the same way using SetMonitor action, i.e. SetMonitor("eDP-1")

**Comment by milochadam** [comment]
How do I use it? If I copy-paste it at the top of my config I get:
```
11:01:50,91 /home/user/.config/sfwbar/sfwbar.config:2: invalid action
```

**Comment by LBCrion** [comment]
My bad, it should be:

Function("SfwBarInit") {
SetLayer "bottom"
}

**Comment by milochadam** [comment]
It works, thank you very much :)

**Comment by tstraus13** [comment]
Hello. Sorry to reply on a closed issue but I am having this same exact issue. I tried to apply the SetLayer "bottom" config but that doesnt seem to work. It still appears above a full screen window. I also tried to toggle it with the SIGUSR2 signal which does toggle it but when I toggle it back "on" it displays on the incorrect monitor. Is there something I am missing to get this to not be about full screen applications? Thanks.

**Comment by LBCrion** [comment]
@tstraus13 , what version of sfwbar are you using and what version of gtk-layer-shell do you have installed? I wonder if you're seeing the problem from #47.
The monitor jumping shouldn't happen on hide/show trigger though (unless the original monitor is disconnected in the meantime). Can you please let me know which compostior you're using and post your config and the output of ``sfwbar -m list`` ?

**Comment by tstraus13** [comment]
I am running 1.0_beta9 off a Fedora Copr repo (https://copr.fedorainfracloud.org/coprs/crion/sfwbar/) on top of the LabWC window manager/compositor (0.5.3). I am not sure I have gtk-layer-shell installed unless its a requirement for sfwbar, if it is then I will check when I get home later today. I am not disconnecting any monitors and will give you the output for `sfwbar -m list` when I get home. Thanks for your help.

**Comment by LBCrion** [comment]
Also to check,  when you say the bar appears above the full screen window,
does the window actually partially go under the bar or does it just
maximize on the part of the screen not occupied by the bar?
That later could be an effect of the layer shell exclusive zone and can be
addressed with SetExclusiveZone "-1"

**Comment by LBCrion** [comment]
Hi @tstraus13 , just wanted to check if you had a chance to check the above?

**Comment by tstraus13** [comment]
I apologize. I had to change desktop environment and was not able to test. You may consider my issue resolved. Thanks.
