### ISSUE TITLE
Per-app volume sliders

### ISSUE THREAD

**Issue by Ithvr** [LBCrion/sfwbar#150]
Hi,
I am wondering if it is possible to get per-app volume sliders in the PulseAudio module?
I have seen some standalone solution, but they start more like a desktop application rather then a volume mixer so I'm hoping it solvable inside of sfwbar.

**Comment by LBCrion** [comment]
It should be possible to add support for this. Fundamentally it's not too
different from the sink volume,  but will need some wiring up.

**Comment by Ithvr** [comment]
If it helps I saw that nwg-panel added this feature in their 0.9.18 release. 
Both of you are using gtk, but I don't know how much help that is for you.

**Comment by LBCrion** [comment]
Here's what I have so far. The controls work, including control of individual channels for clients.

![20240227_18h29m21s_grim](https://github.com/LBCrion/sfwbar/assets/76477076/90005ad6-43c6-4963-892b-4952829d7132)

**Comment by LBCrion** [comment]
I pushed the initial support for client volume controls into the main git
branch. Give it a try if you get a chance and see if this is what you're
looking for.

**Comment by Ithvr** [comment]
I'm impressed how quick you are.
Can't say I feel solid in my compiling knowledge to test an application. I guess I will see how well this works on the next release.

**Comment by pocco81** [comment]
I tested it, and it works great. The only thing that bugs me is that the volume widget (as well as the wifi one, for that matter) don't automatically close when I click off.

**Comment by LBCrion** [comment]
@pocco81, thank you for testing!

You have a couple of ways to set the pulse volume control window to close on a click outside of it:

1) You can copy pulse-module.widget to your config directory and add `AutoClose = true` setting to `PopUp "XVolumeWindow"` section.
2) You can override it from your config by adding `Config "PopUp 'XVolumeWindow' { AutoClose = true }"` to `Function("SfwbarInit")`

Alas, the config for the volume control will likely change as I'm planning to create a single volume control interface implemented by multiple modules (i.e. pulse, alsa and hopefully wireplumber in the future).

One question I have is: would it be useful to allow changing the sink for a given client (i.e. have a button next to a client volume control to allow selecting which sink the sound should go to?)

**Comment by Consolatis** [comment]
> One question I have is: would it be useful to allow changing the sink for a given client (i.e. have a button next to a client volume control to allow selecting which sink the sound should go to?)

That sounds awesome. Maybe it could depend on the amount of detected sinks, e.g. if there is just one sink anyway the option doesn't really make sense.

**Comment by LBCrion** [comment]
That was easier than I expected. Menu should be conditional on sink count > 1 now.

**Comment by LBCrion** [comment]
Can I just check that you're using the git version if the latest git version of the pulsectl.so module and of volume.widget? (since we now have a volume control interface, there is a unified config for alsactl and pulsectl).

If you're still seeing these with the latest config and module, can you please post the output of `sfwbar -d -g XVolumeControlTmpl`

**Comment by LBCrion** [comment]
Can you try adding this snippet to the #CSS section of volume.widget?

#hidden {
  -GtkWidget-visible: false;
}

**Comment by Ithvr** [comment]
Can confirm that the feature works well on v1.0_beta15.
Thank for implementing it.
