### ISSUE TITLE
sfwbar installed with custom prefix won't start

### ISSUE THREAD

**Issue by aashipov** [LBCrion/sfwbar#151]
meson setup ... --prefix=<some ${HOME} subdir> build
ninja -C build install

From console:
sfwbar

Watch error
** (sfwbar:3180): ERROR **: 05:00:47.735: Error: can't read config file winops.widget

Workaround
In ${HOME}/.config/sfwbar create symlinks to <some ${HOME} subdir>/share/sfwbar/*.widget

**Comment by LBCrion** [comment]
I added prefix/datafir to config search path. Would you mind testing if the latest git version works for you?

**Comment by aashipov** [comment]
Thank you, at 569dbbe no such issue
