### ISSUE TITLE
sfwbar prefers `/usr/share/sfwbar/sfwbar.config` over `~/.config/sfwbar/sfwbar.config` after `0b8182e`

### ISSUE THREAD

**Issue by Flrian** [LBCrion/sfwbar#152]
See title, no custom prefix or anything. I was using an ebuild on gentoo to install, but tested with

```
meson setup build
meson compile -C build
sudo meson install -C build
```
and the same thing happened there, just with `/usr/local/share/sfwbar/sfwbar.config`

**Comment by LBCrion** [comment]
Oops.  Put the hard coded directory too high in the search path priority.  Should be fixed now.
