### ISSUE TITLE
Hide some apps in taskbar

### ISSUE THREAD

**Issue by letkan** [LBCrion/sfwbar#156]
As the title says, is there an option to hide certain items in taskbar? In my case I run 2 conky scripts at startup of labwc and they have no reason to be in the taskbar. Something like a black list I'm thinking..
Thanks

**Comment by LBCrion** [comment]
This should be easy to implement, since taskbars already have a filtering
mechanism. I assume you would want to filter by an app_id or a title?
I am thinking that filtering should affect all taskbars and a window
switcher. Let me know if you prefer otherwise.

**Comment by Consolatis** [comment]
> In my case I run 2 conky scripts at startup of labwc and they have no reason to be in the taskbar.

This sounds like a good feature, just for the sake of completeness: you can also do the filtering in labwc via [window rules](https://labwc.github.io/labwc-config.5.html#window_rules).

**Comment by letkan** [comment]
> This should be easy to implement, since taskbars already have a filtering mechanism. I assume you would want to filter by an app_id or a title? 
That's right
>I am thinking that filtering should affect all taskbars and a window switcher. Let me know if you prefer otherwise.
No, this sounds good

Thanks for the fast reply

**Comment by letkan** [comment]
> This sounds like a good feature, just for the sake of completeness: you can also do the filtering in labwc via [window rules](https://labwc.github.io/labwc-config.5.html#window_rules).
This works as well
`<windowRules>
<windowRule identifier="conky*"  skipTaskbar="yes"></windowRule>
</windowRules>`
did the trick.

**Comment by LBCrion** [comment]
I am officially going senile in my old age. I started writing this functionality and realized it's already in the sfwbar. You can use toplevel keywords `FilterAppid` an `FilterTitle`. Both take regular expressions as inputs. I.e. `FilterAppid "firefox"` or `FilterTitle "^conky.*blah$"`

**Comment by letkan** [comment]
> I started writing this functionality and realized it's already in the sfwbar.
Good to hear, it fixed itself sort of :)

**Comment by LBCrion** [comment]
Current docs document FilterAppid and FilterTitle, so I'm closing this. Please feel free to reopen if anything else related to this issue is still outstanding.

**Comment by clemencyworld1** [comment]
Thanks for this insight. In my case, i want to filter and display only the focused window. What syntax should i use for that? Thanks

**Comment by LBCrion** [comment]
Do you mean you want to have a taskbar with a single item in it? Or do you just want to have a title of the focused window in your taskbar? The later you can get by using `ActiveWin` expression function, i.e. ``label { value = ActiveWin(); }``

If you do want a taskbar with just the item for the focused window in it, you can get it by hiding all other windows in css:
``
button#taskbar_normal {
  -GtkWidget-visible: false;
}
``

**Comment by clemencyworld1** [comment]
Thanks. Both will serve my use case. Just to check them out

**Comment by clemencyworld1** [comment]
"label { value = ActiveWin(); }" works well for me. The second command works also but instead of removing the inactive window buttons only hides its appearance and reserves space for them. Though i have no use case for such function at the moment. Thanks for prompt feedback
