### ISSUE TITLE
Feature request: middle click on taskbar program to close the program

### ISSUE THREAD

**Issue by milochadam** [LBCrion/sfwbar#16]

**Comment by LBCrion** [comment]
I'd like to make actions on taskbar buttons more configurable in general (similar to advanced actions on widgets). With new actions and functions it should be reasonably straightforward. I just need to figure out a good way to implement window-state conditional actions and window addressing in actions.

**Comment by LBCrion** [comment]
I added window actions in the main branch and added action support for taskbar buttons. To configure window close on middle click just add ``action[2] = Close`` to taskbar widget. Other actions supported are Focus, Minimize, Maximize, UnMinimize and UnMaximize.

**Comment by milochadam** [comment]
It works, thank you :)
