### ISSUE TITLE
Menus outputting garbage errors

### ISSUE THREAD

**Issue by 01micko** [LBCrion/sfwbar#160]
This occurs with my custom menu generator and the stock sfwbar `startmenu.widget`. I think the new code checking for 'id' is missing something but I can't figure it out. My small widget menus are not affected. I tested this by not including my widget and `startmenu.widget`.

Terminal output:
```
~$ sfwbar
10:11:09.76 duplicate menu item id: 'H�E�H�}�'
10:11:09.76 duplicate menu item id: 'H�E�H�}�'
10:11:09.76 duplicate menu item id: 'H�E�H�}�'
10:11:09.76 duplicate menu item id: 'H�E�H�}�'
10:11:09.76 duplicate menu item id: 'H�E�H�}�'
10:12:26.72 duplicate menu item id: 'H�E���UH��ATSH��`H�}�H�u�H�U�H�M�L�E�H�}�'
10:12:26.72 duplicate menu item id: 'H�E�H�}�'
10:12:26.72 duplicate menu item id: 'H�E�H�}�'
10:12:26.72 duplicate menu item id: 'H�E�H�}�'
10:12:26.72 duplicate menu item id: 'H�E�H�}�'
10:12:26.72 duplicate menu item id: 'H�E�H�}�'
10:12:26.72 duplicate menu item id: 'H�E�H�}�'
10:13:02.98 duplicate menu item id: 'H�E���UH��ATSH��`H�}�H�u�H�U�H�M�L�E�H�}�'
10:13:02.98 duplicate menu item id: 'H�E�H�}�'
10:13:02.98 duplicate menu item id: 'H�E�H�}�'
10:13:02.98 duplicate menu item id: 'H�E�H�}�'
10:13:02.98 duplicate menu item id: 'H�E�H�}�'
10:13:02.98 duplicate menu item id: 'H�E�H�}�'
10:13:02.98 duplicate menu item id: 'H�E�H�}�'

```

As I understand it from the docs, that `id` is optional and if used `MenuItemClear` needs to be called. ATM, I'm not using id's.

**Comment by LBCrion** [comment]
Sorry for slow response on the bug reports right now.  I'm travelling
without access to computer right now, so it will be another week before I
can look at this (and the other bugs). I think I know the cause of this one
and should be a quick fix.

**Comment by 01micko** [comment]
_Do not_ be sorry! Enjoy you're break. These are not show stoppers so relax and have fun! :smiley:

**Comment by LBCrion** [comment]
This should be fixed in the latest git :)

**Comment by 01micko** [comment]
Confirmed :+1:
