### ISSUE TITLE
Progressbars configuration help

### ISSUE THREAD

**Issue by letkan** [LBCrion/sfwbar#162]
This is not exactly an "issue" but I can't figure out how to configure 2 progressbars (cpu and ram) one above the other, the best I could do so far was one next to the other but that takes too much space. I can have this configuration with conky but why not use sfwbar if it's possible. 
Another configuration problem I have is that I wasn't able to align the bar to the right side in case I set its length to say 80% of the screen.
Any help would be appreciated, thanks.

**Comment by LBCrion** [comment]
try wrapping them into a grid with a downward direction. i.e.:

layout {
...
  grid {
    css = "* { -GtkWidget-direction: bottom; }"
    scale {
       settings for CPU progress bar
    }
    scale {
       settings for RAM progress bar
    }
  }
...
}

**Comment by letkan** [comment]
Thanks a lot, that did it.

**Comment by LBCrion** [comment]
You can use explicit coordinates in a grid, i.e.:
```
grid {
  label {
    value = "RAM:"
    loc (1,1)
  }
  scale {
    ....
    loc (2,1)
  }
  label {
    value = "CPU:"
    loc (1,2)
  }
  scale {
    ...
    loc (2,2)
  }
}
```

**Comment by LBCrion** [comment]
also, you can specify units for padding in css, i.e. `padding: 10px;` or `padding: 2mm;`

**Comment by letkan** [comment]
Excellent. Thanks

**Comment by LBCrion** [comment]
Closing this as it seems to be resolved. Please feel free to reopen if anything doesn't work still.
