### ISSUE TITLE
regression: icons in taskbar items are shown only in the first output

### ISSUE THREAD

**Issue by tokyo4j** [LBCrion/sfwbar#165]
After d89d2f30, icons in taskbar items are shown only in the first output.

![20240418_12h12m00s_grim](https://github.com/LBCrion/sfwbar/assets/22029524/1a34c41f-e7d2-4481-8534-d748d6daa4d0)

Config:
```
Function("SfwbarInit") {
  SetLayer "top"
  SetBarSize "100%"
  SetMirror "*"
}

layout {
  include("startmenu.widget")
  taskbar {
    style = "taskbar"
    rows = 1;
    icons = true;
    labels = true;
    sort = false;
  }
  tray
  include("battery-svg.widget")
  include("network-module.widget")
  include("volume.widget")
}

#CSS
window {
  -GtkWidget-direction: top;
}

```

**Comment by LBCrion** [comment]
This looks like an omission in mirroring flowgrid properties. I'll try to fix this in the next few days.

**Comment by LBCrion** [comment]
This should be fixed in the latest git. I still need to tweak it some more for a proper fix (i.e. the case where config may change icon/label settings on the fly).

**Comment by tokyo4j** [comment]
It worked! Thank you!
