### ISSUE TITLE
Segmentation fault when uncommenting SetBarSensor

### ISSUE THREAD

**Issue by keet77** [LBCrion/sfwbar#166]
Hello, I'm using the latest labwc (compiled from git a day or two ago) and swfbar 1.0 beta 14.  When I copy the default configuration from /usr/share/sfwbar/sfwbar.config to ~/.config/sfwbar/ and run sfwbar, it works fine.  If I uncomment line 19 (SetBarSensor "1000") and run sfwbar again, it crashes.  This is the output:

(sfwbar:377184): Gtk-WARNING **: 11:03:21.530: Theme parsing error: gtk.css:27:8: 'height' is not a valid property name

(sfwbar:377184): Gtk-WARNING **: 11:03:21.530: Theme parsing error: gtk.css:29:12: 'max-height' is not a valid property name

(sfwbar:377184): GLib-CRITICAL **: 11:03:21.597: g_hash_table_remove_all: assertion 'hash_table != NULL' failed
i3-ipc*input type:keyboard xkb_switch_layout nexti3-ipc*input type:keyboard xkb_switch_layout prevSegmentation fault (core dumped)

Could you please help figure out how to fix this?

**Comment by LBCrion** [comment]
I believe this the same issue as #139 . Are you able to check if the git version works for you?

**Comment by LBCrion** [comment]
Thank you for testing! I'll close this for now, but please do reopen if you see this re-occuring.
