### ISSUE TITLE
Icon in taskbar missing

### ISSUE THREAD

**Issue by letkan** [LBCrion/sfwbar#167]
I'm on Arch with labwc and have just installed Mercury browser. Pacman put it in _/opt/mercury-browser_ and the icons are in _/opt/mercury-browser/browser/chrome/icons/default/_ and they are named **default16.png**, etc.. What's the best approach to make sfwbar use a Mercury icon in the taskbar instead of this?
![20240421_21h13m20s_grim](https://github.com/LBCrion/sfwbar/assets/9017461/31d96b62-45c6-4c49-bffb-7ba8e0ae48b9)

**Comment by LBCrion** [comment]
1. run `sfwbar -d -g app_id` to get an app id of Mercury
2. symlink default16.png (or icon with a more appropriate size) to $HOME/.config/sfwbar/<appid>.png - replace <appid> with the app id you got in step 1

**Comment by letkan** [comment]
Ok, thanks, I'll do that

**Comment by letkan** [comment]
Great, it worked

**Comment by LBCrion** [comment]
Looks like this issue is resolved. I'll close it for now. If you run into this again (for this or other applications) please feel free to reopen.
