### ISSUE TITLE
Taskbar overlap window

### ISSUE THREAD

**Issue by Ithvr** [LBCrion/sfwbar#168]
I am using the git version (with labwc 0.7.1) and for some reason ssfebar is overlapping the windows I have open.
I can see this happening with vscodium, firefox, and stardew vally

**Comment by LBCrion** [comment]
Try adding `SetExclusiveZone "auto"` to `Function("SfwbarInit")`

**Comment by Ithvr** [comment]
Yeah, that worked. This is the danger of using a config that you don't understand.
