### ISSUE TITLE
How to add widgets dynamically?

### ISSUE THREAD

**Issue by salahoued** [LBCrion/sfwbar#169]
Hello,
trying _sfwbar_ with _labwc_
I have been 'playing' around with _sfwbar_, to try and put together a satisfying config. and its mostly going good.
I find it powerful but also compicated with the configuration.

The idea i have is because there is still no (stable wayland protocoles) support for workspaces in a lot of bars and taskbars with _labwc_. So the only way is to manually add them to the config like:

`layout {
  grid {
        style = "desktops"
		css = "* { -GtkWidget-direction: right; }"
		label {
			style = "desk"
			value = "1"
			action = "wtype -M win -P F1"
		}
		label {
			style = "desk"
			value = "2"
			action = "wtype -M win -P F2"
		}
		label {
			style = "desk"
			value = "3"
			action = "wtype -M win -P F3"
		}
		label {
			style = "desk"
			value = "4"
			action = "wtype -M win -P F4"
		}
	}

}`

Then I got the idea to write a python script to find the workspaces in _.config/labwc/rc.xml_ and the switching keybinds and add them to the bar like so with _wtype_:

`import xml.etree.ElementTree as et
from os.path import join, expanduser

rcfile = join( expanduser("~"), ".config/labwc/rc.xml" )
rctree = et.parse(rcfile)
rcroot = rctree.getroot()
meta_keys = {
    "A": "alt",
    "C": "ctrl",
    "M": "altgr",
    "S": "shift",
    "W": "win"
    }

def get_wtype(keyb):
    l = keyb.split("-")
    cmd = "wtype "
    for i in l:
        if i in meta_keys:
            cmd += "-M " + meta_keys[i] + " "
        else:
            cmd += "-P " + i + " "
    return cmd

keybinds = rcroot.findall("{*}keyboard/{*}keybind")
if keybinds:
	for key in keybinds:
		actions = key.findall("{*}action")
		if actions:
			for action in actions:
				if action.get("name") == "GoToDesktop":
					tos = action.findall("{*}to")
					if tos:
						for ato in tos:
							if ato.text.isdigit():
								k = key.get("key")
								print("label {\n style =  \"desk\"\n value = \"" + ato.text + "\" \n action = \"" + get_wtype(k) + "\"\n}")`

this script then returns:

`label {
 style =  "desk"
 value = "1" 
 action = "wtype -M win -P F1 "
}
label {
 style =  "desk"
 value = "2" 
 action = "wtype -M win -P F2 "
}
label {
 style =  "desk"
 value = "3" 
 action = "wtype -M win -P F3 "
}
label {
 style =  "desk"
 value = "4" 
 action = "wtype -M win -P F4 "
}
`

Is there a way to add that in the config file?

Thanks,

**Comment by Consolatis** [comment]
This is some amazingly hacky solution, I love it!
Technically you could also add something like `<action name="Execute" command="sh -c 'echo 2 > /tmp/current_workspace'" />` to each of the workspace switching keybinds and then have sfwbar read that file and have a current-workspace indicator.

**Comment by salahoued** [comment]
Thanks for your your suggestion, I have seen this 'kind' of method in other cases but never thought of using it in this.
Thanks a bunch.

And that hacky method above I got it when I was experimenting with _eww_ bar for workspaces, taskbar and active window (eww doesn't have a taskbar widget yet) using tools like _wlrctl_ and _lswt_, but didn't like it much.

**Comment by LBCrion** [comment]
You can create widgets on the fly.  The relevant actions are PipeRead and
Config.  The first one executes a command and parses is output as
configuration snippet.  The second takes a string and parses it as a config
snippet.

If you want to create a dynamic pager. First thing you need is to create a
grid into which you will add your widgets, something like:

Layout {
  ...
  Grid "my_pager" {}
  ...
}

This adds an empty grid with ID my_pager to your layout.

Next you need to tell sfwbar to call your script and parse its output, I.e.
via an RT signal: pkill -SIGRTMIN+5 sfwbar

In sfwbar,  you can bind an action to this signal:

TriggerAction "SIGRTMIN+5", PipeRead "/path/to/myscript"

Your script should output something like:

Grid "my_pager" {
  Label "pager_item_1" {
     Value = "1"
      Action = "wtype ..."
  }
}

This will add a label into your pager grid.  You want to create this label
with an ID, in this example pager_item_1, so you can destroy it later, if
needed. I.e.

TriggerAction "SIGRTMIN+6", ClearWidget Read("/path/to/file")

You'll need to write the name of the widget to destroy into a file before
sending SIGRTMIN+6 to sfwbar.

**Comment by Consolatis** [comment]
Can `PipeRead()` also be used in `SfwBarInit()`? That would allow to have the initial state without sending a signal.

**Comment by salahoued** [comment]
Hello,
Yeah I saw those actions, and a python script in _config/wifi.widget_, but I couldn't wrap my head around it (that's where I got these idea).

Sorry if I sound rude, but i couldn't find more examples in the documentation.

Thanks a lot

**Comment by LBCrion** [comment]
@Consolatis , Sure, you can use PipeRead in SfwbarInit
@salahoued , not at all. Sfwbar configuration is complex, unfortunately I haven't figured out a way to make it simpler without sacrificing configurability.

**Comment by salahoued** [comment]
@LBCrion , Sorry for the trouble, but how can I add the output of the script the layout using Config.
[desktop_labwc.txt](https://github.com/LBCrion/sfwbar/files/15140285/desktop_labwc.txt)

**Comment by LBCrion** [comment]
You can add it using piperead from sfwbarinit function,  I.e.:

Function("SfwbarInit")
{
...
  PipeRead("/path/to/script")
...
}

One thing to note is that this grid will be added to the end of your
layout,  since function sfwbarinit runs after config is processed. You also
won't be able to modify this pager,  since widgets in it don't have id's
assigned.

**Comment by salahoued** [comment]
@LBCrion , @Consolatis 
Sorry I was about to report my results, when I saw your last comment.
I have  successfully added the pager, without using _Config_ (I still don't know how to properly use it) and here is my solution:
 file : `~/.config/sfwbar/widgets/labwc_workspaces.widget` I put this config (inspiration from `wifi.widget`) :
`Scanner {
  file("/tmp/current_ws.txt") {
    CurrentWS = Grab()
  }
}

layout {

    action[0] = PipeRead "~/.local/bin/labwc-workspaces.py --ws-sfwbar GoToDesktop"
    grid "labwc_ws" {
		style = "desktops"
        css = "* { -GtkWidget-direction: right; }"
	}
}

#CSS
label#desk, label#desk_active {
    padding: 0 5px;
}
#desktops {
    padding: 0 5px;
    margin: 0 3px;
    color: alpha(black, 0.80);
    background-color: alpha(white, 0.70);
}
label#desk_active {
    font-weight: bold;
    color: alpha(black, 1);
}`

And here is the code for the python script `~/.local/bin/labwc-workspaces.py`  : 
``

**Comment by Consolatis** [comment]
You can use \`\`\` for code blocks, otherwise its quite hard to read. Something like

```python
***python
words=("some", "python", "code", "with", "multiple")
print(' '.join(words) + " lines")
***
```

The `python` keyword is optional and just improves the highlighting. Just replace `***` with \`\`\`

**Comment by salahoued** [comment]
@Consolatis , thanks I was working on better writing it again, so this is a quick solution for the time being
Sorry for the trouble

**Comment by LBCrion** [comment]
Nice. Hacks like this remind me why maintaining the flexibility in sfwbar is worth it. 

One change I would recommend is adding a CheckTime to the scanner,  to avoid constantly opening the file,  I.e.:
```
Scanner {
  file("/tmp/current_ws.txt", CheckTime) {
    CurrentWS = Grab()
  }
}
```

**Comment by salahoued** [comment]
Credit to @Consolatis , for that idea.
Thanks for the 'tip'.
