### ISSUE TITLE
Idle inhibitor randomly stops working if left turned off and swayidle kicks in by locking the screen

### ISSUE THREAD

**Issue by kode54** [LBCrion/sfwbar#170]
I am using wallock as my screen locker and desktop background, with labwc as my compositor, and wlroots 0.17.3.

Sometimes, I forget to turn on the idle inhibitor, and I'll go to play a fullscreen game with Steam, such as Fall Guys, which I mostly operate with a game controller. After 5 minutes of gameplay, the screen locker will kick in by running `wallock -o lock`, and I'll have to unlock the game.

After this happens, I'll alt-tab out of the game so I can free my cursor and click the idle inhibitor lock on the other monitor, but it doesn't toggle state. I'll have to run `systemctl --user restart sfwbar` to relaunch sfwbar to enable the idle inhibitor again.

Here is my service template:
```
[Unit]
Description=S* Floating Window Bar
Documentation=https://github.com/LBCrion/sfwbar/wiki
# order startup after WM
After=graphical-session.target

[Service]
ExecStart=/usr/bin/sfwbar
ExecReload=kill -SIGUSR2 $MAINPID
Restart=on-failure
Slice=app-graphical.slice

[Install]
# Get started via specific WMs
WantedBy=wayland-wm@sway.service
WantedBy=wayland-wm@wayfire.service
WantedBy=wayland-wm@labwc.service
WantedBy=wayland-wm@sway.desktop.service
WantedBy=wayland-wm@wayfire.desktop.service
WantedBy=wayland-wm@labwc.desktop.service
```

This is coupled with the [uwsm](https://github.com/Vladimir-csp/uwsm) session manager script.

**Comment by LBCrion** [comment]
Can I check what your config looks like? In particular the idle inhibit widget?

**Comment by kode54** [comment]
I'm using a mostly stock sfwbar.config, so it's using idle.widget. I did have a copy in my ~/.config/sfwbar folder, unmodified, because I thought I needed to have a local copy to use home folder icons. I was previously using altered icons because I was using a dark theme, and the stock locked/unlocked icons didn't work well on dark mode.

**Comment by LBCrion** [comment]
Ok, this looks like a fairly complex issue. Idle inhibit protocol is very simple, when we activate an inhibitor, we requires an inhibitor object for a surface (a surface of an idle inhibit widget in case of sfwbar) and to deactivate the inhibitor, we destroy the inhibitor object. I.e. it's really just a toggle on an inhibitor state of the surface, and it seems to be breaking somewhere.

A few questions that may help debug this:
1) If you activate the inhibitor before you launch the game, does it work? The screensaver never kicks in?
2) If the screensaver kicks in and you unlock it, and then escape from the game, does the lock icon on the inhibitor widget change when you click it?
3) Do you use an auto-hide feature of sfwbar? (i.e. SetSensor action)
4) Is the bar covered by any windows?
5) Do you use a mirrored taskbar (i.e. do you have sfwbar on each monitor?). If you do, can you please check whether your inhibitor actually stops working? I.e. if you click on the widget once after escaping from the game, does the screensaver kick in after 5min or is it in fact inhibited? (It could be that the icon doesn't update correctly on a mirrored bar).

**Comment by kode54** [comment]
> Ok, this looks like a fairly complex issue. Idle inhibit protocol is very simple, when we activate an inhibitor, we requires an inhibitor object for a surface (a surface of an idle inhibit widget in case of sfwbar) and to deactivate the inhibitor, we destroy the inhibitor object. I.e. it's really just a toggle on an inhibitor state of the surface, and it seems to be breaking somewhere.

Indeed a complex issue, sorry.

> A few questions that may help debug this:
> 
>     1. If you activate the inhibitor before you launch the game, does it work? The screensaver never kicks in?

The inhibitor toggles on if I remember to toggle it in the morning. I think. I'll have to remember to try this again tomorrow.


>     2. If the screensaver kicks in and you unlock it, and then escape from the game, does the lock icon on the inhibitor widget change when you click it?

I tab out of the game and move the mouse over to the secondary screen, and clicking the icon doesn't change the icon. However, the rest of the bar is responsive. I have to restart it from an open terminal to toggle it again.


>     3. Do you use an auto-hide feature of sfwbar? (i.e. SetSensor action)

I do not use auto-hide, I simply use the fullscreen mode of my compositor, either hinted by the game itself, or if the game doesn't set it properly, I have a Super+F shortcut bound in the compositor to toggle it.


>     4. Is the bar covered by any windows?

The bar is covered by the fullscreen game on the primary display, but not on the secondary display. Otherwise, I would not be able to click it at all.


>     5. Do you use a mirrored taskbar (i.e. do you have sfwbar on each monitor?). If you do, can you please check whether your inhibitor actually stops working? I.e. if you click on the widget once after escaping from the game, does the screensaver kick in after 5min or is it in fact inhibited? (It could be that the icon doesn't update correctly on a mirrored bar).

It is a mirrored bar on every display, but currently hidden on the primary due to a fullscreen game running. I will check tomorrow if I forget to toggle it on before running the game, and see if it actually toggles on. It does toggle on when hidden on the primary if I restart it first while the game is running, though.

**Comment by Consolatis** [comment]
@kode54 
In case you want to log the inhibitor being active / destroyed from the labwc side you can add some `wlr_log(WLR_ERROR, "inhibitor created");` in `handle_idle_inhibitor_{new,destroy}` @ `src/idle.c`.

**Comment by kode54** [comment]
I just realized something. Maybe this is only happening on login, because sfwbar is starting before swayidle does? I thought the compositor implemented the relevant services, not swayidle. Though labwc doesn’t have its own idle handler.

**Comment by Consolatis** [comment]
The compositor is only relaying information from both sides (and combining it with user input like mouse or keyboard). See [ext-idle-notify-v1.xml](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/blob/main/staging/ext-idle-notify/ext-idle-notify-v1.xml), likely used by swayidle and [idle-inhibit-unstable-v1.xml](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/blob/main/unstable/idle-inhibit/idle-inhibit-unstable-v1.xml) likely used by sfwbar.

**Comment by LBCrion** [comment]
@kode54, do you usually use the idle inhibit widget on the main display before you start the game and only use secondary display when the game is already running? I think this may be the cause of the problem. Idle inhibitor works on both displays, but the icon won't change when you click an inhibitor on the secondary display.

This is because the value of the widget (i.e. an icon in case of an image widget) is set once for the main instance of the widget and then inherited by the mirrored instances. So, if you click the inhibitor on the main bar, it will change the inhibitor state and update the icon. However, if you click it on the secondary bar, it will update the inhibitor correctly, but the widget will continue inheriting the (incorrect) icon from the primary instance.

I see two ways of addressing it. 
1. I can either change an idle inhibitor module to change the inhibitor state on the primary widget and all its mirrors simultaneously (the tricky bit would be handling a creation of a new mirror after the inhibitor is turned on).
2. Introduce a concept of unmirrored value for widgets. I.e. if this property is set for a widget it will use it's own value rather than inheriting a value from a primary instance.

**Comment by kode54** [comment]
Ah, yeah, you hit the nail on the head. It also works correctly for the secondary display if I first toggle it there, which then breaks the inheritance for the primary display.

**Comment by LBCrion** [comment]
This should be fixed in the latest git version. I implemented `local` property to prevent mirroring of widget values. `idle.widget` now uses this property and the inhibitors should update the icon independently across mirrored bars.

**Comment by kode54** [comment]
Cool. Works, though I don't know if this also means that multiple bars means multiple inhibitors can be loaded at once.

**Comment by LBCrion** [comment]
This was always the case. Since an idle inhibitor is created for a specific surface, you can create multiple inhibitors. The fix was just for the UI to reflect the state each inhibitor correctly.

**Comment by LBCrion** [comment]
What's interesting is that playing a game in fullscreen mode doesn't stop an inhibitor from functioning when the game covers it. In theory, the inhibitor should be ignored if the surface is occluded (at least if I'm reading the protocol spec correctly).

**Comment by Consolatis** [comment]
> What's interesting is that playing a game in fullscreen mode doesn't stop an inhibitor from functioning when the game covers it. In theory, the inhibitor should be ignored if the surface is occluded (at least if I'm reading the protocol spec correctly).

That is correct as far as I remember.
Labwc deliberately decided to go against that spec in this regard, other compositors may have done so as well.

There are actually quite some examples why following the spec here would go against the wishes of the user, mostly input not being relayed through the compositor like for gamepads (and thus not resetting compositor internal idle timers) and also fullscreen video players and similar that do not implement the idle inhibitor protocol.
