### ISSUE TITLE
"missing pattern in MapAppId"

### ISSUE THREAD

**Issue by winteriscariot** [LBCrion/sfwbar#173]
Due to a known issue with the Electron version used in the `spotify-launcher` package in Arch Linux repos, Spotify gets an empty app_id when launched Wayland native. It thus results in a generic SFW icon in sfwbar. I'm attempting to use the MapAppId function to map an appid to Spotify so it'll pick up an icon.

However, I get this error and I don't get the icon:

`$HOME/.config/sfwbar/sfwbar.config:1: missing pattern in MapAppId`

This is how Spotify appears in lswt when running in native Wayland:

```
~/.config $> lswt | grep Spotify
0: ---- "Spotify Premium" 
~/.config $>
``` 

This is the example given in the read me:

```
Mapping is supported via top-level MapAppId keyword. I.e. :

MapAppId app_id, pattern
```

This is the line in my config:

`MapAppId Spotify, "Spotify Premium"`

have I misunderstood the requirements?

**Comment by LBCrion** [comment]
Should be MapAppId "Spotify", "Spotify Premium"

**Comment by winteriscariot** [comment]
awesome, that worked, thanks!
