### ISSUE TITLE
How can I reduce my bottom BAR height

### ISSUE THREAD

**Issue by knm100** [LBCrion/sfwbar#175]
the default bar height is too high for me.  I can't find any way to do this in the Man manual. Is there no way to change the bar's height?

**Comment by LBCrion** [comment]
This is done through the CSS sheet of swbar, but there isn't a single place
where it's controlled. The minimum height is set in css = property of the
layout section, but there are other elements that would keep the current
height (i.e. padding + min-height of #module node, padding of #taskbar
nodes etc.) I should probably try to make the stylesheet a bit more
streamlined in this regard.

**Comment by knm100** [comment]
good for me, Looking forward to this being implemented.

**Comment by LBCrion** [comment]
I made configs more scalable, but a few things are still a pain. In
general, you can reduce the min-height of the main grid now to scale the
bar, but you will at least need to change the direction of the clock grid
(or remove the date from it), since otherwise the clock will dictate the
min height.
The bigger problem is margins for images (i.e. tray items, modules), GTK
goesn't support percent-length for margins, so they have to specified in
pixels. As you shrink the bar, you will need to adjust these or your images
will become too small.

**Comment by knm100** [comment]
in my oppion,it is best to have a fixed height setting, just like the width. so that if there is a problem with any widget, button, grid, etc., you can clearly see where the problem is,  in this way it is easy to  configure the sfwbar for  non-professional users.
Of course, this is the view from the user's point , and from the view of developer's point , there is  maybe more trouble than a non-fixed width

**Comment by knm100** [comment]
I would prefer to be able to specify a size directly, with no maximum and no minimum. but that's just what suits my personal preference.  maybe most other people would prefer min or max.   
limited to my level of CSS, I prefer to respond directly to the tweaks I've made in the config file.  that's why i prefer to be able to specify a size directly,with no maximum and no minimum.   
It doesn't matter if it destroys my layout, I can readjust it, I just don't know how to do it now, it seems to be unresponsive to my adjustments.

**Comment by LBCrion** [comment]
This is likely caused by -GtkWidget-vexpand being applied to images
somewhere.

**Comment by knm100** [comment]
readjust it done.   thanks

**Comment by knm100** [comment]
-GtkWidget-vexpand and  -GtkWidget-hexpand,  they are not  friendly to new.    The actual effect is not easy to control
 -GtkWidget-valign: center;  It is much simpler

**Comment by knm100** [comment]
Is there a way to set up "-GtkWidget-valign: center " to  global  except "progressbar#memory progress" & "progressbar#memory trough" & "progressbar#memory" ?

**Comment by knm100** [comment]
> sfwbar introduces -GtkWidget-max-width and -GtkWidget-max-height properties that limit the max size, but these are non-standard and won't survive the eventual migration to gtk4.
> Do you think it would be better to revert this and go back to sizing images to min-width/min-height?
now "-GtkWidget-max-width:" and "-GtkWidget-max-height“ have a problem wiht high cpu usage (git rev:4dffd40)
so I think it's probably better to return to using mini, anyway, it's going to prot to GTK4 soon, and MAX is gone, so there's no need to waste time on MAX, it's more valuable to spend time on GTK4
