### ISSUE TITLE
When I run sfwbar in the terminal, there is always a GTK warning

### ISSUE THREAD

**Issue by knm100** [LBCrion/sfwbar#176]
Although it does not affect the use, it always makes me  feel that there is something wrong as following
(sfwbar:748): Gtk-WARNING **: 14:34:35.799: Theme parsing error: <data>:9:0: Expected semicolon
add the debug log, maybe it is useful.
[debug.txt](https://github.com/LBCrion/sfwbar/files/15244851/debug.txt)

**Comment by 01micko** [comment]
There is something wrong in your CSS somewhere. If you use a custom config can you post it please?

**Comment by knm100** [comment]
> There is something wrong in your CSS somewhere. If you use a custom config can you post it please?

My config file is here, Please help!
[sfwbar.config.txt](https://github.com/LBCrion/sfwbar/files/15245367/sfwbar.config.txt)

**Comment by 01micko** [comment]
I see comments `#`  in CSS section. This isn't allowed. If you need to comment use C style : 
`/* commented section */`

**Comment by knm100** [comment]
That's true, there is no warning now！ thank you!
