### ISSUE TITLE
title_width in taskbar  didn't work

### ISSUE THREAD

**Issue by knm100** [LBCrion/sfwbar#177]
Although I set title_width = 30, it doesn't look like it is taking effect
![swappy-20240508-152213](https://github.com/LBCrion/sfwbar/assets/166389780/781eab96-9371-4dba-8256-3bed667431cb)

My taskbar section：
taskbar {
    rows = 1
    css = "* { -GtkWidget-hexpand: true; -FlowGrid-column-homogeneous: true; }" # stretch horizontally
    labels = true
    icons = true
    title_width = 36
#    group = pager  # remove this line if you don't want a multi-desktop taskbar
#    group icons = true
#    group labels = true
    sort = false
#    numeric = true

    action[RightClick] = Menu "winops"
    action[MiddleClick] = Close
    action[Drag] = Focus
  }

All of my  sfwbar.config 
[sfwbar.config.txt](https://github.com/LBCrion/sfwbar/files/15245270/sfwbar.config.txt)

**Comment by 01micko** [comment]
This is what I use for taskbar: (the `label` without a value seems to do it)

```
  taskbar {
    rows = 1
    css = "* { -GtkWidget-hexpand: false; }" # stretch horizontally
    title_width = 20
    sort = false
    group = false
    icons = true
    labels = true
    action[3] = Menu "winops"
  }
  label {
    css = "* { -GtkWidget-hexpand: true; }"
  }
```

**Comment by knm100** [comment]
After adding “ label  { {css = "* { -GtkWidget-hexpand: true; } }",   it did work.     than your very much!

**Comment by 01micko** [comment]
You're welcome!
