### ISSUE TITLE
Can I change the icons of  menu categories?

### ISSUE THREAD

**Issue by knm100** [LBCrion/sfwbar#179]
After  I  changed the phrase "'System': System" to "'System": System-tools' " in startmenu.widget,  The system  categorie  in the start menu has also become system-tools  categorie.    that's very good for me.  But the icon of  system categorie had become the SFW logo.
Judging by the content of the start menu,   it seem to me that  I can fix it  by copying   /usr/share/icons/Adwaita/symbolic/categories/preferences-system-symbolic.svg  to  $HOME/.icon/  and  renameing it to preferences-system-tools-symbolic.svg .   
     following this hunch， i did so.  unfortunately, nothing happened.    any way to fix it ?  please help!

**Comment by LBCrion** [comment]
try renaming it to applications-system-tools-symbolic.svg

**Comment by knm100** [comment]
Thank you very much.  It came into effect.   after moved the  preferences-system-symbolic.svg to $HOME/.icons/ or ./local/share/icons/  and renamed it to applications-system-tools-symbolic.svg.  the sfw log changed to  applications-system-tools-symbolic.svg.
