### ISSUE TITLE
`sfwbar -m DP-2` creates the bar on the active screen and not the one specified via `-m` parameter

### ISSUE THREAD

**Issue by milochadam** [LBCrion/sfwbar#18]

**Comment by LBCrion** [comment]
Do you have SetMonitor specified in function SfwBarInit? SetMonitor will override the -m parameter.

**Comment by milochadam** [comment]
No, I don't. Also, as in the title, it depends on which monitor the terminal is where I issue the command - is it possible that it stopped working with implementing SetMonitor?

**Comment by LBCrion** [comment]
Would you mind trying the current main branch? I think I found the issue.

**Comment by milochadam** [comment]
It works now, thank you :)
