### ISSUE TITLE
CSS property  in winops.widget  can affect  to  startmenu.widget

### ISSUE THREAD

**Issue by knm100** [LBCrion/sfwbar#180]
I set menu.item CSS property in winops.widget, But this seems to affect all menu.items.  
As explained in MAN, this effect should not be possible

**Comment by LBCrion** [comment]
Are you adding this snippet to a css = property or #!CSS section? The
former applies only to the widget it's defined for,  the latter applies to
all widgets.

**Comment by knm100** [comment]
I tried "css = " in two ways in winops.widget, but both of they didn't  work. and report a error wiht word " 11:03:33.96 /home/knm/.config/sfwbar/winops.widget:28: Unexpected toplevel token"
1.
menu("winops") {
  item("Focus", Focus );
  item("Close", Close );
  item("Maximize", Maximize );
  item("Minimize", Minimize );
 css = { menuitem  {  padding: 3px; }   };  
}

2.
menu("winops") {
  item("Focus", Focus );
  item("Close", Close );
  item("Maximize", Maximize );
  item("Minimize", Minimize );
}
css = { menuitem  {  padding: 3px; }   };

**Comment by LBCrion** [comment]
Menues aren't layout widgets, so you can't add a css property to a menu. It wouldn't be very useful anyway, since it would apply only to the menu widget, but not it's children (i.e. you wouldn't be able to style menu items). 

To style menu items in a specific menu, you can use it's name. I.e.:

```
menu#winops #menu_item {
  background-color: green;
}
```

**Comment by knm100** [comment]
thank your very much, this work well.
