### ISSUE TITLE
New widget for notification request

### ISSUE THREAD

**Issue by knm100** [LBCrion/sfwbar#183]
Is there a plan to develop a widget for notification that can integrate the notification programes like mako, swaync into the panel？

**Comment by LBCrion** [comment]
I don't think we can realistically integrate with one of the existing notification servers (i.e. mako or swaync), since they already to do the job of displaying notifications and there's not much we can do in the way of interacting with them. Realistically, I think we're looking at implementing a notification server within sfwbar. Looking at the spec for desktop notification protocol it should be possible to implement support for it via an sfwbar module. 

I think the question I would like to explore before jumping off the deep end on this is how notifications should look. Do we want to show a popup when a notification comes in or just show an icon on the bar (with an option to show a popup if user clicks on an icon?)

**Comment by knm100** [comment]
probably the notification  mean that   it's probably an icon that will be displayed when a notification comes, and when a notification comes in, it will simply show stauts of new notification(include source of notification) and the numbers of  notifications, and   click on the icon, there will be a pop-up window showing the content of the notification and sorting by group by time.
     maybe integrate an external program to do  the things  after  clicking on the icon,  it is more simply ways to develop this widget. 
  an idea from an  amateurs, maybe this will make things more difficult.

**Comment by knm100** [comment]
probably the notification  mean that   it's probably an icon that will be displayed when a notification comes, and when a notification comes in, it will simply show stauts of new notification(include source of notification) and the numbers of  notifications, and   click on the icon, there will be a pop-up window showing the content of the notification and sorting by group by time.
an idea from an  amateurs, maybe this will make things more difficult. maybe integrate an external program to do  the things  after  clicking on the icon,  it is more simply ways to develop this widget.

**Comment by Consolatis** [comment]
If sfwbar implements a notification service it should request a xdg_activation token on click of its surface and deliver that token back to the sender of the notification request. The token can be used by the sender to activate itself (e.g. raise to the top).

**Comment by knm100** [comment]
is it possible to do this as the way of  integrating the swaync to waybar ?

**Comment by LBCrion** [comment]
Something like this?
```
scanner {
  ExecClient("swaync-client -swb", "swaync") {
    SwayncLabel = Json(".text")
    SwayncTooltip = Json(".tooltip")
  }
}

layout {
  style = If($SwayncLabel!="","swaync","hidden")
  label {
    value = $SwayncLabel
    tooltip = $SwayncTooltip
    style = "swaync"
    trigger = "Swaync"
    action[LeftClick] = Exec "swaync-client -t -sw"
  }
}

#CSS

label#swaync {
  -GtkWidget-vexpand: true;
  -GtWidget-valign: center;
}
```

**Comment by knm100** [comment]
Yes, thank your very much.   Of course, this is only a makeshift,  Just Implement notification functions from 0 to 1. It would certainly be best if SWFBAR implemented notifications on its own.

**Comment by LBCrion** [comment]
It should give you the total number of pending notifications, so if you
have more than one notification outstanding, the widget should show the
correct number. I'll have a look at implementing full notification support,
but that will be in the next version of sfwbar at the earliest.

**Comment by knm100** [comment]
Yes, I need total number of pending notifications, thank you again.

**Comment by knm100** [comment]
I added a button, but for some reason what is in #CSS for button does not work.

layout {
  style = If($SwayncLabel!="","swaync","hidden")
  button {
    value = "preferences-system-notifications-symbolic"
    style = "swaynclauncher"
    tooltip = "notifications"
    action[LeftClick] = Exec "swaync-client -t -sw"
  }      
  label {
    value = $SwayncLabel
    #tooltip = $SwayncTooltip
    style = "swaync"
    trigger = "Swaync"
  }
}

#CSS

lable#swaync {
  -GtkWidget-vexpand: true;
  -GtWidget-valign: center;
  padding: 0px 5px 0px 0px;
  font-size: 8px;
}

button#swaynclauncher  {
  -GtkWidget-vexpand: true;
  -GtWidget-valign: center;
  padding: 0px 3px 0px 3px;
  min-width: 16px;
  min-height: 16px;
}

**Comment by LBCrion** [comment]
I suspect the button is styled correctly, but the image within it isn't,
try adding:

button#swaynclauncher image {
  -GtkWidget-vexpand: true;
  -GtkWidget-valign: fill;
}

or you can add min-height and min-width for the image if you prefer.

**Comment by knm100** [comment]
I set it like this, the button section works, but the padding of the lable section  doesn't work.

#CSS
lable#swaync {
  -GtkWidget-vexpand: true;
  -GtWidget-valign: center;
  padding: 0px 5px 0px 3px;
}
button#swaynclauncher {
   padding: 0px 0px 0px 0px;
   border: none;
} 
button#swaynclauncher image {
  -GtkWidget-vexpand: true;
  -GtkWidget-valign: fill;
  -gtk-icon-effect: dim;
  min-width: 16px;
  min-height: 16px;
  border: none;
  padding: 0px;
  margin: 0px;
}

**Comment by LBCrion** [comment]
What padding are you trying to set? In the below, you're setting top and
bottom padding. Since the widget is centered,  it will only have effect of
the widget spans the entire vertical height of the bar.

**Comment by knm100** [comment]
The top is the effect of padding: 0px 5px 0px 3px, and below is the padding: 3px 0px 0px 5px; effect
![swappy-20240512-214723](https://github.com/LBCrion/sfwbar/assets/166389780/6ad450c0-06b9-46ca-89a5-ffe88e8bbe6c)

**Comment by knm100** [comment]
according to  https://developer.mozilla.org/en-US/docs/Web/CSS/padding,   the padding should be  format: padding: (top  right  bottom left)
![swappy-20240512-222426](https://github.com/LBCrion/sfwbar/assets/166389780/c63756f7-8fba-49a9-972c-1134e301eea2)

**Comment by LBCrion** [comment]
Indeed,  you're right.  Looking at the config,  you have a node named
lable#swaync, it should be label#swaync

**Comment by knm100** [comment]
Ah, a spelling mistake.   I'm so sorry for wasting your time!   it work now. thank you!

**Comment by LBCrion** [comment]
Ok, I got a basic notification module working. I need some programs to test
with though. Any good examples to test with that don't have much in the way
of dependencies and can be easily triggered to send a notification?
Preferably something that sends an image over dbus rather than just an icon
name. I've been using notify-send so far, but it doesn't support sending
images.

**Comment by knm100** [comment]
You can refer to the arch wiki(https://wiki.archlinux.org/title/Desktop_notifications#Standalone), where there is a reference to notify-send sending images

**Comment by LBCrion** [comment]
I merged an initial implementation of the notification center widget. You can test it with the latest git but including `ncenter.widget` into your layout (you do need the latest git version of sfwbar to use it and you need to build with ncenter option enabled).

**Comment by knm100** [comment]
Ok,  I will try it.

**Comment by knm100** [comment]
everything is OK but no icons of program and pop-ups.

**Comment by LBCrion** [comment]
Notifications for which applications are missing icons? I can see icons for
the few examples I've tested with, but there could be other ways to send
them that I haven't implemented yet.

**Comment by knm100** [comment]
I just tried it with thunderbird.

> I can see icons forthe few examples 

what  is their name?  I will try they to verify if  my environments casue no icons.

**Comment by LBCrion** [comment]
Would you mind running the following command and see what output you get
when thunderbird sends a notification?

sfwbar -d -g "ncenter:"

**Comment by knm100** [comment]
Please refer to the following message.  
knm@archlinux ~]$ sfwbar -d -g "ncenter:" 
i3-ipc*input type:keyboard xkb_switch_layout nexti3-ipc*input type:keyboard xkb_switch_layout prev
(sfwbar:5724): GLib-CRITICAL **: 09:52:30.187: g_hash_table_remove_all: assertion 'hash_table != NULL' failed
^C

**Comment by LBCrion** [comment]
Was this session running while thunderbird sent a notification,  I.e. did
this sfwbar process display a notification without an icon? I would have
expected at least one line starting with "ncenter:" showing the details of
that notification.

**Comment by knm100** [comment]
Actually, I think there's no output. 
Because I ran this command before Thunderbird started, and then ran it again after thunderbird started and received an email and showed an unread message in the panel, the output was the same both times

**Comment by LBCrion** [comment]
You ran out before and after? Do you mean that this cool van be doesn't
produce a running sfwbar session,  or doesn't create a bar that stays open
while thunderbird emits a notification? How do you normally start sfwbar on
your machine?

**Comment by knm100** [comment]
Tested again, Please refer to the following message:
[knm@archlinux ~]$ sfwbar -d -g "ncenter:" 
i3-ipc*input type:keyboard xkb_switch_layout nexti3-ipc*input type:keyboard xkb_switch_layout prev
(sfwbar:7857): GLib-CRITICAL **: 10:32:04.161: g_hash_table_remove_all: assertion 'hash_table != NULL' failed
10:32:54.96 ncenter: found image data
10:32:54.96 ncenter: app: 1, action: default: 'Activate'
10:32:54.96 ncenter: app: 'Thunderbird', id: 1, icon: '', summary 'XXXX@126.com received 1 new message', body 'test for sfwbar from "XXXX"', timeout: 0
![swappy-20240706-103917](https://github.com/LBCrion/sfwbar/assets/166389780/9d80e4ca-fd5b-443e-9798-c5b7b97bd964)

**Comment by LBCrion** [comment]
Thank you! This is exactly what I needed. Can you try the latest git
version and see if it shows an icon? (this is exactly the kind of example I
was looking to test).

**Comment by knm100** [comment]
Tried the latest git rev(There are several warnings output by the compiler ）,Please refer to the following message 
[knm@archlinux ~]$  sfwbar -d -g "ncenter:"
i3-ipc*input type:keyboard xkb_switch_layout nexti3-ipc*input type:keyboard xkb_switch_layout prev
(sfwbar:10013): GLib-CRITICAL **: 23:18:37.294: g_hash_table_remove_all: assertion 'hash_table != NULL' failed
23:20:06.50 ncenter: found image data
23:20:06.50 ncenter: app: 1, action: default: 'Activate'
23:20:06.50 ncenter: app: 'Thunderbird', id: 1, icon: '', summary 'xxxxx@126.com received 3 new messages', body '[LBCrion/sfwbar] New widget for notification request (Issue #183) from LBCrion
Thank you! This is exactly what I needed', timeout: 0
23:22:10.28 ncenter: expand event: 'Thunderbird'
23:22:11.15 ncenter: expand event: 'Thunderbird'
23:22:13.58 ncenter: expand event: 'Thunderbird'
23:22:13.81 ncenter: expand event: 'Thunderbird'
23:22:18.81 ncenter: invoke action: 1, 'default'
23:22:19.68 ncenter: invoke action: 1, 'default'
23:22:19.93 ncenter: invoke action: 1, 'default'
23:22:22.17 ncenter: expand event: 'Thunderbird'
23:22:45.09 ncenter: expand event: 'Thunderbird'
23:22:53.55 ncenter: expand event: 'Thunderbird'
23:23:05.60 ncenter: collapse event: 'Thunderbird'
23:23:16.34 ncenter: expand event: 'Thunderbird'
23:23:17.71 ncenter: expand event: 'Thunderbird'
23:23:20.74 ncenter: collapse event: 'Thunderbird'
23:23:22.74 ncenter: expand event: 'Thunderbird'
23:23:26.70 ncenter: expand event: 'Thunderbird'
23:23:26.93 ncenter: expand event: 'Thunderbird'
23:23:27.94 ncenter: invoke action: 1, 'default'
23:23:31.02 ncenter: collapse event: 'Thunderbird'
23:23:31.81 ncenter: close event: 1
![swappy-20240706-232202](https://github.com/LBCrion/sfwbar/assets/166389780/cc9d3504-254b-4146-bbbc-4cdc1cabbc27)

**Comment by knm100** [comment]
Tried the latest git rev(There are several warnings output by the compiler ）,Please refer to the following message 
[knm@archlinux ~]$  sfwbar -d -g "ncenter:"
i3-ipc*input type:keyboard xkb_switch_layout nexti3-ipc*input type:keyboard xkb_switch_layout prev
(sfwbar:10013): GLib-CRITICAL **: 23:18:37.294: g_hash_table_remove_all: assertion 'hash_table != NULL' failed
23:20:06.50 ncenter: found image data
23:20:06.50 ncenter: app: 1, action: default: 'Activate'
23:20:06.50 ncenter: app: 'Thunderbird', id: 1, icon: '', summary 'xxxxx@126.com received 3 new messages', body '[LBCrion/sfwbar] New widget for notification request (Issue #183) from LBCrion
Thank you! This is exactly what I needed', timeout: 0
23:22:10.28 ncenter: expand event: 'Thunderbird'
23:22:11.15 ncenter: expand event: 'Thunderbird'
23:22:13.58 ncenter: expand event: 'Thunderbird'
23:22:13.81 ncenter: expand event: 'Thunderbird'
23:22:18.81 ncenter: invoke action: 1, 'default'
23:22:19.68 ncenter: invoke action: 1, 'default'
23:22:19.93 ncenter: invoke action: 1, 'default'
23:22:22.17 ncenter: expand event: 'Thunderbird'
23:22:45.09 ncenter: expand event: 'Thunderbird'
23:22:53.55 ncenter: expand event: 'Thunderbird'
23:23:05.60 ncenter: collapse event: 'Thunderbird'
23:23:16.34 ncenter: expand event: 'Thunderbird'
23:23:17.71 ncenter: expand event: 'Thunderbird'
23:23:20.74 ncenter: collapse event: 'Thunderbird'
23:23:22.74 ncenter: expand event: 'Thunderbird'
23:23:26.70 ncenter: expand event: 'Thunderbird'
23:23:26.93 ncenter: expand event: 'Thunderbird'
23:23:27.94 ncenter: invoke action: 1, 'default'
23:23:31.02 ncenter: collapse event: 'Thunderbird'
23:23:31.81 ncenter: close event: 1
![swappy-20240706-232202](https://github.com/LBCrion/sfwbar/assets/166389780/cc9d3504-254b-4146-bbbc-4cdc1cabbc27)

**Comment by knm100** [comment]
warnings output by the compiler:
```
Found ninja-1.12.1 at /usr/bin/ninja
WARNING: Running the setup command as `meson [options]` instead of `meson setup [options]` is ambiguous and deprecated.
ninja: Entering directory `build'
[73/91] Compiling C object ncenter.so.p/modules_ncenter.c.o
../modules/ncenter.c: In function ‘dn_parse_image_data’:
../modules/ncenter.c:272:12: warning: passing argument 1 of ‘g_free’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  272 |     g_free(copy);
      |            ^~~~
In file included from /usr/include/glib-2.0/glib/glist.h:34,
                 from /usr/include/glib-2.0/glib/ghash.h:36,
                 from /usr/include/glib-2.0/glib.h:52,
                 from ../modules/ncenter.c:1:
/usr/include/glib-2.0/glib/gmem.h:74:46: note: expected ‘gpointer’ {aka ‘void *’} but argument is of type ‘const void *’
   74 | void     (g_free)         (gpointer          mem);
      |                            ~~~~~~~~~~~~~~~~~~^~~
[91/91] Linking target sfwbar

```

**Comment by LBCrion** [comment]
This warning should be fixed now (an incorrect var type in a declaration).

@Consolatis, I'm working on xdg-activation support. Do you know what clients I can test it with?

**Comment by LBCrion** [comment]
Actually, it looks like xdg-activation works fine with the current git version of labwc (tested with thunderbird), but not with sway 1.9.

**Comment by Consolatis** [comment]
> @Consolatis, I'm working on xdg-activation support. Do you know what clients I can test it with?

From memory I tested it with thunderbird as well. Desktop notifications via browser might also work.
Something unrelated to notifications is using foot to launch a URL, it should request a valid token and supply it to xdg-open which then does some magic to supply it to the running browser which in turn then activates itself.

> Actually, it looks like xdg-activation works fine with the current git version of labwc (tested with thunderbird), but not with sway 1.9.

That might actually be a labwc bug, at the time when we implemented the xdg-activation protocol we could not properly check for the surface being valid due to a wlroots limitation. That has been fixed in wlroots but labwc still doesn't enforce a valid surface attached to the token and thus allows less privileged tokens than intended.

To test this assumption you could patch labwc and check for the surface being set.
Note that the diff is just for debugging and would also prevent the activation of the target window if the notification surface was destroyed in the meantime. To work around that for testing you could keep the notification surface open.

<details>
<summary>labwc debug diff</summary>

```diff
diff --git a/src/xdg.c b/src/xdg.c
index 86ee06c3..0b3ff714 100644
--- a/src/xdg.c
+++ b/src/xdg.c
@@ -685,6 +685,10 @@ xdg_activation_handle_request(struct wl_listener *listener, void *data)
 		wlr_log(WLR_INFO, "Denying focus request, seat wasn't supplied");
 		return;
 	}
+	if (!event->token->surface) {
+		wlr_log(WLR_ERROR, "Denying focus request, source surface not set");
+		return;
+	}
 	/*
 	 * We do not check for event->token->surface here because it may already
 	 * be destroyed and thus being NULL. With wlroots 0.17 we can hook into
```

</details>

**Comment by LBCrion** [comment]
Indeed, it looks like surface/serial checks are failing with sway:
```
00:01:26.430 [wlr] [types/wlr_xdg_activation_v1.c:120] Rejecting token commit request: surface doesn't have focus
00:01:26.442 [wlr] [types/wlr_xdg_activation_v1.c:112] Rejecting token commit request: serial 0 was never given to client
```
I can see that this is going to be fun, given the challenges of getting a focused layer shell surface and a correct serial out of the bowels of GTK.
