### ISSUE TITLE
 can display the comment in desktop file  to start menu according to the user's locale1

### ISSUE THREAD

**Issue by knm100** [LBCrion/sfwbar#184]
Almost all desktops already have localized comments, which is useful to localize the menu.

**Comment by knm100** [comment]
Just a suggestion, not urgent, if it has an impact on your schedule, feel free to ignore it

**Comment by LBCrion** [comment]
Do you mean the current locale sfwbar is running with?

**Comment by LBCrion** [comment]
I added a `getlocale()` expression function, which returns LC_ALL form of the current locale. You can select a localized string based on the current locale like this:
```
Set LocalString = Map(Extract(getlocale(), "(.*)_"),
    "en", "hello",
    "es", "hola",
    "default message for unhandled locale");

layout {
  ...
  label "mylabel" {
    value = $LocalString
  }
}
```

I set the function as deterministic for now, so that it doesn't cause constant string re-evaluation.  You will need to manually trigger an update if the locale is changed (i.e. using ``SetValue "mylabel", $LocalString``).

**Comment by knm100** [comment]
LC_ALL ？ it usually  is set to empty.   LANG might be a better option
![swappy-20240513-152928](https://github.com/LBCrion/sfwbar/assets/166389780/6deccae8-c61d-40ef-b9af-23a9ea54a946)

**Comment by knm100** [comment]
about locale1, please refer to https://www.freedesktop.org/software/systemd/man/latest/org.freedesktop.locale1.html

**Comment by knm100** [comment]
![swappy-20240513-212716](https://github.com/LBCrion/sfwbar/assets/166389780/81df9512-c345-4ba1-aa77-b8462f5a0861)
![swappy-20240513-213108](https://github.com/LBCrion/sfwbar/assets/166389780/3d67d56c-a346-425b-97e0-83719a5697c6)
The same config+widget,  the first picture is a display of the latest 4dffd40 rev, the second picture is  a display of the latest 6b1f740 rev.     It seems that all the CSS in $HOME/.config/sfwbar/ doesn't work anymore!

**Comment by LBCrion** [comment]
I expect this is a byproduct of #175. Let's discuss this in more detail there.

**Comment by LBCrion** [comment]
Right, I was thinking locale rather than locale1 (I'm still not used to all this newfangled systemd stuff). I suspect the best way to introduce this would be to implement basic dbus property monitoring in the scanner, but this would likely need to wait for the next version.

**Comment by knm100** [comment]
No problem, That's not an urgent thing.
