### ISSUE TITLE
Is it possible to specify max width for taskbar?

### ISSUE THREAD

**Issue by milochadam** [LBCrion/sfwbar#19]

**Comment by LBCrion** [comment]
No currently, let me add an option for this.

**Comment by LBCrion** [comment]
This should be possible in the main branch now.

Function("SfwBarInit") {
SetBarSize "800"
}

This would set bar width to 800 pixels. You can also use percentages of screen size, i.e. "50%"

**Comment by milochadam** [comment]
Oh, now I see I've been imprecise. I meant taskbar labels - when a program has a long title I would like to cap it so it doesn't take up half of the taskbar like this:
![image](https://user-images.githubusercontent.com/27895477/150697806-431fc6e8-edc0-457d-9461-173a5f1402f6.png)

**Comment by LBCrion** [comment]
I added this in the latest main, you can limit the title length using title_width option in the taskbar widget, i.e.

taskbar {
rows = 1
icons = true
labels = true
title_width = 15
}

You would also want to make sure that taskbar buttons don't have -GtkWidget-hexpand: true; in CSS (either in css property in taskbar or in #taskbar_normal or #taskbar_active in the main CSS section).

**Comment by milochadam** [comment]
Thank you, I appreciate it :)
