### ISSUE TITLE
Feature request toggle maximized for the taskbar

### ISSUE THREAD

**Issue by guzz46** [LBCrion/sfwbar#195]
If possible it would be great if there was a toggle maximized option for the taskbar, thanks.

**Comment by LBCrion** [comment]
This should already be included in the winops.widget. If you right click on a taskbar item, you should get a menu with an (un)Maximize option. (If you use a grouped taskbar, i.e. t2.config, you may need to grab the latest git as I just fixed a bug in the git version).

**Comment by guzz46** [comment]
I should have clarified toggle maximize as a click option, for example currently you can configure right click to maximize, but you can't un-maximize it by right clicking again.

**Comment by LBCrion** [comment]
Make sure you have windows.widget included and set:

action[RightClick] = Function "ToggleMaximize"

**Comment by guzz46** [comment]
Do you mean 

include("windows.widget")

If so where do I find that?

**Comment by guzz46** [comment]
I got it, I had to set

include("winops.widget")

And edit the taskbar like so

```
  taskbar {
    css = "* { -GtkWidget-vexpand: false; border: }" 
    sort = false
    icons = true     
    labels = false   
    cols = 1
    action[2] = Close
    action[RightClick] = Function "ToggleMaximize"
  }
