### ISSUE TITLE
Incorrect taskbar groups (sub-items) positioning

### ISSUE THREAD

**Issue by Vimux** [LBCrion/sfwbar#202]
**Description:**

All programs (?) started after sfwbar are arranged incorrectly (horizontally) in the taskbar sub-menu, while the previous programs are arranged correctly (vertically). Maybe that's not the reason, but sub-items are arranged differently for sure.

**Steps to reproduce:**

1. Open several windows of any program (`foot` in the example)
2. Run sfwbar (`w10.config`)
3. Make sure that the sub-items are positioned correctly
4. Open several windows of any *other* program (`mpv` in the example)

**Expected behavior:**

Sub-items are arranged in a uniform manner.

**Actual behavior:**

Sub-items are arranged differently.

**Screenshots:**

*Correct:*
![1](https://github.com/LBCrion/sfwbar/assets/21033483/52279b9d-0c51-4b31-94fe-7c090bef627d)

*Incorrect:*
![2](https://github.com/LBCrion/sfwbar/assets/21033483/cf99282d-a7e8-482e-9033-b504ac876a3f)

**Info**:

* Latest git (https://github.com/LBCrion/sfwbar/commit/125209a7f72ebe1aa6e17a0068ed66bf20f97e07)

**Comment by LBCrion** [comment]
I think I found the reason. Can you test if the latest git version fixes
this for you please?

**Comment by Vimux** [comment]
Indeed, fixed.
