### ISSUE TITLE
Allow Python script embedded in startmenu.widget to be used on its own

### ISSUE THREAD

**Issue by jjramsey** [LBCrion/sfwbar#204]
I wanted to customize my Start menu so that the generated menu was a submenu accompanied by some favorites.

What I ended up doing was copying the Python script in the original startmenu.widget and getting rid of some no-longer necessary backslashes (result here: [Create_Menugen_Applications_For_Sfwbar.py](https://github.com/user-attachments/files/16150717/Create_Menugen_Applications_For_Sfwbar_py.txt), and then using that in my own script for creating menus:

```sh
#!/bin/sh
echo 'menuclear("StartMenu")'
echo 'menu("StartMenu") { item("Firefox%/usr/share/icons/hicolor/scalable/apps/firefox.svg", Exec "firefox") }'
echo 'menu("StartMenu") { item("Qterminal%utilities-terminal", Exec "qterminal") }'
echo 'menu("StartMenu") { item("PCManFM-Qt%system-file-manager", Exec "pcmanfm-qt") }'
echo 'menu("StartMenu") { separator }'
echo 'menu("StartMenu") { item("Search apps ...%/usr/share/icons/hicolor/scalable/actions/category-search-symbolic.svg", Exec "rofi -show drun") }'
Create_Menugen_Applications_For_Sfwbar.py
echo 'menu("StartMenu") { submenu("Browse apps", "MenuGen_Applications") }'
echo 'menu("StartMenu") { item("Exit", Exec "wayland-exit-dialog.py") }'
```
I have used this successfully in my own custom start menu widget.

What I would like would have been to not have to have done the first part. The Python script from the startmenu.widget script is more generally useful when it *isn't* embedded, and it would be nice for anyone to make use of it in their own customized widgets, much as I did.

**Comment by LBCrion** [comment]
One of the reasons for this config was to have an example of an embedded python script. Splitting the script would also make life a bit more difficult, since it will need to be placed into a suitable location, which may be system dependent. As a result, configs will need to have to be updated at the installation time to correctly identify location of the script.

I wonder if it makes sense to move the embedded script into a .source config file. This way it can stay as an embedded script example, but you should be able to use it as part of your custom menu. I.e. instead of running a script, you can run call a function that would build the submenu for you that you can then add into your custom menu.

**Comment by jjramsey** [comment]
> One of the reasons for this config was to have an example of an embedded python script.

You've still got an example in battery.widget. Arguably, it's even a better one, because it's shorter and not much use outside of the battery.widget.

> it will need to be placed into a suitable location, which may be system dependent.

True, but that could be said for the location of the "sfwbar" executable itself. I'd suggest putting it in the same location as that executable, much as, say, the executables "labwc" and "labwc-menu-generator" are typically in the same path as well.

> I wonder if it makes sense to move the embedded script into a .source config file. This way it can stay as an embedded script example, but you should be able to use it as part of your custom menu. I.e. instead of running a script, you can run call a function that would build the submenu for you that you can then add into your custom menu.

If you can swing it, that might would work for me, especially if you can show that you can get the same results that I got.

**Comment by LBCrion** [comment]
Sure, I spit the script into startmenu.source, here's an example of a custom menu using it:
```
include("startmenu.source")

Function("CustomMenuShow") {
  MenuClear "CustomStartMenu"
  Config 'Menu("CustomStartMenu") {
  item("Firefox%/usr/share/icons/hicolor/scalable/apps/firefox.svg", Exec "firefox")
  item("Qterminal%utilities-terminal", Exec "qterminal")
  item("PCManFM-Qt%system-file-manager", Exec "pcmanfm-qt")
  separator
  item("Search apps ...%/usr/share/icons/hicolor/scalable/actions/category-search-symbolic.svg", Exec "rofi -show drun")
  submenu("Browse apps", "MenuGen_Applications")
  item("Exit", Exec "wayland-exit-dialog.py")
  }'

  Function "StartMenuBuild"
  Menu "CustomStartMenu"
}

layout {
  button {
    value = "open-menu"
    style = "startmenu"
    action = Function "CustomMenuShow"
    tooltip = "Application menu"
  }
}
```

**Comment by jjramsey** [comment]
That looks workable to me, so I'll close this issue. Thanks!
