### ISSUE TITLE
Segfaulting when clicking icons

### ISSUE THREAD

**Issue by wastlnd** [LBCrion/sfwbar#207]
Installed on Arch Linux, gtk3 up to date. Starting from the latest beta, everytime I click on the icon of a running pcmanfm or sakura terminal, I have a segfault with this error in console:
`base_widget_get_mirror_parent: assertion 'IS_BASE_WIDGET(self)' failed`

**Comment by Vimux** [comment]
Have you tried the latest git? Sounds like a duplicate #205.

**Comment by wastlnd** [comment]
Yess that fixed it, thanks:)
