### ISSUE TITLE
sfwbar core dumped when clicking an item in taskbar group

### ISSUE THREAD

**Issue by salahoued** [LBCrion/sfwbar#209]
I have set my taskbar to group the tasks
```
group = popup
group cols = 1
group icons = true
group labels = true
```

lately, sometimes (not every time) when hovering over a group of task the tasks are shown/sorted horizontally like:
I'm not sure how to reproduce this issue.
+----------+----------+
| task 1 | task 2 |
+----------+-----------+

instead of 
+----------+
| task 1 |
+----------+
| task 2 |
+-----------+
![20240719_21h33m30s_grim](https://github.com/user-attachments/assets/2579f664-dfa6-478d-be76-4bfdc2b34cd8)

And when selecting/clicking a task from the group `sfwbar` core dump.
```
21:37:34,71 base_widget_get_mirror_parent: assertion 'IS_BASE_WIDGET(self)' failed
Erreur de segmentation (core dumped)
```

**Comment by LBCrion** [comment]
Can you please check if these issues still happen with the latest git?
These look like #202 and #205.

**Comment by salahoued** [comment]
Yes they are the same issues, sorry I didn't check if there are similar issues to mine before writing this.

And this issues no longer happen in the latest git version, it works fine.

Thanks and sorry.
