### ISSUE TITLE
Feature request: make taskbar show only windows from currently active workspace

### ISSUE THREAD

**Issue by milochadam** [LBCrion/sfwbar#21]
I also noticed only windows that support Wayland are listed. Firefox is there but no Google Chrome. Is it possible to include XWayland windows aswell?
Another thing: is it possible to remmber state of the window before minimizing? Currently clicking a window in a taskbar unminimizes it but it doesn't maximize it if it was maximized before minimizing.

**Comment by LBCrion** [comment]
Xwayland windows should now work. Let me look at the other bits.

**Comment by milochadam** [comment]
I just remembered another somewhat annoying thing: when I click a window from the taskbar it automatically moves the cursor to the window (it's undesirable for example if I have several browser windows open and I just want to peek). Would it be possible to disable that?

**Comment by LBCrion** [comment]
Do you mean the keyboard input moves to a selected window? The default action on click is to focus a window. The focused window gets input. I can't see a way in sway to bring window to the top without focusing it. Do you know of one?

**Comment by milochadam** [comment]
I don't mind the focus, I don't like that the cursor is moved to the center of the window if it's on display other than the sfwbar. If the window is on the same display as the bar the cursor stays where it was. In this context I would be satisfied with being able to make the taskbar show only windows from the same workspace as the bar's instace.

**Comment by LBCrion** [comment]
I'm looking into per-output taskbar. This poses an interesting question for minimized windows. Sway doesn't have a concept of a minimized window, so we move them to a scratchpad instead. Scratchpad is it's own output, so minimized windows don't belong to any monitor.
For windows minimized during a session, I can simply keep them mapped to a monitor on which they last appeared, but if the bar is restarted, we lose this information and minimized windows will not appear on any monitor.
One solution would be to add minimized windows to bars on all outputs on startup, this way a window isn't lost and a bar that unminimizes it first claims it. This isn't the tidiest solution, but it would work.

**Comment by LBCrion** [comment]
I implemented a prototype of the above approach in main, you can enable it by adding

filter_output = true

to the taskbar widget.

**Comment by milochadam** [comment]
Hi @LBCrion, yes and sorry for the late response. And thank you :)
