### ISSUE TITLE
Segfault when launching `waybar` -> `nm-applet` -> `sfwbar` -> `labwc`

### ISSUE THREAD

**Issue by tokyo4j** [LBCrion/sfwbar#215]
## How to reproduce
1. Start labwc with `labwc -C /tmp`
2. Launch `foot` by pressing `Super+Enter`
3. Run following commands one-by-one:
```
waybar &
nm-applet &
sfwbar &
labwc
```
4. Sfwbar segfaults at `sni_watcher_item_lost_cb()`
```
Thread 1 "sfwbar" received signal SIGSEGV, Segmentation fault.
0x00007ffff7f948c4 in sni_watcher_item_lost_cb (con=0x555555592610, name=0x555555a48370 ":1.791", item=0x555555a515e0)
    at ../src/sni.c:62
62        g_debug("sni watcher %s: lost item: %s", item->watcher->iface, name);
(gdb) bt
#0  0x00007ffff7f948c4 in sni_watcher_item_lost_cb (con=0x555555592610, name=0x555555a48370 ":1.791", item=0x555555a515e0)
    at ../src/sni.c:62
#1  0x00007ffff753b844 in ??? () at /usr/lib/libgio-2.0.so.0
#2  0x00007ffff7544334 in ??? () at /usr/lib/libgio-2.0.so.0
#3  0x00007ffff74d91ac in ??? () at /usr/lib/libgio-2.0.so.0
#4  0x00007ffff74dd445 in ??? () at /usr/lib/libgio-2.0.so.0
#5  0x00007ffff753aa28 in ??? () at /usr/lib/libgio-2.0.so.0
#6  0x00007ffff74d91ac in ??? () at /usr/lib/libgio-2.0.so.0
#7  0x00007ffff74d91f5 in ??? () at /usr/lib/libgio-2.0.so.0
#8  0x00007ffff7341ab9 in ??? () at /usr/lib/libglib-2.0.so.0
#9  0x00007ffff73a39e7 in ??? () at /usr/lib/libglib-2.0.so.0
#10 0x00007ffff7340fc5 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#11 0x00007ffff7510c66 in g_application_run () at /usr/lib/libgio-2.0.so.0
#12 0x0000555555556d34 in main (argc=1, argv=0x7fffffffe468) at ../src/sfwbar.c:199
(gdb) p item->watcher->iface
Cannot access memory at address 0x555000f76389
```

**Comment by LBCrion** [comment]
Interesting.  It looks like this sequence manages to kill the sni watcher.
I am a bit surprised the watcher is running at all,  since I would expect
waybar's watcher to be active.
I think I figured out what caused this,  but I can't test it,  as I'm
travelling.  Can you try the latest git version and see if the problem
still exists?

**Comment by tokyo4j** [comment]
Unfortunately sfwbar-git reinstalled from AUR still sometimes segfaults.

Sorry I forgot that the nested `labwc` executes `~/.config/labwc/autostart` which runs waybar and nm-applet.
I'll investigate the condition triggering the segfault.

**Comment by LBCrion** [comment]
Does it still segfault with the same stacktrace?
Also,  I want to make sure I get the setup correct: you have one instance
of labwc with waybar and nm-applet running,  you then run sfwbar and then
start another nested session of labwc with another instance of both waybar
and nm-applet?

**Comment by tokyo4j** [comment]
> Does it still segfault with the same stacktrace?

Here's the stacktrace:
```
Thread 1 "sfwbar" received signal SIGSEGV, Segmentation fault.
0x00007ffff7262beb in ?? () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff7262beb in ??? () at /usr/lib/libc.so.6
#1  0x00007ffff7f94dfc in sni_watcher_item_add
    (watcher=0x5555556fcca0, uid=0x555555a479e0 ":1.175/StatusNotifierItem")
    at ../src/sni.c:80
#2  0x00007ffff7f95406 in sni_watcher_register_cb
    (con=0x555555592610, name=0x5555556a26d0 "org.kde.StatusNotifierWatcher", watcher=0x5555556fcca0) at ../src/sni.c:202
#3  0x00007ffff753b844 in ??? () at /usr/lib/libgio-2.0.so.0
#4  0x00007ffff7543fea in ??? () at /usr/lib/libgio-2.0.so.0
#5  0x00007ffff7533379 in ??? () at /usr/lib/libgio-2.0.so.0
#6  0x00007ffff7341ab9 in ??? () at /usr/lib/libglib-2.0.so.0
#7  0x00007ffff73a39e7 in ??? () at /usr/lib/libglib-2.0.so.0
#8  0x00007ffff7340fc5 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#9  0x00007ffff7510c66 in g_application_run () at /usr/lib/libgio-2.0.so.0
#10 0x0000555555556d34 in main (argc=1, argv=0x7fffffffe5f8) at ../src/sfwbar.c:199
(gdb) f 1
#1  0x00007ffff7f94dfc in sni_watcher_item_add (watcher=0x5555556fcca0,
    uid=0x555555a479e0 ":1.175/StatusNotifierItem") at ../src/sni.c:80
80	    if(!g_strcmp0(((struct watcher_item *)iter->data)->uid, uid))
(gdb) p ((struct watcher_item *)iter->data)->uid
$1 = (gchar *) 0x1 <error: Cannot access memory at address 0x1>
(gdb)
```

> Also,  I want to make sure I get the setup correct: you have one instance of labwc with waybar and nm-applet running,  you then run sfwbar and then start another nested session of labwc with another instance of both waybar and nm-applet?

Yes. I usually use waybar, but I additionally launched sfwbar to test labwc/labwc#2055 which shows taskbar icon for nested labwc window.

**Comment by LBCrion** [comment]
Ok,  this looks like a different issue and appears to be related to a hack
that allowed a watcher to steal item inventory from the host when an
external watcher went away.

I disabled this functionality in git. Can you try updating sfwbar-git again
and see if it helps?

**Comment by tokyo4j** [comment]
I updated sfwbar-git and the issue went away!
Thank you for your quick response!

**Comment by LBCrion** [comment]
Thank you for reporting and testing this. This is probably the best fuzzing
test for the sni implementation one can come up with ;)
