### ISSUE TITLE
clicking on a systray icon does not revel popup menu

### ISSUE THREAD

**Issue by keshto** [LBCrion/sfwbar#22]
When using waybar and using pasystray one can click on the systray icon and get a menu.
In sfwbar the icon is shown but clicking on it does not show a menu.

**Comment by LBCrion** [comment]
Hi keshto, which version of sfwbar are you using please? I see the pasystray menu working with both 1.0_beta4 and with the current git.

**Comment by LBCrion** [comment]
Can you please try the latest git version by running the following command:

sfwbar -d 2>&1 | grep sni

Then run pasystray and try left clicking on the icon. If the menu doesn't come up, can you please post the output you got from sfwbar command above?

**Comment by keshto** [comment]
```
$ sfwbar -d 2>&1 | grep sni
11:00:15.82 sni host org.kde.StatusNotifierHost-4630: found watcher org.kde.StatusNotifierWatcher (:1.71)
11:00:15.82 sni host org.freedesktop.StatusNotifierHost-4630: found watcher org.freedesktop.StatusNotifierWatcher (:1.71)
11:00:15.82 sni watcher org.kde.StatusNotifierWatcher: registered host org.kde.StatusNotifierHost-4630
11:00:15.82 sni watcher org.freedesktop.StatusNotifierWatcher: registered host org.freedesktop.StatusNotifierHost-4630
11:00:25.63 sni: host org.kde.StatusNotifierHost-4630: item registered: :1.73 /org/ayatana/NotificationItem/pasystray
11:00:25.63 sni :1.73: property Category = Hardware
11:00:25.63 sni :1.73: property Id = pasystray
11:00:25.63 sni :1.73: property Title = pasystray
11:00:25.63 sni :1.73: property Status = Active
11:00:25.63 sni :1.73: property IconName = pasystray
11:00:25.64 sni :1.73: property AttentionIconName =
11:00:25.64 sni :1.73: property IconThemePath =
11:00:25.64 sni :1.73: property Menu = /org/ayatana/NotificationItem/pasystray/Menu
11:00:33.77 sni :1.73: button: 1
11:00:33.77 sni :1.73: requesting menu
11:00:33.78 sni :1.73: menu: (uint32 2, (0, {'children-display': <'submenu'>}, [<(2, {'children-display': <'submenu'>, 'label': <'Default _Server'>}, [<(3, {'enabled': <false>, 'label': <'none'>}, @av [])>])>, <(4, {'children-display': <'submenu'>, 'label': <'Default S_ink'>}, [<(5, {'enabled': <false>, 'label': <'none'>}, @av [])>])>, <(6, {'children-display': <'submenu'>, 'label': <'Default S_ource'>}, [<(7, {'enabled': <false>, 'label': <'none'>}, @av [])>])>, <(8, {'children-display': <'submenu'>, 'label': <'Playback S_treams'>}, [<(9, {'enabled': <false>, 'label': <'none'>}, @av [])>])>, <(10, {'children-display': <'submenu'>, 'label': <'Recording Stre_ams'>}, [<(11, {'enabled': <false>, 'label': <'none'>}, @av [])>])>, <(12, {'children-display': <'submenu'>, 'label': <'_Modules'>}, [<(13, {'enabled': <false>, 'label': <'none'>}, @av [])>])>, <(14, {'enabled': <true>, 'type': <'separator'>}, @av [])>, <(15, {'enabled': <false>, 'label': <'_Manager...'>}, @av [])>, <(16, {'enabled': <false>, 'label': <'Volume _Control...'>}, @av [])>, <(17, {'enabled': <false>, 'label': <'Volume Meter (_Playback)...'>}, @av [])>, <(18, {'enabled': <false>, 'label': <'Volume Meter (_Recording)...'>}, @av [])>, <(19, {'enabled': <false>, 'label': <'Con_figure Local Sound Server...'>}, @av [])>, <(20, {'enabled': <true>, 'type': <'separator'>}, @av [])>, <(21, {'children-display': <'submenu'>, 'label': <'More...'>}, [<(22, {'label': <'Terminate server'>}, @av [])>])>, <(23, {'label': <'About'>}, @av [])>, <(24, {'label': <'Quit'>}, @av [])>]))
11:00:40.34 sni menu call: 21 ((null)) :1.73
11:00:40.84 sni menu call: 21 ((null)) :1.73
11:00:42.64 sni menu call: 21 ((null)) :1.73
11:00:43.39 sni menu call: 12 ((null)) :1.73
11:00:43.47 sni menu call: 10 ((null)) :1.73
11:00:43.52 sni menu call: 8 ((null)) :1.73
11:00:43.57 sni menu call: 6 ((null)) :1.73
11:00:43.66 sni menu call: 4 ((null)) :1.73
11:00:43.92 sni menu call: 6 ((null)) :1.73
11:00:44.00 sni menu call: 8 ((null)) :1.73
11:00:44.05 sni menu call: 10 ((null)) :1.73
11:00:44.16 sni menu call: 12 ((null)) :1.73
11:00:49.02 sni menu call: 21 ((null)) :1.73
11:00:49.86 sni menu call: 21 ((null)) :1.73
11:00:50.03 sni menu call: 21 ((null)) :1.73
11:00:50.38 sni menu call: 21 ((null)) :1.73
11:00:51.78 sni menu call: 21 ((null)) :1.73
11:00:54.31 sni :1.73: button: 3
11:00:54.31 sni: calling ContextMenu on :1.73 at ( 1486, 1119 )
```

**Comment by keshto** [comment]
For the above, the menu did not appear. moving my mouse around the general area is what generated the `sni menu call: X` output. The below button 3 is the right mouse button click. Below is me using the latest git commit.
`
$ git log
commit 981a7a6d02cf73f838a58def90d78b9cc0582e33
`

**Comment by LBCrion** [comment]
Did you click on various spots to get 'sni menu call' messages? These
should normally appear when you click on menu items.

Do you have a layer set in your configuration with SetLayer?

**Comment by keshto** [comment]
I just retried, to make sure I was not clicking anything and indeed did not click anything to generate those messages. I am running sfwbar after doing a `sudo ninja -C build install` with no changes or local config.

**Comment by keshto** [comment]
I copied over the default config and ran it with the default `overlay` and `top` layer both yielding the same result.

**Comment by LBCrion** [comment]
Ok. The 'sni menu call's are generated when you hover over a submenu in
pasystray menu. So, it looks like the menu is there, but is invisible for
some reason. What version of sway (or another compositor) are you using?
And what version of gtk+? Also, do you have any programs running to set
your background? And do you have any windows in the area immediately above
the system tray that may potentially be covering the menu?
(sorry about a barrage of questions, but I want to cover all possible
reasons for the invisible menu)

**Comment by keshto** [comment]
If you want to jump on a video call I can share my sceen if that makes things easier. 
Looking thought the config it looks like there is supposed to be a menu for the tasklist bar too? (which I don't see, on right click)
>  What version of sway (or another compositor) are you using? 

I tried both on labwc and wayfire compositors. Waybar on same compositors shows menu as expected.
> And what version of gtk+?


```
Package: libgtk-3-0
Version: 3.24.31-1

Package: libgtk-4-1
Version: 4.4.1+ds1-3
```

>Also, do you have any programs running to set your background? And do you have any windows in the area immediately above the system tray that may potentially be covering the menu?

No, just a terminal to launch sfwbar and pasystray. No, keep teminal window above.

**Comment by LBCrion** [comment]
Ok, I managed to reproduce it with labwc. Now I just need to figure out
what causes it.

**Comment by LBCrion** [comment]
Ok, this looks to be an issue with how labwc/wlroots-0.15 handle layer
shell windows on overlay layer. For some reason if such a window pops up a
gtk menu (which is a wayland subsurface), labwc doesn't render it.
I wasn't able to reproduce it with wayfire so far, but this could be due to
the fact that wayfire on gentoo only builds against wlroots-0.14.

A workaround for now would be to put sfwbar on a different layer, i.e top
layer. To do this, copy system config from /usr/share/sfwbar/sfwbar.config
to ~/.config/sfwbar/sfwbar.config and change Function("SfwBarInit") to
include a line SetLayer "top"

With this config change, menus pop up for me.

You mention that you changed SetLayer in the config to top and it made no
difference for you, did you uncomment the SetLayer line when you changed
it? (remove # at the start)

**Comment by keshto** [comment]
Solved https://github.com/labwc/labwc/issues/239. Thanks for helping out there @LBCrion :heart: 

Side note: I don't know why it was not working for me with both wayfire and labwc I assume it was something I was doing with wlroots, because when I recompiled it started to work there. Glad at least we found something :)
