### ISSUE TITLE
[Question] Will issue #111 be possible on labwc?

### ISSUE THREAD

**Issue by 01micko** [LBCrion/sfwbar#221]
#111

Of course this is if/when https://github.com/labwc/labwc/pull/2030 merged?

Would be a very handy feature for BunsenLabs who use a vertical Tint2 panel. 

![Screenshot of BunsenLabs Boron desktop](https://www.debugpoint.com/wp-content/uploads/2024/01/bunsenlabs-Linux-22boron22-based-on-Debian-12.jpg)

**Comment by LBCrion** [comment]
Alas,  this won't work yet,  as we'll still be missing the toplevel-
workspace mapping information and control.  See
https://github.com/labwc/labwc/pull/2030#issuecomment-2275438204

**Comment by 01micko** [comment]
I thought that may be the case. So out of scope for now. I'll close.

Thanks!

**Comment by LBCrion** [comment]
BTW, if the necessary protocols do get implemented,  this feature won't
require any extra effort to implement. It should start working pretty much
automatically.

**Comment by 01micko** [comment]
@knm100 that is in X11/openbox/Tint2

It is jgmenu by @johanmalm . It runs in wayland via Xwayland but is a bit clunky with that method so not recommended.

**Comment by knm100** [comment]
Thanks for the reply. You're right.
