### ISSUE TITLE
Skype's tray icon fallsback instead of getting displayed

### ISSUE THREAD

**Issue by orfeasxyz** [LBCrion/sfwbar#229]
After upgrading from latest release to master I've noticed that Skype's icon is broken. Old version is up and newest is down.
![image](https://github.com/user-attachments/assets/857edf90-e943-4e56-a4e6-a6fa945df51e)

After building testing different commits, the patch that the issue first appeared is this one  https://github.com/LBCrion/sfwbar/commit/f95b6b8b164c79b5a1f4267def1293b77f9cf20d

**Comment by LBCrion** [comment]
This is indeed a regression. Should be fixed in the latest git version.

**Comment by orfeasxyz** [comment]
Fixed 👍
