### ISSUE TITLE
Some taskbar icons show the default icon

### ISSUE THREAD

**Issue by 01micko** [LBCrion/sfwbar#23]
Using this in `labwc` in Puppy Linux.

I can't figure out why some apps display an icon (firefox, geany, celluloid and some others are fine) and many don't. Most have icons in the icon themes I use and many have icons in the 'hicolor' theme (as they should). But that doesn't seem to matter as gimp doesn't show, GParted doesn't show and others.

I'm on the latest git version and not using many features, just icons taskbar and clock, all with tooltips and actions and a bit of css.

BTW, the default icon is pretty crappy, maybe you could find a nicer one and this issue wouldn't be so bothersome!

Thanks, and I like this bar, `foreign-toplevel` implementation is good and user friendly.

Got it looking a bit like JWM :laughing: 

![20220228_17h13m57s_grim](https://user-images.githubusercontent.com/1019119/155940311-eeb3c4d0-9c54-4c6c-90c8-67d2affd9457.png)

**Comment by Consolatis** [comment]
Here is another (likely more hacky) implementation for getting the icon: https://github.com/mate-desktop/mate-panel/pull/1275/files
Maybe something similar could be used as fallback if `g_desktop_app_info_search()` fails to find an icon.

In another project I am using:
- `g_desktop_app_info_new("{app_id}.desktop")`
- `g_desktop_app_info_new("{lower(app_id)}.desktop")`
and fall back to `gtk_image_set_from_icon_name()` directly using `app_id` and `lower(app_id)`

**Comment by LBCrion** [comment]
Ok, it looks like the case of gimp is simple - we need to check the lowercase version of app_id to match the icon (as Consolatis pointed out). This should be taken care of in the latest git version.

Gparted is a trickier case, the actual Gparted executable is gpartedbin and gtk by default sets app_id to the basename of the progam, so the app_id is gpartedbin. There is no clean way to map this to the correct icon name. The proper fix for this would for Gparted to set the app_id to 'gparted' using g_set_prgname (or gtkmm equivalent). Barring that, you can use a workaround and symlink /usr/share/icons/hicolor/scalable/apps/gparted.svg to $HOME/.config/sfwbar/gpartedbin.svg for per user config or to /usr/share/sfwbar/gpartedbin.svg for systemwide fix.

As for the missing image icon, you can override it by placing an icon of your choice into $HOME/.config/sfwbar/icons/misc/missing.svg (and if you have a nicer icon in mind available without redistribution restrictions, I'd be happy to update the default for sfwbar - ux design isn't my strong suit).

**Comment by LBCrion** [comment]
Ok, I found a bug that broke gimp after the last fix.  Would you mind
trying it again with the latest git?

In general,  I think we should symlink only as a last resort.  Most
programs should be better behaved.  I'll try to check examples you
mentioned and see if there's anything I can improve for these cases.

**Comment by 01micko** [comment]
Initial test I removed symlinks  gimp, transmission  and vivaldi work! :-)

PCmanfm now works.

As far as I can tell, all programs installed that are compiled from source, either by me or upstream,  work.
 
Only generic Puppy apps (mostly scripts) don't work. Thes are gtkdialog or Xdialog and the generic icons for those are missing.

I think this is solved. Only icons that don't show I think are my problems, and I'll fix them.

Thanks a lot!

**Comment by LBCrion** [comment]
Good to hear icons are now working.  Does GtkDialog allow setting app_id
from the script? That would let you set different icons for individual
dialogs.

**Comment by 01micko** [comment]
Does GtkDialog allow setting app_id
from the script?

No, but it is likely something we can patch in.

**Comment by 01micko** [comment]
![20220303_20h44m03s_grim](https://user-images.githubusercontent.com/1019119/156549349-b4956853-03be-4510-9e25-058e6034ec16.jpeg)


All icons working. I did try a new 'missing' icon but it's too complex. Would be a good application icon, not that one is needed.

For the 'missing.svg' are you willing to accept some contrast? In a dark theme these dark gray icons would be  difficult to see. I'm thinking just a plain gray circle with a fairly painless pastel color (maybe with some transparency) or something filling the circle.

**Comment by LBCrion** [comment]
That sounds good. I think so long as the icon scales well and works as a
missing image icon for different scenarios (I.e. taskbar item,  switcher
item,  tray, user widgets),  it would be an improvement.

**Comment by 01micko** [comment]
I've fixed (pr https://github.com/puppylinux-woof-CE/gtkdialog/pull/139) icons for our `gtkdialog` program and a few other things at my end and the 'missing' icon rarely shows, so no real need to change it.

I've zipped some alternate icons (just color change - lighter for a dark gtk theme) but I don't know if/how you would want to implement them.

[sfwbar-icons.zip](https://github.com/LBCrion/sfwbar/files/8310503/sfwbar-icons.zip)

My bar now - 

![20220320_12h23m36s_grim](https://user-images.githubusercontent.com/1019119/159145384-131e376d-af4e-47c5-82cd-0ef1eb13530b.png)

Thanks!

**Comment by LBCrion** [comment]
Nice.  GtkDialog with icons makes for a nice interface.

For icons, I think for single color icons,  we can just add a setting to
specify the icon color. I added a css property -ScaleImage-color for images
in the current git, which allows specifying a color to draw the icon in.
For example,  you can specify -ScaleImage-color: #000000; for a light theme
and - ScaleImage-color: #ffffff; for a dark theme.

Do you think this would do the trick for themimg icons?

**Comment by 01micko** [comment]
That's a good idea.

There's something else I want to try with CSS, but I haven't succeeded yet. When I get time I'll try again and if I can't get it to work with the latest revision then I'll open an issue.

Thanks!

**Comment by 01micko** [comment]
They are all sfwbar widgets. See #32 for some of the development discussion.

**Comment by LBCrion** [comment]
@01micko, you know you'll need to post those widgets somewhere. I think sfwbar could really do with some spruced up screenshots and default configs. My '90s designs don't appeal to many modern users.

**Comment by 01micko** [comment]
> @01micko, you know you'll need to post those widgets somewhere. I think sfwbar could really do with some spruced up screenshots and default configs. My '90s designs don't appeal to many modern users.

Yes! But I do have to do some minor refactoring now that I know I can `include` widgets in widgets.

The reasons I want to do this are:
- it will be easier and cleaner for me to migrate to a single `sfwbar.config` for my bar and launcher
- it will make it quite simple for anyone to make a configuration app written in any language they like such as pure `C`, shell, `py-gtk`, `gtkdialog` (which naturally I have done) or whatever, either GUI or CLI 

I'll have a think about where to post them.

**Comment by stefonarch** [comment]
Stumbled upon this, use the taskbar in arch and in debian 12, and in the latter thunderbird icon is not found and replaced by Sfw icon. Both have git master.

**Comment by LBCrion** [comment]
This sounds like an icon is missing on debian. Can you please check output
of "sfwbar -d -g app_id" to check the name of the thunderbird icon?

Usually an icon file with that name would be installed into
/usr/share/icons/hicolor/scalable/apps

Can you check if the icon exists on arch and/or debian?

**Comment by stefonarch** [comment]
Under arch it looks like sfwbar displays the "papirus" theme icon (icon set in lxqt-config-appearance).
```
$ sfwbar -d -g thunderbird
18:07:38,92 app_id: 'thunderbird', title 'Posta in arrivo - Cartelle locali - Mozilla Thunderbird'
18:07:39,09 image: thunderbird @ 0
18:07:39,11 image: thunderbird @ 28
18:07:39,14 image: thunderbird @ 28

```
```
$ locate thunderbird.svg
/home/stef/.local/share/icons/Plataro/apps/scalable/thunderbird.svg
/usr/share/icons/Papirus/16x16/apps/thunderbird.svg
/usr/share/icons/Papirus/22x22/apps/thunderbird.svg
/usr/share/icons/Papirus/24x24/apps/thunderbird.svg
/usr/share/icons/Papirus/32x32/apps/thunderbird.svg
/usr/share/icons/Papirus/48x48/apps/thunderbird.svg
/usr/share/icons/Papirus/64x64/apps/thunderbird.svg
/usr/share/icons/Plataro/apps/scalable/thunderbird.svg
```
Now checking debian.

**Comment by stefonarch** [comment]
```
$ sfwbar -d -g thunderbird
18:17:43,63 app_id: 'thunderbird-default', title 'Posta in arrivo - Cartelle locali - Mozilla Thunderbird'
18:17:43,86 image: thunderbird-default @ 28 x 28
```

Copying the icon in apps/48x48/  thunderbird.svg to thunderbird-default.svg and restarting sfwbar works.

**Comment by stefonarch** [comment]
Another client I noticed today is qpdfview (all happens on labwc):

sfwbar -d -g qpdfview
```
18:49:32,00 app_id: 'qpdfview.local.qpdfview', title 'Pagina001 - qpdfview'
18:49:32,19 image: qpdfview.local.qpdfview @ 0
18:49:32,22 image: qpdfview.local.qpdfview @ 28
18:49:32,24 image: qpdfview.local.qpdfview @ 28
```

**Comment by LBCrion** [comment]
With thunderbird, it looks like the program doesn't set app id explicitly, but rather inherits it from the name of the executable. It works fine, so long as the executable is named `thunderbird`, but fails once it's renamed into `thunderbird-default`. You can work around that by symlinking the  icon as you did, but ideally thunderbird should set a consistent app id, independent from the name of the executable. It may be worth raising it with thunderbird devs.

Qpdfview is a bit more interesting. It seems to set app id to a full application name. Usually only the last component should be use as an appid (so application `qpdfview.local.qpdfview` should have app id of `qpdfvew`). Again, a correct fix should probably be on the application side, but it may be worth adding a workaround to sfwbar for such occurrences.

**Comment by LBCrion** [comment]
I added the workaround to check for the suffix of an appid if the main lookup fails. Can you please check if this helps with qpdfview?

**Comment by stefonarch** [comment]
Can confirm, it works fine for qpdfview now, thanks. 
I found out that symlinking didn't work actually, it looked working because I restarted sfwbar from the command line inside the icon folder, at next login it was without icon again.

**Comment by LBCrion** [comment]
Where did you symlink the icon to? If you place symlink into
~/.config/sfwbar/ or /usr/share/sfwbar/ it should work.

**Comment by stefonarch** [comment]
I symlinked in severall icon folders. 
`ln -s /usr/share/icons/Papirus/48x48/apps/thunderbird.svg thunderbird-default.svg` works, thanks!

**Comment by stefonarch** [comment]
Latest entries:
![screen_area_ven_15:52:42_](https://github.com/LBCrion/sfwbar/assets/10681413/be5225f6-5715-4bce-893e-bb780374c4cb)

**Comment by stefonarch** [comment]
> I added the workaround to check for the suffix of an appid if the main lookup fails. Can you please check if this helps with qpdfview?

Just saw that under debian qpdfview is still without icon, it needs `qpdfview.local.qpdfview.svg` in `~/.config/sfwbar` ...

**Comment by LBCrion** [comment]
Can you check what appid it has and whether there is a .desktop file for
it? (and if there is, what Icon line does it have)?

**Comment by stefonarch** [comment]
Appid is `qpdfview.local.qpdfview` on debian, desktop file:


 /usr/share/applications/qpdfview.desktop:

`Icon=qpdfview`

**Comment by LBCrion** [comment]
I just installed qpdfview and sfwbar (current git version) picked up a correct icon. It tried to load `qpdfview.local.qpdfview` first and then fell back to `qpdfview`

**Comment by stefonarch** [comment]
Sorry for the delay, I didn't have access to the debian machine in the mean time, will recheck. But on arch Virtualbox are iconless too I see.
```

$ lswt
app-id:                title:
"VirtualBox Manager"   "Oracle VM VirtualBox Gestore"
```

**Comment by LBCrion** [comment]
Is there a "VirtualBox Machine" icon or desktop entry?

**Comment by stefonarch** [comment]
The icon here is ` /usr/share/icons/hicolor/40x40/mimetypes/virtualbox.png`

![screen_area_lun_09:06:52_](https://github.com/LBCrion/sfwbar/assets/10681413/4df6809f-1327-45a1-a359-14875086847a)

**Comment by LBCrion** [comment]
Strictly speaking, the icon name should match the appid of the program, so it should be `VirtualBox Machine.png`. That said, using space a separator may be a pattern we'll see more than once. I added a fallback mechanism to check the first word of an appid as a desktop entry / icon name candidate. Can you please check if this helps in this case?

**Comment by Consolatis** [comment]
> Edit: "VirtualBox Machine" has the icon.

It would be interesting to know why that worked before. Is there some *VirtualBox Machine.desktop` file somewhere?
I never heard of any kind of try-to-skip-spaces-in-app_id thing before.
(Also that app_id is \*bad\*, is it running via xwayland by chance and thus is actually the `WM_CLASS` ?)

**Comment by stefonarch** [comment]
Checked know, yes, both the machines and the manager run on xwayland. The only `.destop`file is  `virtualbox.desktop`.

>I added a fallback mechanism to check the first word of an appid as a desktop entry / icon name candidate. Can you please check if this helps in this case?

Installed from AUR sfw-git - no change.

**Comment by Consolatis** [comment]
Another option could be to find all `.desktop` files with `StartupWMClass` matching the app_id as a final resort.
@stefonarch could you post the contents of `virtualbox.desktop`?

**Comment by stefonarch** [comment]
```
[Desktop Entry]
Version=1.0
Name=Oracle VM VirtualBox
GenericName=Virtualization Software
GenericName[de]=Virtualisierung Software
GenericName[ru]=
Type=Application
Exec=VirtualBox %U
TryExec=VirtualBox
Keywords=virtualization;
Keywords[de]=Virtualisierung;
Keywords[ru]=виртуализация;
MimeType=application/x-virtualbox-vbox;application/x-virtualbox-vbox-extpack;application/x-virtualbox-ovf;application/x-virtualbox-ova;
Icon=virtualbox
Categories=Emulator;System;
Actions=Manager;
StartupWMClass=VirtualBox Manager
Comment=Run several virtual systems on a single host computer
Comment[de]=Mehrere virtuelle Maschinen auf einem einzigen Rechner ausführen
Comment[it]=Esegui più macchine virtuali su un singolo computer
Comment[ko]=가상 머신
Comment[pl]=Uruchamianie wielu systemów wirtualnych na jednym komputerze gospodarza
Comment[ru]=Запуск нескольких виртуальных машин на одном компьютере
Comment[sv]=Kör flera virtuella system på en enda värddator

[Desktop Action Manager]
Exec=VirtualBox
Name=Open VM Manager
Name[de]=VM Manager öffnen
```

**Comment by LBCrion** [comment]
It looks like we can lookup the icon from the StartupWMClass, but it won't
be trivial,  since we need to either iterate through all .desktop entries
(which would be rather expensive performance-wise) or keep track of all the
mappings in memory.

**Comment by stefonarch** [comment]
Another one is meteo-qt: app-id `meteo-qt.python3`.

**Comment by LBCrion** [comment]
Does it have a desktop entry? If it does, would you mind posting it?

**Comment by stefonarch** [comment]
```
[Desktop Entry]
Type=Application
Name=Meteo-qt
GenericName=Weather status information
Comment=A Qt system tray application for weather information
Exec=meteo-qt
Icon=weather-few-clouds
Terminal=false
StartupNotify=false
Categories=Qt;LXQt;Network;
X-DBUS-ServiceName=meteo-qt

```

**Comment by LBCrion** [comment]
And is the filename of this file meteo-qt.dedktop or
meteo-qt.python3.desktop?

**Comment by stefonarch** [comment]
`meteo-qt.desktop `

**Comment by Consolatis** [comment]
At some point I wonder if it makes sense to add more and more workarounds for the app_id -> .desktop / icon file lookups, at least for wayland native applications. Maybe the applications should just set a proper app_id. Xwayland applications are another topic though.

**Comment by LBCrion** [comment]
Meteo-qt looks like a case of an application reporting a bogus app_id. I
suspect it's based on the name of the executable rather than set by an
application to a specific value. Some distributions may change the name of
the executable and there is no way to catch these cases consistently. For
cases like this I would suggest either using an icon symlink (i.e. symlink
meteo-qt.svg to meteo-qt.python3.svg) or use MapAppId configuration option
to map app_id from a window title (if it's consistently identifiable).

**Comment by LBCrion** [comment]
It looks like glib/gio GDesktopAppInfo by default performs lookup of an app name (app_id in our case) on Exec, GenericName, Keywords, Name and XGnomeFullName, but not StartupWMClass. This means that in order to map on StartupWMClass, we'll need to do parallel tracking with GDesktopAppInfo.

I guess we could get GDesktopAppMonitor to monitor any changes in desktop files and rebuild an index of GDesktopAppInfo objects keyed to StartupWmClass. 

Gio documentation mentions that monitoring the app info database for changes is expensive, so I think I'll need to run some check on performance cost this will incur.

**Comment by LBCrion** [comment]
I added a lookup on StartupWMClass property of desktop entries now. @stefonarch, can you please check if this helps with VirtualBox?

**Comment by stefonarch** [comment]
Installad AUR git package, no change with Vbox Manager unfortunately.

**Comment by LBCrion** [comment]
Hmm, I just installed virtualbox on an arch system and ran it together with sfwbar. Here's what I see:
![20240224_08h01m40s_grim](https://github.com/LBCrion/sfwbar/assets/76477076/173a6fca-517a-46af-900c-78045032bf15)

**Comment by stefonarch** [comment]
No idea, reinstalled AUR git package, here:

![screen_area_sab_09:40:12_](https://github.com/LBCrion/sfwbar/assets/10681413/c62acbcf-7580-4ca9-be10-ed1c71364f9f)

**Comment by LBCrion** [comment]
Can you try running `sfwbar -d -g WorkspaceActivate` to see if you get any output (just to check if you're running the latest version).

**Comment by stefonarch** [comment]
It opens sfwbar without message.

**Comment by LBCrion** [comment]
This would indicate that the version of sfwbar you're testing isn't the
latest git version. Maybe you have multiple versions installed? Maybe check
where sfwbar-git package installs the executable and see if `which sfwbar`
points at the same file?

**Comment by stefonarch** [comment]
My fault, `/usr/local/bin/` striked again, should stop to install there. All fine with icons, sorry ;)

**Comment by LBCrion** [comment]
Great! I was getting worried there was some unexpected glib/gio behavior in play :)

**Comment by marcusbritanicus** [comment]
> I added the workaround to check for the suffix of an appid if the main lookup fails. Can you please check if this helps with qpdfview?

I may be a little late to this discussion. I just opened an issue today on launchpad regarding qpdfview. The author has replied stating that they have a fix, but are unable to push it due to some ssh connectivity issues. So, by the next release, issue with qpdfview should be gone. :slightly_smiling_face:
