### ISSUE TITLE
always output Gtk-WARNING about Expected semicolon 

### ISSUE THREAD

**Issue by knm100** [LBCrion/sfwbar#235]
Could someone help to have a look at my sfwbar.config.  why it always caused following warning.
[knm@archlinux ~]$ sfwbar

(sfwbar:3455): Gtk-WARNING **: 14:55:57.828: Theme parsing error: <data>:127:0: Expected semicolon

(sfwbar:3455): Gtk-WARNING **: 14:55:57.828: Theme parsing error: <data>:128:0: Expected semicolon

(sfwbar:3455): Gtk-WARNING **: 14:55:57.828: Theme parsing error: <data>:129:0: Expected semicolon

(sfwbar:3455): Gtk-WARNING **: 14:55:57.828: Theme parsing error: <data>:130:0: Expected semicolon

(sfwbar:3455): Gtk-WARNING **: 14:55:57.828: Theme parsing error: <data>:139:0: Expected semicolon
^C
[sfwbar.config.txt](https://github.com/user-attachments/files/17220938/sfwbar.config.txt)

**Comment by LBCrion** [comment]
This is due to '#' style comments in the CSS section. CSS doesn't support
'#' comments, since '#' is used for element name identification. You can
use /* */ style comments instead to avoid these warnings.

**Comment by knm100** [comment]
Thank you very much!
