### ISSUE TITLE
Is it possible for the start menu to be localized?

### ISSUE THREAD

**Issue by knm100** [LBCrion/sfwbar#236]
Changed startmenu.source as before, but it doesn't work like before.

**Comment by LBCrion** [comment]
I just added locale tracking the latest git version. Can you please check
if it works now?

**Comment by knm100** [comment]
It works now except the following menu
![swappy-20241004-103318](https://github.com/user-attachments/assets/eb227c15-5b81-4e91-92af-928fececb391)

**Comment by LBCrion** [comment]
Can you try again please? I just added support for localised category names
(if the directory entry files are available on the system).

**Comment by knm100** [comment]
It worked, but there are still some category that are not localized
![swappy-20241005-090423](https://github.com/user-attachments/assets/2a20a89f-d650-45d6-abce-346d2724edf8)

Is it possible to let the user translate it in startmenu.widget?

**Comment by LBCrion** [comment]
The translations are taken from desktop directory entries present on your
system. Sfwbar checks desktop-directories subdirectory in all XDG data dirs
(user and system). It checks all files in these directories and matches the
"Name" parameter against the freedesktop menu category names. Once it finds
a matching "Name" it checks if a Name[] property id present for the
selected locale. If found, it replaces the default menu category name with
this value.
So, if the categories remain untranslated, either the desktop directory
files for these categories are missing or they don't have a translation for
your locale.

**Comment by knm100** [comment]
Thank you!    so there is no way for users to translate directories that are not localized.

**Comment by knm100** [comment]
There was the lxqt-panel in my arch, which had all the directory files in `/usr/share/desktop-directories/` and all of them have been fully translated.   
I copied also all the directory file of nwg-menu to  `$HOME/.local/share/ ` (Started nwg-menu directly, and the menus of nwg-menu were fully localized)
but startmenu still was changed.    maybe we should provide working directory files directly, as nwg-menu did. In this way, startmenu will have a good user experience.

**Comment by LBCrion** [comment]
Supplying fallback files could be an option. We would need a set of license
compatible files with good translations. But I don't see any issue
including them with a default install.

**Comment by knm100** [comment]
It could probably be modified directly based on the directory file for nwg-menu, which is distributed under the MIT license.

**Comment by knm100** [comment]
Any plans to make it happen?

**Comment by LBCrion** [comment]
I 'borrowed' desktop-directories files from gnome and kde (both of which
are GPL-3 compatible). These are now installed into
/use/share/sfwbar/desktop-directories and are only used if a directory file
for a category isn't found in the system dirs.

**Comment by knm100** [comment]
Great Job, Now I have an perfect startmenu.  thank your very much!
