### ISSUE TITLE
Make the icon appear to levitating on the panel by creating a shadow underneath it

### ISSUE THREAD

**Issue by knm100** [LBCrion/sfwbar#239]
Can I  used` -gtk-icon-shadow ` to creat a shadow underneath icon for the levitation effect?

**Comment by LBCrion** [comment]
We don't use gtkicon objects, but it should be possible to add this effect
to ScaleImage widgets sfwbar uses. Although, I'll need to research a bit
how drop shadows should be sized vis-a-vis padding and margin first.

**Comment by knm100** [comment]
Yes,  the icons is smaller than windows,  too big shadows is Unrealistic， too small is ineffective.

**Comment by LBCrion** [comment]
I added support for drop shadows in the latest git, can you please check if this does what you're looking for? The shadows are controlled via CSS properties:
`-ScaleImage-shadow-radius: 2;` sets radius (2px in this example)
`-ScaleImage-shadow-x-offset: 4;` sets x offset vs the icon (4px in this example)
`-ScaleImage-shadow-y-offset: 4;` sets y offset vs the icon (4px in this example)
`-ScaleImage-shadow-color: Rgba(0,0,0,0.8);` sets the color of the shadow
`-ScaleImage-shadow-clip: true;` controls whether the shadow is clipped to the padding box, the default is true, if you set it to false, the shadow will spill over the border and the margins on the widget.

**Comment by knm100** [comment]
It didn't work for me
![swappy-20241009-193552](https://github.com/user-attachments/assets/5b52bcf5-d5f5-47ef-a9bb-5e7913a882b1)
[sfwbar.config.txt](https://github.com/user-attachments/files/17307498/sfwbar.config.txt)

**Comment by LBCrion** [comment]
Are you sure it's the latest git version? I just tried your config and I
see shadows (although they need some aligning).

**Comment by knm100** [comment]
the sfwbar ver  that was installed in my arch  is  r1577.2d71ba7.  it should be the latest rev untill r1578.eed9600
![swappy-20241010-104307](https://github.com/user-attachments/assets/2ed74f4e-547e-4b8a-853f-29c4cb7f7b87)
I can see the shadows in r1578.eed9600
![swappy-20241010-105839](https://github.com/user-attachments/assets/0422925a-1ad9-4d0a-a658-1ac3e84ae524)

**Comment by knm100** [comment]
I've gotten some 3D effects with the following configuration. But Chromium's icons look a bit weird
![swappy-20241010-115057](https://github.com/user-attachments/assets/72546d72-a0d7-4ae2-948d-8808fb8dac86)


```
-ScaleImage-shadow-radius: 4;
  -ScaleImage-shadow-x-offset: 0; 
  -ScaleImage-shadow-y-offset: 0;
  -ScaleImage-shadow-color: Rgba(0,0,0,0.6);
  -ScaleImage-shadow-clip: false;
```

**Comment by LBCrion** [comment]
It looks like the shadow is clipped by the widget boundaries. Do you have
any padding or margins around the widget? You need at least one of these to
accommodate the shadow.

**Comment by knm100** [comment]
It was working.  thank you!

**Comment by knm100** [comment]
Flatness is all the rage right now. I don't know if what we doing is going against the trend. but I like it .

**Comment by LBCrion** [comment]
Bah. Trends come and go. Shadows do look nice with the right style.
