### ISSUE TITLE
Preview of pager didn't work

### ISSUE THREAD

**Issue by knm100** [LBCrion/sfwbar#240]
I guess, this is not an issue.   but the protocols does not allow it

**Comment by LBCrion** [comment]
Do you mean pager preview (i.e. layout of windows on the workspace) or
preview of each window contents? The former is supported with custom IPCs,
but not with pure wayland protocols (which compositor are you using?). The
later isn't supported yet, the protocol to support this has been recently
merged into wayland-protocols, but isn't widely implemented by compositors
yet.

**Comment by knm100** [comment]
I was using labwc.

**Comment by LBCrion** [comment]
With labwc, pager previews aren't supported yet (as we don't have a common
protocol to communicate the window positions). Pager itself should work
with the latest git of sfwbar and labwc.

**Comment by 01micko** [comment]
Pager works fine. As stated, preview is unsupported.

**Comment by knm100** [comment]
thanks all of you!
