### ISSUE TITLE
How to make an automount widget?

### ISSUE THREAD

**Issue by knm100** [LBCrion/sfwbar#241]
I realized that sfwbar doesn't automatically mount widgets when I plugged in a USB flash drive.

**Comment by LBCrion** [comment]
Automount functionality itself is way out of scope for sfwbar. I would
recommend using udiskie as disk mounter. You can run udiskie -t to get a
tray icon in sfwbar tray.

**Comment by knm100** [comment]
thank you!

**Comment by LBCrion** [comment]
BTW, if there is a commonly available automount service with a control ipc,
implementing a control module for it would be in scope for sfwbar. I'm just
not aware of such a service.

**Comment by knm100** [comment]
what about AUTOFS? Is it okay?

**Comment by LBCrion** [comment]
I don't think autofs has a control ipc. Isn't it fully configured via
config files?

**Comment by knm100** [comment]
Or like the lxqt-panel implementation, I think pcmanfm-qt does the mounting, the plugin on lxqt-panel just   display the information.
