### ISSUE TITLE
No menu in Vesktop and possibly other Electron apps' tray icons

### ISSUE THREAD

**Issue by kode54** [LBCrion/sfwbar#242]
Possibly related to this, possibly not:

https://github.com/LBCrion/sfwbar/issues/222

Here's what the menu looks like under sfwbar:

![image](https://github.com/user-attachments/assets/8efa88f8-64e9-42ac-84af-c6a385d92a2d)

Tray doesn't even work now in ironbar, so I'll report that to them. Though the menu does work from Waybar:

![image](https://github.com/user-attachments/assets/6cd54087-f07c-4272-9f14-0f5deb0126b5)

**Comment by LBCrion** [comment]
Can you please check if the below patch (vs the latest git) helps?
```
diff --git a/src/snimenu.c b/src/snimenu.c
index d1e86c8..fde43da 100644
--- a/src/snimenu.c
+++ b/src/snimenu.c
@@ -264,7 +264,7 @@ static void sni_menu_get_layout_cb ( GObject *src, GAsyncResult *res,

   g_variant_get(result, "(u(i@a{sv}av))", &rev, &id, &dict, &iter);

-  if(rev > GPOINTER_TO_INT(g_object_get_data(G_OBJECT(sni->menu_obj), "rev")))
+/*  if(rev > GPOINTER_TO_INT(g_object_get_data(G_OBJECT(sni->menu_obj), "rev")))
   {
     menu = sni_menu_item_find(sni->menu_obj, id);
     if( (parent = gtk_menu_get_attach_widget(GTK_MENU(menu))) )
@@ -272,7 +272,8 @@ static void sni_menu_get_layout_cb ( GObject *src, GAsyncResult *res,
     else
       sni_menu_parse(menu, iter);
     g_object_set_data(G_OBJECT(sni->menu_obj), "rev", GINT_TO_POINTER(rev));
-  }
+  }*/
+  sni_menu_parse(sni->menu_obj, iter);

   g_variant_iter_free(iter);
   g_variant_unref(dict);
```

**Comment by kode54** [comment]
Yes, now the menu opens.

**Comment by LBCrion** [comment]
This is most likely caused by incorrect revision number being sent. Can you
please check if the latest git version works ok for you (without the patch)?

**Comment by kode54** [comment]
Yes, that works.
