### ISSUE TITLE
autohide sfwbar ?

### ISSUE THREAD

**Issue by sfs-pra** [LBCrion/sfwbar#258]
I did not find such functionality in the documentation

**Comment by 01micko** [comment]
sensor \<timeout\> https://github.com/LBCrion/sfwbar/blob/main/doc/sfwbar.rst

**Comment by LBCrion** [comment]
Indeed, the `sensor` property controls the autohide behavior. I added a
clarification to the doc to make searching for it easier.

**Comment by sfs-pra** [comment]
Thank you. It's working
