### ISSUE TITLE
If `mirror = "*"` is added before `layer = "bottom"` the bar won't show

### ISSUE THREAD

**Issue by Flrian** [LBCrion/sfwbar#263]
Tried it with the default config too, same thing happens.

Everthing works as expected:
```
layout {

  size = "100%"
  layer = "bottom"
  mirror = "*"
  exclusive_zone = "auto"
```
Bar isn't shown:
```
layout {

  size = "100%"
  mirror = "*"
  layer = "bottom"
  exclusive_zone = "auto"
```

That seems pretty weird and shouldn't happen, right?

**Comment by LBCrion** [comment]
Does the bar not show only on secondary monitors or does it affect the
primary monitor as well? (I.e. no bar at all?)

**Comment by LBCrion** [comment]
Can you please check if you still get this with the latest git? This looks like interaction between the layer shell and sfwbar workaround for making gtk play nice with the layer shell surfaces. I have a suspicion that the fix I committed fixes the issue for the recent gtk layer shell versions, but breaks it for the earlier versions.
