### ISSUE TITLE
The qterminal's icon in the task switcher didn't follow the taskbar and startmenu.

### ISSUE THREAD

**Issue by knm100** [LBCrion/sfwbar#264]
There is` icon=utilities-terminal` in `/usr/share/qterminal.desktop`.
labwc can find utilities-terminal.svg in the breeze icon and sfwbar can find qterminal.png in `/usr/share/hicolor/64/apps/`
Copied utilities-terminal.svg to `$HOME/.icon/hicolor/scalable/apps/ `and renamed it to qterminal.svg.  The taskbar and startmenu showed `$HOME/.icon/hicolor/scalable/apps/qteminal.svg `as the qterminal's icon, and the task switcher showed `/usr/share/hicolor/64/apps/qterminal.png` as the qterminal's icon.

If` /usr/share/hicolor/64/apps/qterminal.png` is deleted, Task Switcher showed the qterminal's icon via sfwbar logo.

**Comment by LBCrion** [comment]
Can you please post the output of sfwbar -d -g app_id ?

**Comment by LBCrion** [comment]
Can you check of the attached patch fixes the issue?

[diff.txt](https://github.com/user-attachments/files/17879158/diff.txt)

**Comment by knm100** [comment]
this issue should be fixed.  thank you
![swappy-20241123-191935](https://github.com/user-attachments/assets/eaca7464-9cbf-444c-84b2-163a55a5d913)

**Comment by knm100** [comment]
I've found that the sfwbar.config file caused this issue, if I commented out the CSS of task switcher, the latest git version (not including the patch you posted), the task switcher showed the same icon of qtermianl as taskbar and startmenu.

I'm wondering why CSS affects the selection of qterminal's icon.
could you take a look at my sfwbar.config?
[sfwbar.config.txt](https://github.com/user-attachments/files/17879879/sfwbar.config.txt)

**Comment by knm100** [comment]
Just tried 24px, 30px, 48px,   the three size of icon all can fix this issue.

**Comment by knm100** [comment]
`095c5ea` have fixed this issue, now no need to copy qterminal.svg to $HOME/.icon/   
Thanks

**Comment by knm100** [comment]
`lxqt-logout` have a desktop file named `lxqt-logout.desktop`  in `/usr/share/applications`.    there is `icon=system-log-out` in it
there is also` lxqt-leave.desktop` with` icon=system-shutdown`  in `/usr/share/applications`
running the command `wlrctl toplevel list` from terminal  and  i can  find that the appid is` lxqt-leave` and the title is `logout from lxqt session`. 
IMO,  the sfwbar should search the desktop file  in `/usr/share/applications`  by appid first,   so it should find lxqt-leave.desktop and look in it to find the icon name is system-shuntdown.  
In fact, the icon of the lxqt-logout displayed on the panel is system-reboot.
I have copied the icon of system-shutdown.svg to `$HOME/.icon `and renamed it to lxqt-leave.svg.  saw also the correct icon, but after displaying it correctly a couple of times, it goes back to the wrong icon(system-reboot)!
![swappy-20241127-222217](https://github.com/user-attachments/assets/8af07bb8-8fe7-488d-8224-b3f68285fbc2)

**Comment by LBCrion** [comment]
Where would sfwbar get system-reboot icon from? If lxqt-leave.desktop has
icon=system-shutdown I would expect that icon to be used. Sfwbar does check
the .desktop entry with filename = app_id in the first instance.
Is system-reboot icon present in any other .desktop entries?

**Comment by knm100** [comment]
I was using the sfwbar with breeze theme
there are following desktop files in` /usr/share/applications/`
lxqt-leave.desktop(`icon=system-shutdown,Exec=lxqt-leave`) 
lxqt-lockscreen.desktop(`icon=system-lock-screen,Exec=lxqt-leave --lockscreen`)
lxqt-logout.desktop (`icon=system-log-out,Exec=lxqt-leave --logout`)
lxqt-reboot.desktop(`icon=system-reboot,Exec=lxqt-leave --reboot`)
lxqt-hiberante.desktop(`icon=system-suspend-hibernate,Exec=lxqt-leave --hibernate`)
lxqt-shutdown.desktop(`icon=system-shutdown,Exec=lxqt-leave --shutdown`)
lxqt-suspend.desktop(`icon=system-suspend,Exec=lxqt-leave --suspend`)
they have the same appid(lxqt-leave),different titles. 
all of those icons can be found in` /usr/share/icons/breeze/actions/32/ `
today, the icons of they have been changed to system-suspend.svg.
![swappy-20241128-091853](https://github.com/user-attachments/assets/d313a206-4b4c-4a8b-bbcb-ae4f1ff02a16)
