### ISSUE TITLE
git ver 8b75300 Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by knm100** [LBCrion/sfwbar#266]
git ver 8b75300  output a message: Segmentation fault (core dumped)
[sfwbar coredump.txt](https://github.com/user-attachments/files/17896487/sfwbar.coredump.txt)

**Comment by knm100** [comment]
480b096 haven't  issue with me.

**Comment by LBCrion** [comment]
I'm not too surprised. This commit was a major rewrite of the expression
parser. That said, the parser shouldn't generate Ident calls without a
parameter. I added a check to guard against this. Can you please check if
you can reproduce this with the latest git version?

**Comment by LBCrion** [comment]
Can you try the latest git again please? The cause makes a lot more sense
now. I flipped two parameters around when allocating the vm stack and got
garbage.

**Comment by knm100** [comment]
I can run `f5423be` successfully,  but it crsahed when i launched the program like qterminal, chromium, lxqt-leave.   not to test for  the other programs.

**Comment by LBCrion** [comment]
Are you launching the programs from the bar or does the bar crash
regardless of how you launch a program? Can you get a stack trace of the
crash please? (I couldn't reproduce on my machine so far, so need to figure
out what's causing it).

**Comment by knm100** [comment]
Launching the program from bar or  by shrotcuts , all of the both caused the git ver` ee1b9bb`  to crash.
the following log1.txt  is the output from running the command `WAYLAND_DEBUG=1   sfwbar 2> log1.txt `in terminal 
[log1.txt](https://github.com/user-attachments/files/17917143/log1.txt)

**Comment by LBCrion** [comment]
This is the wayland protocol trace and it doesn't show much of a reason for
a crash. Can you get a stacktrace? Generally after you get a coredump, you
can run "coredumpctl gdb" and once in gdb, run "bt" to get the stack trace.

**Comment by knm100** [comment]
Please see the following coredump.txt,    is it what you need? 
[coredump.txt](https://github.com/user-attachments/files/17928364/coredump.txt)

**Comment by LBCrion** [comment]
This is it indeed. Can you try the latest git please to see if it helps?

**Comment by knm100** [comment]
`123f986` worked fine, thank you!
