### ISSUE TITLE
menu of winops.widget don't pop up with git ver 123f986 any more.

### ISSUE THREAD

**Issue by knm100** [LBCrion/sfwbar#268]
It pops up normally with the git ver 480b096

**Comment by LBCrion** [comment]
Odd, it's working on my machine with the current git. Can you try running
"sfwbar -d -g winops", right clicking on the window and posting the output
please?

**Comment by knm100** [comment]
Please see the following screenshot
![swappy-20241128-103958](https://github.com/user-attachments/assets/4d103225-8d2f-469e-b3c5-8559b8a86b38)

**Comment by knm100** [comment]
I recorded a video to show you this issue.  after plaied the video by chromium.  I found the sfwbar crashed.  the following video and gdb debug file for you reference

https://github.com/user-attachments/assets/6b830440-1800-48ae-aebf-f8e837358556

[crash.txt](https://github.com/user-attachments/files/17942290/crash.txt)

**Comment by knm100** [comment]
the ncenter.widget don't show the notifications. please see the following video

https://github.com/user-attachments/assets/220b586d-6534-4eac-a50e-4467640e6f4a

The panel crashes when the volume is adjusted, regardless of whether audio is playing or not. This kind of crash can be reproduced

**Comment by LBCrion** [comment]
ncenter should be fixed in the latest git (or rather the underlying functionality that caused ncenter to not work correctly is fixed).
Can you please check if the crash on audio changes and window switching is still there for you?

**Comment by knm100** [comment]
the ncenter and volume have been fixed in git ver` 0ae3f6e`      
the issue of winops is still there.   
I also found out that the idle doesn't change the IdleInhibitState properly either.   Clicking on the icon of idle does not respond

**Comment by LBCrion** [comment]
Can you check idle.widget with the latest git please?

**Comment by LBCrion** [comment]
Winops should hopefully work as well now.
