### ISSUE TITLE
the calendars with issue after git ver 480b096

### ISSUE THREAD

**Issue by knm100** [LBCrion/sfwbar#269]
Here's a screenshot of the calendar as it appeared in git ver` 480b096` and` 2624bbe` on December 1 (yesterday).
![swappy-20241202-102342](https://github.com/user-attachments/assets/3aedede7-d619-4188-8040-23e0ef68e3ce)

**Comment by LBCrion** [comment]
Is the style #cal_cell_focused_current defined in the widget? I don't see
it referenced anywhere.

**Comment by knm100** [comment]
Sorry,  I was using the cal.widge made by @01micko .
style #cal_cell_focused_current can work for me in git ver 480b096
the following ins the my cal.widget
[cal.widget.txt](https://github.com/user-attachments/files/18035466/cal.widget.txt)

**Comment by knm100** [comment]
in git ver a72e3de,  the  style #cal_cell_focused_current worked again.
