### ISSUE TITLE
The winops menu  sometimes does not pop up as expected.

### ISSUE THREAD

**Issue by knm100** [LBCrion/sfwbar#270]
Please see the following video.

https://github.com/user-attachments/assets/029acaa2-b7f4-4e15-b927-c3598692d33e
The programs that can't be popped up winops menu are random. sometimes all programs can't pop up winops menu.

 may not pop up now, but after a few minutes or more, the winops menu will pop up again.

for any program, after the first pop-up winops menu, the winops menu will always pop-up.

**Comment by LBCrion** [comment]
What exactly doesn't popup? The winops menu or the window list from the
appid group?

**Comment by knm100** [comment]
The winops menu of appid group doesn't popup, when there is only one window in the appid group.

**Comment by LBCrion** [comment]
Can you try the latest git version please?
