### ISSUE TITLE
git ver  `430bc0b'  the bar crashed,when launched program by launcher botton

### ISSUE THREAD

**Issue by knm100** [LBCrion/sfwbar#271]
if launched programs by shortcuts or startmenu,  the bar worked fine.
the following file is the gdb coredump file for you reference.
[coredump.txt](https://github.com/user-attachments/files/18023687/coredump.txt)

**Comment by LBCrion** [comment]
Can you check the latest git version please?

**Comment by knm100** [comment]
It work now, thank you!
