### ISSUE TITLE
network-module.widget problems

### ISSUE THREAD

**Issue by sfs-pra** [LBCrion/sfwbar#274]
1. Does not work with NM
With iwd only works when dhcpcd is running
2. In wifi password input window : white text on white background
3. tray icon does not change. Always “network-wired”
No errors here ?
`Set XNetworkIcon = If(Ident(NetInfo),If(NetInfo(“essid”)!=“”,$XNetworkWirelessIcon,$XNetworkWiredIcon),“”")`
The tooltip shows essid. The icon is : “network-wired”
4. After “disconnect” the connection automatically reconnects itself. Only “forget password” helps

**Comment by LBCrion** [comment]
1) With network manager, can you try running sfwbar with `-d -g nm:` parameters and post any output?
2) With iwd and without dhcpcd running, can you try running with `-d -g iwd:`? One thing to note if you're playing with your settings with and without network manager, you may need to restart iwd after shutting down network manager.
3) Password input window doesn't have any default css settings in the config I believe, so it should be using your default gtk theme settings. THat said, you can override these using nodes `#wifi_user_entry` and `#wifi_passphrase_entry`

4) tray icon - this one is messy, I may need to add some debug output and ask for some testing on this one.

5) Is the auto reconnect after disconnect - I assume this is happening with iwd?

**Comment by sfs-pra** [comment]
Problem with nm solved: killall nm-applet
Connecting - disconnecting via “connect” - “disconnect” - ok

Connecting - disconnecting via “left click” :
Disconnect - ok
Connecting - not connecting

Password color - problem solved by selecting dark gtk theme

C iwg - I'll try to do some experiments tomorrow

trayicon - if 
`If(Ident(NetInfo),If(NetInfo(“essid”)!=“”“,$XNetworkWirelessIcon,$XNetworkWiredIcon),”“”")`
remove “!” - always wifi
Are you sure there are no errors in this line of code? 

When there are no connections - there should be some third icon?

**Comment by LBCrion** [comment]
Odd, nm-applet shouldn't prevent sfwbar nm module from working.
NetworkModule interface should allow multiple clients to access it
simultaneously.
In your description of connecting / disconnecting above, do you mean that
if you connect to a network, then disconnect and try to connect again - it
fails?

trayicon - the code is correct, it checks if ESSID is populated to
determine if wifi is connected. If you hove over the network icon and get a
tooltip, do you see essid: populated when you're connected to wifi?

**Comment by sfs-pra** [comment]
Connecting - disconnecting via “left click” :  figured it out. The confusion was because I thought that “left-click” worked like “on/off” i.e. it changes the state of the connection
Turns out it's just “on.”
“on/off” would have been more convenient...
Same with iwd

trayicon :
ESSID is filled in and visible in tooltip while the icon does not change. Always “network-wired”

**Comment by sfs-pra** [comment]
After this tweak, the tray icon shows what I need it to show :
# cat sfwbar-net-ico
```
#!/bin/bash
check_interface() {
    local interface=$1
    local status=$(ip link show "$interface" | grep -oP 'state \K\w+')
    local link_quality=$(iwconfig "$interface" 2>/dev/null | grep -oP 'Link Quality=\K\d+/\d+')

    if [ -n "$link_quality" ]; then
        local quality_percent=$(echo "$link_quality" | awk -F'/' '{printf "%.0f %%\n", $1/$2*100}')

    fi
        [ "$status" = "UP" ] && echo "$interface: $status $quality_percent"

}

interfaces=$(ip link show | grep -oP '^\d+: \K\w+' | grep -v 'lo')

a=`for interface in $interfaces; do
    check_interface "$interface"
done`
i=connect_no
q="`echo $a |awk '{print $5}'`"

[ "`echo $a |grep UP`" ] && i=network-wired
[ "`echo $a |grep %`" ] && i=wifi 
echo $i 
```
At the beginning of network-module.widget I added :
```
scanner {
  Exec("sfwbar-net-ico") {
    XNetworkIcon1 = Grab(First)
  }
}
```
In the middle replaced:
```
#Set XNetworkIcon = If(Ident(NetInfo),If(NetInfo("essid")!="",$XNetworkWirelessIcon,$XNetworkWiredIcon),"")
Set XNetworkIcon2 = If(Ident(NetInfo),If($XNetworkIcon1="wifi",$XNetworkWirelessIcon,$XNetworkWiredIcon),"")
Set XNetworkIcon = If(Ident(NetInfo),If($XNetworkIcon1="connect_no",$XNetworkIcon1,$XNetworkIcon2),"")
```

**Comment by LBCrion** [comment]
Disconnecting on clicking an active network should be possible to implement
as a config change I think. I'll look into it once I finish the current
re-write of the expression / action engine (some of the changes I'm making
should make this type of configuration much cleaner).

Let me look into the network icon. If ESSID is showing up in the tooltip,
it's likely a trigger not firing correctly (and the icon not updating as a
result).

I would prefer to avoid a script based solution,  since it involves
executing a script repeatedly just to check wifi connection state.  I
originally wrote the predecessor to sfwbar to avoid repeatedly executing
scripts to populate a status bar,  since it wastes a lot of resources.

**Comment by LBCrion** [comment]
I pushed some changes that should make the network module more reliable in
updating the wifi connection state. Can you please check if this makes any
difference on your setup?

**Comment by sfs-pra** [comment]
https://github.com/LBCrion/sfwbar/commit/14c4e52738c9e041ab2ae3192803e7a491900569 - Icon started to change when wifi connection, but “connect” “disconnect” stopped working.
Works together with nm-applet
There is no icon for disconnected ethernet and wifi?

**Comment by LBCrion** [comment]
connect/disconnect should work now. Icon for disconnected network can be
done via config changes, i.e. If(NetInfo("interface")="",
"network-disconnected", ...)

**Comment by sfs-pra** [comment]
sfwbar-git-r1686.bf76d13 - Problem solved

Icon for disconnected network :
```
#Set XNetworkIcon = If(Ident(NetInfo),If(NetInfo("essid")!="",$XNetworkWirelessIcon,$XNetworkWiredIcon),"")
Set XNetworkIcon1 = If(Ident(NetInfo),If(NetInfo("essid")!="",$XNetworkWirelessIcon,$XNetworkWiredIcon),"")
Set XNetworkIcon = If(NetInfo("interface")="","noconnect",$XNetworkWiredIcoon1)
```
iwd hasn't been tested yet

**Comment by sfs-pra** [comment]
sfwbar-git-r1686.bf76d13 - Problem solved
iwd - problem solved
