### ISSUE TITLE
ext-workspace crash when removing focused workspace

### ISSUE THREAD

**Issue by Consolatis** [LBCrion/sfwbar#275]
When the active workspace is the last one and then changing `rc.xml` in labwc to a lower number sfwbar crashes because it tries to de-reference `focus` via `workspace_commit()` on getting a new focus.
This seems to fix it but I don't know if its the correct fix for the other workspace backends:
```diff
diff --git a/src/workspace.c b/src/workspace.c
index bb6a8ab..28708ce 100644
--- a/src/workspace.c
+++ b/src/workspace.c
@@ -84,6 +84,9 @@ void workspace_unref ( gpointer id )
 
   g_debug("Workspace: destroying workspace: '%s'", ws->name);
 
+  if(ws == focus)
+    focus = NULL;
+
   if(g_list_find_custom(global_pins, ws->name, (GCompareFunc)g_strcmp0))
   {
     g_debug("Workspace: workspace returned to a pin: '%s'", ws->name);
```

**Comment by LBCrion** [comment]
Thank you! This is indeed a correct fix. Setting focus to NULL will
effectively ignore it until sfwbar gets a new focus from the compositor.

**Comment by Consolatis** [comment]
I see you added it as ce07b7b30f171e7b21cad30e2e9157c9c1e2bde5

Thanks as always for your prompt fix :)
