### ISSUE TITLE
Variable in "include"

### ISSUE THREAD

**Issue by sfs-pra** [LBCrion/sfwbar#278]
```
Set LNG = "-you.UTF-8"
include("wifi" + $LNG + ".widget")
```
does not work. How to use it correctly?

**Comment by LBCrion** [comment]
This construct would be rather weird in the current implementation of the
variables. Sfwbar variables aren't variables in the traditional sense. You
can think of them as cells in a spreadsheet with auto-calculation enabled.
I.e. the value of the variable will change over time and all expressions
referencing it will update along with it. Furthermore variable updates are
asynchronous, so the initial value of the variable may not be what you
expect it to be.
Changing a value of the input to Include would imply reading a new config
file every time the variable value updates. If you really want to read
config updates from different files based on a state of a variable, you can
use a combination Config and Read actions to accomplish this.

**Comment by LBCrion** [comment]
Can I check what you're trying to accomplish with this? Are you looking to change the language on a labels in the widget based on the current locale?

**Comment by sfs-pra** [comment]
`PipeRead('echo "include(\"wifi-${LANG}.widget\")"')  `
It doesn't work either

I want to change the language on a labels in the widget based on the current locale.
Can i use gettext for this?

**Comment by LBCrion** [comment]
How about something like this?

Exec("echo ${LANG}") {
  Lang = Grab()
}
Function("SfwbarInit") {
  Config Read "wifi-" + $Lang + ".widget"
}

**Comment by sfs-pra** [comment]
"Exec" should be added to the sfwbar.config ? - malfunctions
It works like this :
`    PipeRead "echo 'Set Lang = \"'$LANG'\"'"`
When "Lang" is defined - "Config Read" still doesn't work:
`Read"wifi-"+$Lang+".widget":1:4: error: Unexpected input at the end of expression`

**Comment by LBCrion** [comment]
Oops, needs to be Config Read("...")

**Comment by sfs-pra** [comment]
`Config "Read("wifi-" + $Lang + ".widget")"`
Unexpected toplevel token

**Comment by LBCrion** [comment]
Don't put quotes around Read, just:
Config Read("wifi-" + $Lang + ".widget")

**Comment by sfs-pra** [comment]
`Config Read("wifi-" + $Lang + ".widget")`
config string:1: Unexpected toplevel token

**Comment by sfs-pra** [comment]
```
PipeRead "echo 'Set Lang = \"'$LANG'\"'"
Config Read("/usr/share/sfwbar/wifi-" + $Lang + ".widget")
```
works !
But not very convenient. It would be more convenient to use standard “gettext”

**Comment by LBCrion** [comment]
I guess we'll need to use gettext to translate the config files? Sfwbar had
virtually no builtin strings on it's own.  All labels are defined in the
configs. It should be fairly simple to create a new function to translate
strings using glib gettext interface from what I can see.

**Comment by sfs-pra** [comment]
> I guess we'll need to use gettext to translate the config files?
Yes
> create a new function
`GT(Pattern[,TEXTDOMAIN])`

**Comment by LBCrion** [comment]
I think the hardest bit of work will be extracting the list of strings to
translate. I don't xgettext will be able to extract the strings from sfwbar
configs,  since some of the strings are nested.

**Comment by sfs-pra** [comment]
There's very little text. It can be done manually

**Comment by LBCrion** [comment]
If you're willing to do the hard part and catalogue all the strings,  you
can have the gettext function tomorrow.  Do you GT as a name or something
else?

**Comment by LBCrion** [comment]
No need to wait for tomorrow, you can have it now: GT(msgid [,domain]).
locale files are in DATADIR/locale

**Comment by sfs-pra** [comment]
> If you're willing to do the hard part and catalogue all the strings, you can have the gettext function tomorrow.

Ready

**Comment by sfs-pra** [comment]
> I don't xgettext will be able to extract the strings from sfwbar

Can xgettext do it from “modules”?
There's text there, too.

**Comment by LBCrion** [comment]
You can use xgettext on modules, but I think it's probably better to allow
setting these strings from config, so we can handle things consistently. I
think the only strings are in the username/passphrase prompts in the wifi
modules. I wonder if I should just add an action WifiSetPrompts to allow
defining these strings from config.
