### ISSUE TITLE
sfwbar-git-r1682.14c4e52 : stopped working ">=" "<="

### ISSUE THREAD

**Issue by sfs-pra** [LBCrion/sfwbar#281]
Everything worked fine in sfwbar-git-r1622.64b65ff 
For example, changing lan-bps.widget :
```
#    value = Str((EthRcvd-EthRcvd.pval)/0.001024/EthRcvd.time,0)+"K/s"
    value = If(EthRcvd>EthRcvd.pval,Str((EthRcvd-EthRcvd.pval)/0.001024/EthRcvd.time,0)+"K/s","test"
```
I get “test”.

Change “>” to ">="
`/usr/share/sfwbar/lan-bps.widget:32: Invalid property in a widget declaration`

"Pad" stopped working too

In https://github.com/LBCrion/sfwbar/blob/main/doc/sfwbar.rst - error : >=	less than or equal
Right : <=

**Comment by LBCrion** [comment]
'>=' still needs to be implemented in the new parser/vm. You can do
If(!(EthRcvd<EthRcvd.prev), ...)
But just to check do you have the source with EthRcvd defined? You can copy
it from lan-bps.widget if needed.

**Comment by sfs-pra** [comment]
EthRcvd is defined.
`value = Str((EthRcvd-EthRcvd.pval)/0.001024/EthRcvd.time,0)+"K/s"`
Works well
In the standard lan-bps.widget changed only this line

So it's better not to use the latest version yet?

**Comment by LBCrion** [comment]
The git version would be prone to bugs in the expression engine right now,
but on the other hand, testing is very helpful ;)

>= and <= should be fixed in the current version.

**Comment by sfs-pra** [comment]
OK :) I'm waiting for the bugs to be fixed and ready to continue testing...

**Comment by sfs-pra** [comment]
sfwbar-git-r1686.bf76d13 - Problem solved
