### ISSUE TITLE
Pad doesn't work in sfwbar-git-r1693.86654c1 :

### ISSUE THREAD

**Issue by sfs-pra** [LBCrion/sfwbar#288]
value = Pad("123",5," ") - doesn't work
value = "123" - work

**Comment by LBCrion** [comment]
This should be fixed now

**Comment by sfs-pra** [comment]
sfwbar-git-r1697.de2d42b
It got worse : --nan

**Comment by LBCrion** [comment]
Do you get -nan with value = Pad("123", 5, " ") ?
This sounds very odd, since Pad returns a string. Or is it a different
expression?

**Comment by sfs-pra** [comment]
sfwbar-git-r1705.818813f - problem solved
