### ISSUE TITLE
"Scan" in wifi.widget is not clickable

### ISSUE THREAD

**Issue by sfs-pra** [LBCrion/sfwbar#289]
sfwbar-git > r1665.a72e3de
sfwbar-git <= r1665.a72e3de - norm

**Comment by LBCrion** [comment]
if you run "sfwbar -d -g trigger:", do you get any output when you press
the scan button?

**Comment by sfs-pra** [comment]
sfwbar-git-r1705.818813f
"sfwbar -d -g trigger:" - the button won't press. debug writes nothing
Wifi connects normally (iwd)

**Comment by LBCrion** [comment]
Can you try the latest git please?

**Comment by sfs-pra** [comment]
sfwbar-git-r1707.53cb1e0 - problem solved
