### ISSUE TITLE
i get segmentation fault using sfwbar in river

### ISSUE THREAD

**Issue by adcdam** [LBCrion/sfwbar#29]
Hi 
when i launch sfwbar in river i get segmentation fault, in sway and labwc it work fine.
https://github.com/riverwm/river
im using glibc 2.35, wlroots 0.15.1

**Comment by LBCrion** [comment]
Is this with the latest release or the current git please?

**Comment by adcdam** [comment]
i used sfwbar v1.0_beta6 and river 0.1.3

**Comment by LBCrion** [comment]
It looks like river doesn't support idle inhibit protocol. Can you please check if the attached patch solves the issue?
[inhibit_check.txt](https://github.com/LBCrion/sfwbar/files/8703306/inhibit_check.txt)

**Comment by adcdam** [comment]
yes that solves the issue and was able to launch sfwbar from river, thanks!!

**Comment by LBCrion** [comment]
Closing as the issue has been resolved.
