### ISSUE TITLE
GT("msgid" [,"domain"]) problem

### ISSUE THREAD

**Issue by sfs-pra** [LBCrion/sfwbar#294]
sfwbar-git-r1718.4a8690c
[gt.tar.gz](https://github.com/user-attachments/files/18249924/gt.tar.gz)
startmenu.widget
`tooltip = GT("Application menu")`
or
`tooltip = GT("Application menu",sfwbar)`
if you move the cursor closer to the menu :
```
08:25:11,21 expr: '(null)' = 'Меню', vstate: 1
munmap_chunk(): invalid pointer
Аварийный останов
```

**Comment by LBCrion** [comment]
This should hopefully be fixed now. Can you try again please?

**Comment by sfs-pra** [comment]
sfwbar-git-r1719.9fafc51
tooltip = GT("Application menu") - work
I'll keep working on the .pot

tooltip = GT("Application menu",sfwbar) - no work
```
21:20:19,17 expr: '(null)' = '0', vstate: 1
21:20:19,17 expr: '(null)' = 'Application menu', vstate: 1
```
It's not translating.

**Comment by LBCrion** [comment]
It should be tooltip = GT("Application menu","sfwbar")
Without quotes,  sfwbar is interpreted as a numeric variable, which causes
GT to return with an invalid type error.

**Comment by sfs-pra** [comment]
` GT("Application menu","sfwbar")` - work!
Need to add to documentation

**Comment by sfs-pra** [comment]
I'm having trouble with “item”:
`  item("GT('focus')", Focus );`
missing label in item

`  item("GT('focus')", Focus );`
GT('focus')

**Comment by LBCrion** [comment]
Menu items take literal strings, so GT indeed won't work on these
currently. Looks like I'll need to do some work on this. I think the
question is - at what point should a menu item be updated? When it's built
or when the menu is about to be popped up.

**Comment by LBCrion** [comment]
You should now be able to use expressions in menu titles, i.e.
Item(GT('focus'), Focus)

**Comment by sfs-pra** [comment]
sfwbar-git-r1722.ddae3ec - menu problem solved

**Comment by sfs-pra** [comment]
sfwbar-git-r1722.ddae3ec :
`  item(" focus%gtk-find", Focus );`
or
`  item(" "+GT("focus")+"%gtk-find", Focus );`
Stopped finding icons. Substitutes “sfw”
It worked in sfwbar-git r1622.64b65ff.

**Comment by LBCrion** [comment]
Can you try the latest git please? Should be fixed hopefully.

**Comment by sfs-pra** [comment]
sfwbar-git r1723.c609476 -  problem solved

**Comment by sfs-pra** [comment]
I checked and posted a widget with GT https://github.com/LBCrion/sfwbar/pull/300
