### ISSUE TITLE
lan-bps chart

### ISSUE THREAD

**Issue by sfs-pra** [LBCrion/sfwbar#298]
I want to change the lan-bps.widget “label” to “chart”.
What is 100% ?
If you take as 100% `ip link show eth0 |head -n1|awk -F qlen '{print $2}'` - the chart will be at zero all the time
You could take the number of bits per minute as 100%. I don't understand how to get it in widget

**Comment by LBCrion** [comment]
The answer would depend on what you're trying to display. I assume you're
looking to graph the receive transmission rate. There is really no well
defined upper limit you can use. You could use your adapters max rate,  but
I think your actual rates would be way too low vs that to get a meaningful
graph.

Possibly the most reasonable graph you can plot is the current tx rate vs
max recorded tx rate for the session. It would be a bit fiddly to
implement,  but should be possible.

**Comment by sfs-pra** [comment]
> Possibly the most reasonable graph you can plot is the current tx rate vs max recorded tx rate for the session. It would be a bit fiddly to implement, but should be possible.

`Set EthRcvdMax1 = If(EthRcvd1 >= EthRcvdMax1, EthRcvd1, EthRcvdMax1)`
`[lan-chart.widget.gz](https://github.com/user-attachments/files/18270233/lan-chart.widget.gz)`
Рroblems :
When “rcvd” is changed to “sent” - the whole chart is recolored

**Comment by Consolatis** [comment]
For another implementation I've gone with a default min cap of 50 kb/s and otherwise max bw for the values represented in the history to mean 100%. The min cap ensures that values like 0.5 kb/s don't show up as 100% if there is otherwise no noticeable network traffic.

**Comment by LBCrion** [comment]
How about this?
```
file("/proc/net/dev") {
  EthRcvd = RegEx("^(?!.*lo).*:[\t ]*([0-9]+)",Sum)
}

Set LanBPS = (EthRcvd-EthRcvd.pval)/0.001024/EthRcvd.time
Set LanMax = Max(Max(50, Cached(LanMax)), LanBPS)

layout {
  chart {
    style = "cpu_chart"
    interval = 1000
    value = LanBPS/LanMax
  }
}
```

**Comment by sfs-pra** [comment]
> How about this?

perfectly


> EthRcvd = RegEx("^(?!.*lo).*:[\t ]*([0-9]+)",Sum)

And if two interfaces eth0 wlan0 ?

**Comment by LBCrion** [comment]
This will sum up the traffic across all interfaces other than lo.

If you want a specific interface,  you can replace !.lo with interface
name.

**Comment by sfs-pra** [comment]
[lan-chart.widget.gz](https://github.com/user-attachments/files/18280258/lan-chart.widget.gz)

> When “rcvd” is changed to “sent” - the whole chart is recolored

Here either draw 2*chart or wait for a chart with two charts to appear  :)
