### ISSUE TITLE
Minor issue - zip file containing folder named buld instead of build

### ISSUE THREAD

**Issue by m4lin** [LBCrion/sfwbar#30]
just to let you know, i downloaded the zip file to build and install sfwbar, but the build folder is named buld, so fail the step 

ninja -C build

rename the folder solve the issue obviously.

KR

Marco

**Comment by LBCrion** [comment]
Is this with 1.0beta6? I wouldn't expect a build directory in the tree,
since I roll releases directly from github (and I certainly wouldn't expect
a buld directory). Let me look into this.

**Comment by LBCrion** [comment]
I just checked a zip file for 1.0_beta6, and couldn't find a buld directory
in it.

**Comment by m4lin** [comment]
Sorry for the delay in coming back to you.
My apologies for this, i just realize looking at the history of my commands that i made the silly mistake giving command below
meson -C buld

sorry again, please close

**Comment by LBCrion** [comment]
Thank you for checking. Closing issue per above.
