### ISSUE TITLE
Menus are not aligned

### ISSUE THREAD

**Issue by 01micko** [LBCrion/sfwbar#35]
This is a recent development. Screen shot tells the story.

![menu-bug](https://user-images.githubusercontent.com/1019119/180616760-8b27e17a-2535-40e4-9ce5-b18e3d8a2c4b.png)

**Comment by 01micko** [comment]
BTW, it's only on taskbar. My widget menus on RHS are fine
![menu-ok](https://user-images.githubusercontent.com/1019119/180616947-d06f847c-5450-4308-a4b7-97c998e35be6.png)
.

**Comment by LBCrion** [comment]
This should be fixed in the latest git.

**Comment by 01micko** [comment]
Confirmed :smile:
