### ISSUE TITLE
[feature request] compensate for apps that don't expose app_id

### ISSUE THREAD

**Issue by 01micko** [LBCrion/sfwbar#36]
Please see this [labwc](https://github.com/labwc/labwc/issues/460) issue and read about Vivaldi and Opera browsers misbehaving.

Would it be possible to override the `app_id` with something in the config?

**Comment by LBCrion** [comment]
Ideally, this would be done on a compositor level, since compositor can consistently override app_id for itself and any clients querying it. The compositor would also have access to more information (such as a pid of the window owner, which can be mapped to an executable the window belongs to).
That said, it wouldn't be hard to add logic that would have a mapping table of regular expressions, such that:

If app_id is NULL and regex title matches a mapping table entry, app_id = override specified in the mapping table. 

Is this how you see it working?

**Comment by 01micko** [comment]
> That said, it wouldn't be hard to add logic that would have a mapping table of regular expressions, such that:
> 
> If app_id is NULL and regex title matches a mapping table entry, app_id = override specified in the mapping table.
> 
> Is this how you see it working?

That's almost exactly how @Consolatis described on IRC (libera#labwc) earlier today.

**Comment by LBCrion** [comment]
Does vivaldi always have an easily identifiable pattern in the title? Firefox for example sets the title to be just the title of the currently open page, so it wouldn't be possible to reliably id it from a title.

**Comment by LBCrion** [comment]
I took a stab at this in the latest git, to add a mapping, you need to add a toplevel config command:

MapAppId "pattern", "app_id"

**Comment by 01micko** [comment]
> Does vivaldi always have an easily identifiable pattern in the title? Firefox for example sets the title to be just the title of the currently open page, so it wouldn't be possible to reliably id it from a title.

Yes, the format is "some title - Vivaldi"

**Comment by 01micko** [comment]
> Does vivaldi always have an easily identifiable pattern in the title? Firefox for example sets the title to be just the title of the currently open page, so it wouldn't be possible to reliably id it from a title.

URL: `file:///initrd/mnt/dev_save/micko/gtkdialog/doc/reference/button.html`
Firefox title bar: `gtkdialog: button widget reference`
html source: `<title>gtkdialog: button widget reference</title>`
sfwbar taskbar and labwc window title: `gtkdialog: button widget reference -- Mozilla Firefox` # compiled in slackware from official repo
sfwbar taskbar and labwc window title: `gtkdialog: button widget reference - Vivaldi` # both snapshot and stable (latest)

Vivaldi is almost identical. `s/-- Mozilla Firefox/- Vivaldi`

This is what I'm trying: `MapAppId "*Vivaldi$", "vivaldi"` with as many variants on the pattern as I can think of and preceding 'vivaldi' with `com.`, using `vivaldi-stable` and `vivaldi-snapshot` with/without the prefix. Nothing of value yet.

So where does `sfwbar` get the name of the app from in the taskbar?

**Comment by 01micko** [comment]
Here's another idea. What about a user configurable default icon? Say `if(app_id == NULL)`?
It's only browsers troubling me (although [`snayk`](https://sr.ht/~leon_plickat/Snayk/)  doesn't work either - I might be able to patch that and offer a PR) so I could use the generic `web-browser` icon.

**Comment by LBCrion** [comment]
Everything sfwbar displays in the taskbar comes from the foreign toplevel protocol, in this case "- Mozilla Firefox" or "- Vivaldi" would be part of the title field supplied through the foreign toplevel protocol. It's possible that an application sets a different title in it's own decoration (if it uses CSD) vs what is supplies to the compositor.

Does wayland-only firefox have the same app_id issue as vivaldi? (I would prefer to test with firefox, since I don't fancy pulling in all of the chromium dependencies, I'm on gentoo and compiling them all will take a good while). 

Meanwhile, I updated the lookup code to re-update an icon based on the title, every time a title changes. This is to catch cases where the browser starts with a title for an empty window, which may not get caugt and then updates it to something matching a pattern. Would you mind giving it a try with the above mapping rule?

**Comment by 01micko** [comment]
Firefox is using CSD. there is absolutely no problem with firefox, chromium or brave browsers. Google-chrome has a bug where on Xwayland we are told '**G**oogle-chrome' and pure wayland '**g**oogle-chrome' which is very sloppy IMHO. They are all using CSD. 

The problem with Vivaldi is that they had it right in the snapshots in May this year and later it regressed. Pure wayland worked a treat - app_id and CSD were fine. I suspect Opera wouldn't care less.

I'll try the latest soon. Thanks for your great work!

**Comment by 01micko** [comment]
Yep `snayk` works. Thanks. I'll offer Mr Plickat my icon, .desktop etc for consideration to his repo.

**Comment by LBCrion** [comment]
@01micko, can you try running the latest git version with "sfwbar -d 2>&1 | grep app_id" and launch vivaldi? Then post the output here. I want to see what we're getting for app_id and title to try and make the mapping work.

**Comment by 01micko** [comment]
Yes

```
~$ sfwbar -d 2>&1 | grep app_id
06:07:46.40 app_id: 'lxterminal', title 'LXTerminal'
06:07:56.25 app_id: 'lxterminal', title 'LXTerminal'
06:07:56.27 app_id: 'lxterminal', title 'LXTerminal'
06:07:57.00 app_id: '', title 'Vivaldi - Vivaldi'
06:07:57.00 app_id: 'lxterminal', title 'LXTerminal'
06:07:57.52 app_id: '', title '[feature request] compensate for apps that don't expose app_id · Issue #36 · LBCrion/sfwbar - Vivaldi'
06:08:13.66 app_id: '', title '[feature request] compensate for apps that don't expose app_id · Issue #36 · LBCrion/sfwbar - Vivaldi'
06:08:13.66 app_id: 'lxterminal', title 'LXTerminal'

```

**Comment by LBCrion** [comment]
Thank you. It looks like app_id isn't actually missing for vivaldi, it's just blank. I changed the code to lookup app_id if the provided value is blank. Can you try the latest git please? Your config should work:

MapAppId "*Vivaldi$", "vivaldi"

**Comment by 01micko** [comment]
No joy. No icon.

```
06:40:12.26 app_id: '', title 'Commits · LBCrion/sfwbar - Vivaldi'
06:40:19.36 app_id: '', title 'check for empty appid when mapping · LBCrion/sfwbar@a0c10d2 - Vivaldi'
06:40:51.98 app_id: '', title 'check for empty appid when mapping · LBCrion/sfwbar@a0c10d2 - Vivaldi'
```

**Comment by LBCrion** [comment]
Try:

MapAppId ".*Vivaldi$", "vivaldi"

**Comment by 01micko** [comment]
:smile:

![success](https://user-images.githubusercontent.com/1019119/181635727-9867d5e2-76d6-4950-bbca-ff1b9e3805cc.png)

**Comment by LBCrion** [comment]
Excellent!

**Comment by 01micko** [comment]
It's using my icon theme too because I have an old vivaldi logo.

Thanks very much!

**Comment by 01micko** [comment]
Using Gimp.Appimage gimp shows up as "Gimp.bin", but my regex isn't escaping the dot so it seems.

```
MapAppId ".*Gimp\.bin$", "gimp"
```

**Comment by LBCrion** [comment]
If memory serves,  you may need to use \\. as single slash in \. gets
translated as a dot in a double quote string.

**Comment by 01micko** [comment]
Sorry for late reply. Tried that, and again ust now but doesn't work

```
MapAppId ".*Gimp\\.bin$", "gimp"
```

**Comment by LBCrion** [comment]
Hmm, I just checked the code an with double backslash, sfwbar is using a
correct pattern. Can you give me an example of a title you're trying to
match so I can test it?

**Comment by 01micko** [comment]
Here you go :)

```
~$ sfwbar -d -g app_id
19:47:39.37 app_id: 'lxterminal', title 'LXTerminal'
19:47:39.37 app_id: 'Gimp.bin', title 'GNU Image Manipulation Program'
```

**Comment by LBCrion** [comment]
MapAppId works by mapping a title pattern to an appid. So in your case,
you'd want to use MapAppId "GNU Image Manipulation Program", "gimp".

**Comment by 01micko** [comment]
Still not working.

What I have:
```
MapAppId "GNU Image Manipulation Program", "gimp".
```
and tried
```
MapAppId ".*GNU Image Manipulation Program$", "gimp".
```

![gimp](https://github.com/LBCrion/sfwbar/assets/1019119/aec89bb3-5d47-45db-b687-989692ab6975)

**Comment by LBCrion** [comment]
That would be because it already has an appid. The MapAppId fallback is
only called if an appid is missing. Are you trying to set a custom icon for
an appid without resorting to the symlink approach? It should be fairly
easy to add this, i.e. a MapIcon command that would allow mapping an appid
to a specific icon name.

**Comment by 01micko** [comment]
I completely forgot about the symlink approach!

```
~/.config/sfwbar$ ln -s ../../../usr/share/icons/Numix-Circle/48/apps/gimp.svg ./Gimp.bin.svg
```

Works :)

**Comment by 01micko** [comment]
![gimp-success](https://github.com/LBCrion/sfwbar/assets/1019119/c72ff7b7-929b-474a-99f3-44cc7bbb7d73)

And there's a preview of my vertical bar with margin :)

**Comment by LBCrion** [comment]
Nice! Btw, if you think appid->icon mapping mechanism would be useful, it would be easy to add, since we now a have a fairly full featured icon lookup implementation.

**Comment by 01micko** [comment]
I'm not sure it is needed as long as the symlink method is in the docs somewhere.

**Comment by LBCrion** [comment]
The only benefit I can see is in case of non-svg icons. With a symlink, we
can only link one icon size. WIth a map, we can pick the most appropriate
size from the icon theme.

**Comment by 01micko** [comment]
yes that is true, so I suppose if you're up for it adding the extra functionality can only be a good thing :)

I often forget that I try to use svg  icons mostly.

**Comment by LBCrion** [comment]
This is now implemented. Action MapIcon (this is an action not a toplevel keyword, so you'll need to add it to SfwbbarInit function). Usage is `MapIcon <app_id>, <icon>`

**Comment by 01micko** [comment]
Works :) once I realised it goes in `SfwBarInit`

```
function("SfwbarInit") {
  SetBarId "panel"
  SetLayer "panel", "bottom"
  SetMonitor "panel", "HDMI-A-1"
  SetBarMargin "5"
  MapIcon "lxtask", "gtk-preferences"
}
```
