### ISSUE TITLE
Icons seem too big in latest

### ISSUE THREAD

**Issue by 01micko** [LBCrion/sfwbar#37]
Seems like the css isn't working, IDK haven't investigated. Icons are larger than they should be.
![20220829_19h03m55s_grim](https://user-images.githubusercontent.com/1019119/187165516-24bc2150-dc21-4ac2-b020-769b26aadfff.png)

Also getting this error if I use [this config](https://github.com/LBCrion/sfwbar/issues/32#issuecomment-1229529237) for sound widget.

```
~$ sfwbar

(sfwbar:2013): GLib-CRITICAL **: 19:01:20.394: g_io_channel_write_chars: assertion 'channel->is_writeable' failed
```

Latest commit.

**Comment by LBCrion** [comment]
Can you try the latest git for the icon issue please? I'm trying to get a well defined sizing behaviour for the images (which were rather hacky before). The new sizing rules should be: 
1. if min-width/height are not defined, image takes up the available space
2. if min-width/height are defined, image is se to this size
3. if min-width/height are defined and -GtkWidget-hexpand/vexpand are set to true, image takes up the available space, subject to minimum size set via min-width/height

For the ExecClient issue, can you try running "pactl subscribe" in the terminal (preferably the same terminal from which you launch sfwbar. The error looks like the command exits (it should keep running and print notifications of any changes to pulseaudio state).

**Comment by 01micko** [comment]
Icons are fixed, thank you.

Ran this:
```
~$ pactl subscribe & sfwbar
[1] 3608
Event 'new' on client #97224
Event 'change' on client #97224
Event 'new' on client #97225
Event 'change' on client #97225
Event 'remove' on client #97225

(sfwbar:3609): GLib-CRITICAL **: 09:12:54.661: g_io_channel_write_chars: assertion 'channel->is_writeable' failed
```

Any ideas?
