### ISSUE TITLE
SNI watcher service startup race condition

### ISSUE THREAD

**Issue by Consolatis** [LBCrion/sfwbar#45]
If you have an SNI client running and then restart sfwbar the SNI client may not recover correctly:
```
(test_ayatana_menu.py:625051): libayatana-appindicator-WARNING **: 22:24:20.703: Unable to connect to the Notification Watcher: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Object does not exist at path “/StatusNotifierWatcher”
```
I monitored the dbus traffic with `dbus-monitor` while it happened and this is the result:

<details><summary>dbus log</summary>

`1:103`: client
`1:105`: sfwbar

```
method call time=1662582260.683590 sender=:1.105 -> destination=org.freedesktop.DBus serial=34 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=RequestName
   string "org.freedesktop.StatusNotifierWatcher"
   uint32 0
signal time=1662582260.683781 sender=org.freedesktop.DBus -> destination=(null destination) serial=275 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameOwnerChanged
   string "org.freedesktop.StatusNotifierWatcher"
   string ""
   string ":1.105"
signal time=1662582260.683914 sender=org.freedesktop.DBus -> destination=:1.105 serial=36 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameAcquired
   string "org.freedesktop.StatusNotifierWatcher"
method return time=1662582260.684019 sender=org.freedesktop.DBus -> destination=:1.105 serial=37 reply_serial=34
   uint32 1
method call time=1662582260.689240 sender=:1.105 -> destination=org.freedesktop.DBus serial=35 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=RequestName
   string "org.freedesktop.StatusNotifierHost-625069"
   uint32 0
signal time=1662582260.690376 sender=org.freedesktop.DBus -> destination=(null destination) serial=276 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameOwnerChanged
   string "org.freedesktop.StatusNotifierHost-625069"
   string ""
   string ":1.105"
signal time=1662582260.691217 sender=org.freedesktop.DBus -> destination=:1.105 serial=38 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameAcquired
   string "org.freedesktop.StatusNotifierHost-625069"
method return time=1662582260.692024 sender=org.freedesktop.DBus -> destination=:1.105 serial=39 reply_serial=35
   uint32 1
method call time=1662582260.693259 sender=:1.105 -> destination=org.freedesktop.DBus serial=36 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=AddMatch
   string "type='signal',sender='org.freedesktop.DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',path='/org/freedesktop/DBus',arg0='org.freedesktop.StatusNotifierWatcher'"
method return time=1662582260.693783 sender=org.freedesktop.DBus -> destination=:1.105 serial=40 reply_serial=36
method call time=1662582260.694197 sender=:1.105 -> destination=org.freedesktop.DBus serial=37 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=GetNameOwner
   string "org.freedesktop.StatusNotifierWatcher"
method return time=1662582260.694343 sender=org.freedesktop.DBus -> destination=:1.105 serial=41 reply_serial=37
   string ":1.105"
method call time=1662582260.697984 sender=:1.103 -> destination=org.freedesktop.DBus serial=47 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=StartServiceByName
   string "org.kde.StatusNotifierWatcher"
   uint32 0
error time=1662582260.698426 sender=org.freedesktop.DBus -> destination=:1.103 error_name=org.freedesktop.DBus.Error.ServiceUnknown reply_serial=47
   string "The name org.kde.StatusNotifierWatcher was not provided by any .service files"
method call time=1662582260.700182 sender=:1.103 -> destination=org.freedesktop.DBus serial=48 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=GetNameOwner
   string "org.kde.StatusNotifierWatcher"
method return time=1662582260.700318 sender=org.freedesktop.DBus -> destination=:1.103 serial=24 reply_serial=48
   string ":1.105"
method call time=1662582260.701506 sender=:1.103 -> destination=:1.105 serial=49 path=/StatusNotifierWatcher; interface=org.kde.StatusNotifierWatcher; member=RegisterStatusNotifierItem
   string "/org/ayatana/NotificationItem/Menu"
error time=1662582260.703074 sender=:1.105 -> destination=:1.103 error_name=org.freedesktop.DBus.Error.UnknownMethod reply_serial=49
   string "Object does not exist at path “/StatusNotifierWatcher”"
```

</details>

Client
- reacts to `NameOwnerChanged`
- sends `RegisterStatusNotifierItem`
- receives `UnknownMethod`
- Gives up

As to why sfwbar returns `UnknownMethod`:
https://github.com/LBCrion/sfwbar/blob/d7a4c76225fa7d11e17872aafd85ffe4dbb1071c/src/sni.c#L312-L315

Starts to own/claim the name and in the callback registers its methods:
https://github.com/LBCrion/sfwbar/blob/d7a4c76225fa7d11e17872aafd85ffe4dbb1071c/src/sni.c#L182-L184

Which are defined here:
https://github.com/LBCrion/sfwbar/blob/d7a4c76225fa7d11e17872aafd85ffe4dbb1071c/src/sni.c#L167-L172

So what happens is that a client tries to talk to the watcher service after it is already owning the "well known" name but before it has initialized its object/callbacks.

A solution could be for the watcher to start by watching or asking for the name (something calling `GetNameOwner`) and if not already set register the object/callbacks and then claim/own the name as the last step.

Or as alternative:
Initializing the watcher (including setting up the object/callbacks) without checking for an existing owner and only then trying to own the name.

Watching for the well known name would additionally provide the benefit that if there is already a watcher running when sfwbar starts up but that other watcher then terminates after some time sfwbar could seamlessly take over.

Something similar might be required for the SNI host service.

**Comment by LBCrion** [comment]
I changed sni initialization to watch for the watcher name becoming available and then registering the interface before claiming the name. I still see cases where the applet doesn't come up upon restart. Not sure if there is another issue somewhere.

**Comment by LBCrion** [comment]
It looks like the remaining case of SNI applets not coming up on restart is in the scenario where SNI watcher returns isStatusNotifierHostRegistered = false.
This is a valid state according to StatusNotifierWatcher spec and in theory the applet should subscribe to StatusNotifierHostRegistered signal, which sfwbar implmentation of StatusNotifierWatcher does emit. 
It looks like the signal our watcher emits is slightly out of spec (we emit the signal with a parameter of a name of a host that connected). I tried changing it to not emit any parameters and the applets still don't reconnect. 

In theory, we can break the spec and just always return isStatusNotifierHost = true; This fixes the problem and applets will always connect to the watcher and the watcher in turn will always send the applets to the host, once it connects, via RegisteredStatusNotifierItems property.

I'm not a fan of breaking the spec and would prefer to check if there is something else I'm missing here.
@Consolatis - do you see anything obvious I may be missing here in implementation of isStatusNotifierHostRegistered/StatusNotifierHostRegistered pair?

**Comment by Consolatis** [comment]
> I still see cases where the applet doesn't come up upon restart. Not sure if there is another issue somewhere.

So far I couldn't reproduce this. Tested with two Python libAyatana applets and also with VLC. Once the panel starts back up all applets reappear for me.

Regarding the host implementation, it seems to request all existing items before subscribing to the signals. This might open (a very narrow) race condition window in that part. Doing it the other way round (subscribing and then getting the existing items) while ignoring duplicates should close that window.

> In theory, we can break the spec and just always return isStatusNotifierHost = true; This fixes the problem and applets will always connect to the watcher and the watcher in turn will always send the applets to the host, once it connects, via RegisteredStatusNotifierItems property.

As a work-around this seems fine to me and shouldn't really break anything. The reason is likely that applications fall back to traditional X11 systray stuff [0]. But that isn't really a thing on wayland anyway.

[0]
https://www.freedesktop.org/wiki/Specifications/StatusNotifierItem/StatusNotifierWatcher/#isstatusnotifierhostregistered
> If no StatusNotifierHost are registered and running, all StatusNotifierItem instances should fall back using the Freedesktop System tray specification.

**Comment by LBCrion** [comment]
I changed the watcher to always return TRUE on isStatusNotifierHostRegistered. Even if host isn't registered it's a matter of milliseconds before it is, so I figured it's not worth messing with this. I also fixed that last race condition in the host code. Thank you!

**Comment by LBCrion** [comment]
Closing, as this seems to be resolved now.
