### ISSUE TITLE
Taskbar group popup acts strange when it contains >1 item

### ISSUE THREAD

**Issue by Vimux** [LBCrion/sfwbar#46]
I tried the new `w10.config` in action and found that it looks strange if the taskbar_group popup contains more than one item. To be precise, if the taskbar popup spawns at least once, it cannot change its dimensions correctly after.

**Reproducing steps:**

1. Open 3 windows of the same program (mpv)
1. Hover over program in the taskbar
1. Close 2 windows

**Screenshot:**

![screenshot_2022-09-10](https://user-images.githubusercontent.com/21033483/189494987-40304c5e-7b45-4289-849b-a2ac6b0d8794.png)

**Video demonstration:**

<details>
  <summary>Spoiler</summary>

https://user-images.githubusercontent.com/21033483/189495014-9cab76d3-fce3-40ed-9b5a-b7237cfcd915.mp4

</details>

**Program version:**

* sfwbar (c8f475907bd78c2301897fb18e8b670605d5c7cc)

**Comment by LBCrion** [comment]
Can you try with the latest git please. It looks like the popup window was never unrealized (and not resized as a result) between popups.

**Comment by Vimux** [comment]
It's working.

---

Off-topic. Is it possible to use this in top or vertical bar mode? Is it possible to change the look and feel? I'm not very familiar with GTK, so my attempts to change the CSS of the taskbar popup and adapt it to my theme were unsuccessful.

**Comment by LBCrion** [comment]
It should be possible to do both, but grouped bars are still a bit of a work in progress.

For vertical bars, the gravity logic still needs a bit of work (currently the popup window is always above the group icon, which doesn't work well for vertical bars). This is something I'm working on fixing, so keep this Issue open and I'll post once it's done.

What type of look and feel are you after? I can try mock something up as I'm developing grouped bar functionality.

**Comment by Vimux** [comment]
Thanks for the clarification.


> What type of look and feel are you after? I can try mock something up as I'm developing grouped bar functionality.

I haven't thought about this too deeply. :smile:
Plus I'm not familiar with the possible limitations, so I only have a couple of random thoughts, nothing more:

* Personally, I'd like to be able to style the taskbar window via CSS in about the same way we can do it now with `menu` (+ `menuitem`). It might be worth trying to unify default look across these elements?
* Ability to specify min and max width size. The elements of the popup depend on the title, so they can be too short or too long.
* Label alignment. Centering might not be to everyone's taste.

**Comment by LBCrion** [comment]
I pushed the fix for the gravity of the popup in taskbar groups, so it should popup in a reasonable place on vertical bars now. You should be able to style the groupped taskbar items via CSS. They follow the usual taskbar item style process. Each item is a button, containing a grid, which in turn contains an icon, a label or both. If you look at CSS of w10.config, the styling is handled wherever you see #taskbar_active or #taskbar_normal.

There is still an issue with groupped icons where the popup gets stuck. I'm working on this one.

**Comment by Vimux** [comment]
> You should be able to style the groupped taskbar items via CSS.

Yeah, that's right, my bad. I was confused about the other thing. If the group is not activated, the `taskbar_normal` and `taskbar_active` are responsible for the appearance of the taskbar elements; if the group is enabled, the same IDs are responsible for the popup elements. It makes sense, but you wouldn't expect this behavior at first glance.

**Comment by LBCrion** [comment]
This is indeed a bit unintuitive at first, but the logic is as following: in a grouped taskbar, the taskbar is split into multiple groups. The main bar now contains groups rather than individual items. And the actual items spill into popups associated with each group.

**Comment by LBCrion** [comment]
A few things I didn't address above: 
1. Taskbar group popup window size - you can control the min size by setting min-width for taskbar items. There is no way to explicitly specify the maximum size of a taskbar group popup window, but you can specify ``group title_width`` option in taskbar declaration to limit the max number of characters displayed for window titles.
2. You can change text alignment for window titles using -GtkWidget-align CSS property. It accepts values between 0 to 1, 0 being left justified and 1 being right justified.
3. In the last git you can also use -GtkWidget-halign/valign options to control widget placement within any free space allocated to them (valid values for these are fill, center, start, end and baseline).

**Comment by Vimux** [comment]
> ... There is no way to explicitly specify the maximum size of a taskbar group popup window, but you can specify group title_width option in taskbar declaration to limit the max number of characters displayed for window titles.

It doesn't work for me. Yes, it works for taskbar items, but never for popup items. I even looked for something similar, like `max-width-chars` or anything else. Maybe I'm just missing something again.

I tried the latest git version with `w10.config`, but nothing has changed.

<details>
  <summary>Taskbar options</summary>
  
```
  taskbar {
    rows = 1
    group = true
    group cols = 1
    group style = "taskbar_group"
    group labels = true
    group icons = true
    group title_width = 3
    title_width = 3
    icons = true
    labels = true
    filter_output = true
    action[3] = Menu "winops"
  }
```
  
</details>

**Comment by LBCrion** [comment]
Oops. That was a typo in the code. It should be fixed in the current git version. Would you mind trying again? And thank you for flagging it!

**Comment by Vimux** [comment]
It works. Fixed.

**Comment by LBCrion** [comment]
Closing this, as it seems resolved. Please feel free to reopen if anything is still outstanding.
