### ISSUE TITLE
SetLayer does not work for me

### ISSUE THREAD

**Issue by Flrian** [LBCrion/sfwbar#47]
See title, basically it seems to be always set to top regardless of what I use as config.

<details><summary>my config in case I did manage to screw up somewhere</summary>

```  
function("SfwbarInit") {
  SetBarId "bar-0"
  SetLayer "bottom"
#  SetExclusiveZone "-1"
#  SetMonitor "eDP-1"
#  SetBarSize "800" 
}

function("ToggleMinimize") {
  [!Minimized] Minimize
  [Minimized] UnMinimize
}

function("ToggleMaximize") {
  [!Maximized] Maximize
  [Maximized] UnMaximize
}

menu("winops") {
  item("UnMinimize", Function "ToggleMinimize" );
  item("UnMaximize", Function "ToggleMaximize" );
  item("Focus", Focus );
  item("Close", Close );
}

# Panel layout

layout {

  # menu
  label {
    style = "awesome"
    value = ""
    css = "* { padding: 0px 8px 0px 8px; }"
    action = ""
  }

  # launcher
  button {
    style = "test"
    action = "firefox"
    value = "firefox"
    css = "* { padding: 0px; }"
  }

  # taskbar
  taskbar {
    css = "* { -GtkWidget-vexpand: true; min-height: 34px; }"
    icons = true
    labels = true
    rows = 1
    action[3] = Menu "winops"
    title_width = 20
  }

  # spacer
  label {
	css = "* { -GtkWidget-hexpand: true; background-color: rgba(0,0,0,0); }"
	value =""
  }

#  include("idle.widget")
#  include("usage.widget")
#  include("mpd-mini.widget")
#  include("weather.widget")

  grid {
    style = "frame_temp"
    css = "* { -GtkWidget-direction: right; }"
    include("cpu-temp.widget")
    include("gpu-temp.widget")
  }

  tray
  include("clock.widget")

}

#CSS

window {
	-GtkWidget-direction: bottom;
	/* background-color: rgba(0,0,0,0); */
}

button#taskbar_normal image, button#taskbar_active image, button#taskbar_normal:hover image {
	min-width: 16px;
	min-height: 16px;
	padding: 0px;
}

button#taskbar_normal label, button#taskbar_active label, button#taskbar_normal:hover label {
	padding: 0px;
	padding-left: 2px;
	font: 9pt Inter;
}

button#taskbar_normal , button#taskbar_active , button#taskbar_normal:hover {
	background-image: none;
	/* border-radius: 0;
	border-image: none; */
	margin: 4px 2px;
	padding: 0px 4px;
	min-width: 140px;
}

button#taskbar_active {
	background-color: #bbddff;
}

button#taskbar_normal:hover {
	background-color: #cccccc;
}

button#tray_active,
button#tray_passive,
button#tray_attention {
	padding: 0px;
	background-color: rgba(0,0,0,0);
}

button#tray_active image,
button#tray_passive image,
button#tray_attention image {
	-GtkWidget-hexpand: true;
	-GtkWidget-vexpand: true;
	padding: 2px;
	min-width: 16px;
	min-height: 16px;
}

progressbar {
	padding-left: 0.25mm;
	padding-right: 0.25mm;
	-GtkWidget-direction: top;
}

progress, trough {
	border-radius: 0;
	border-color: #9c9c9c;
}

progress {
	border-style: outset;
	min-width: 2mm;
}

trough {
	background-color: #a1a1a1;
	border-style: inset;
	min-height: 2.5mm;
	min-width: 2.5mm;
}

grid#frame {
	-GtkWidget-direction: right;
}

grid#layout {
	-GtkWidget-direction: right;
}

image#label {
	padding: 4px;
}

label#cpu-temp_icon, label#gpu-temp_icon {
	font-family: "Font Awesome 5 Free";
	font-weight: 900;
}

button#idle_inhibit {
}

label {
	font: 8pt Sans;
	color: #000000;
}

tooltip label {
	color: #cccccc;
}

label#awesome {
	font-family: "Font Awesome 5 Free";
	font-weight: 900;
}

label#date {
	font-family: Inter;
	font-size: 9pt;
	padding-left: 8px;
}

label#time {
	font-family: Inter;
	font-size: 12pt;
	padding-right: 8px;
}

label#value {
	padding: 0px;
}

grid#frame_temp {
	-GtkWidget-direction: right;
	padding-left: 8px;
	padding-right: 8px;
}

* {
	-GtkWidget-vexpand: true;
}
```
</details>

Also another quick one. I can't seem to reduce the height of buttons (except the taskbar ones), any idea what I might be doing wrong there? The width seems to reduce just fine if I set the padding to 0.. I have no idea what I'm doing with css.
![1663263917_grim](https://user-images.githubusercontent.com/4444593/190476634-2190092c-00c1-47cc-90bf-858c9703f0a0.png)

**Comment by Consolatis** [comment]
> I can't seem to reduce the height of buttons (except the taskbar ones), any idea what I might be doing wrong there

I don't see any button config for it in your config, I use something like this:
```
#launcher {
	padding: 0;
	margin: 0;
	border: 0;
	border-radius: 0;
	background: none;
}
```
In your case the selector would be `#test` or `button#test`. Not sure if it would solve the issue though.

**Comment by LBCrion** [comment]
Which compositor are you using? I tested your config on sway and it correctly placed the bar on the bottom layer for me (i.e. any window overlapping it covered the bar).

For the button sizing, the button by default has vertical "fill" alignment, so it stretches to occupy all available space. Coincidentally, I added support for controlling widget alignments a couple hours before you posted this issue! So, with the latest git, you can set button css to:
```css = "* { padding: 0px; -GtkWidget-valign: center; }"```
If you want to make this work on an older version of sfwbar, you can set the button as vertically non-expandable and wrap it in a grid. But you will then need to figure out vertical centering as well (probably via padding around the button):
```
  grid {
    button {
      style = "test"
      action = "firefox"
      value = "firefox"
      css = "* { padding: 0px; -GtkWidget-vexpand: false; }"
    }
  }
```

**Comment by LBCrion** [comment]
> ^ You can probably ignore all that. I started over with the default oneline.config because of the css and figured out that SetLayer only seems to work for me if I also use SetMonitor (Even with that set to "eDP-1" when my actual monitor is "HDMI-A-1").

This is odd. SetMonitor should be completely unconnected to SetLayer. I just tested the current git version of sfwbar with current git version of labwc and the config you posted correctly goes to the bottom layer for me. Are you using the git version of sfwbar or one of the releases?

**Comment by LBCrion** [comment]
> Thank you for the help with the css, I managed to get it working after starting over and using the snippet you posted! I noticed a thing however, when using the default oneline.config I get a bunch of `(sfwbar:6650): Gtk-WARNING **: 10:56:12.601: Theme parsing error: <data>:1:0: Expected an identifier`, everything seems to work fine though.

This one at least is an easy one to fix. I forgot to remove a line after running some tests. Should be fixed in the latest git.

**Comment by LBCrion** [comment]
> Latest git version of both sfwbar and labwc.

Can you try adding these two lines after gtk_layer_set_layer(GTK_WINDOW(bar),layer); in line 159 of bar.c:
```
  gtk_widget_hide(bar);
  gtk_widget_show(bar);
```
And see if this helps (if you don't use SetMonitor).

**Comment by LBCrion** [comment]
What version of gtk-layer-shell do you use? I don't seem to be able to reproduce this behavior with any compositor locally. Makes me wonder if some version of gtk-layer-shell behave this way.

**Comment by LBCrion** [comment]
It's gtk-layer-shell. I used old 0.1.0 version,  which didn't need this.
0.7.0 does need extra code.
