### ISSUE TITLE
First click on taskbar button doesn't unminimize window

### ISSUE THREAD

**Issue by Flrian** [LBCrion/sfwbar#48]
Using labwc and latest sfwbar git. Easiest to see if you only have one application open.
1. Minimize window by clicking on taskbar button (See how it also stays blue, should mean it is still activated, right?)
2. Click on taskbar button again, now it should unminimize but doesn't. (Only now does the button change to grey.)
3. Click again, now it does unminimize.

If you look at the video you can also see how the state doesn't change. I'm using [wl_framework](https://github.com/Consolatis/wl_framework) to monitor that.
I've also tried it with the default oneline.config, same behavior.

https://user-images.githubusercontent.com/4444593/190834460-62da8fc4-3614-4c22-9ed9-83fd7f9afda8.mp4

**Comment by LBCrion** [comment]
Can you try with the latest git please? It looks like the last window goes
into active+minimized state, which is a bit of an exception to the usual
behaviour (window usually loses focus on minimize event).

**Comment by LBCrion** [comment]
The window remaining active is unfortunately something sfwbar doesn't have
control over.  The bar talks to the compositor via wlr foreign toplevel
protocol. Protocol allows activating,  but not deactivating windows.
Usually, compositors deactivate a window once it's minimised, but labwc
seems to make an exception for the last window.

> Initial setup was a bit intimidating while getting to know the config
format but I really like the bar so far, great work! :)

Thank you! I try to err on the side of more features over simplicity.
Amusingly,  I think this bug could have been fixed without a code change.
Config does allow assigning a custom function to the left click action and
an action can have conditional commands to implement this behaviour.

**Comment by Consolatis** [comment]
> It looks like the last window goes
> into active+minimized state, which is a bit of an exception to the usual
> behaviour (window usually loses focus on minimize event).

If that is the case its a bug in labwc and should be fixed. I'll look into it again.

**Comment by LBCrion** [comment]
@Consolatis, I'm not sure I'd call this a bug. Whether minimizing the last window should cause it to lose focus or not can certainly be debated (per @Flrian's comment, wayfire has the same behaviour as labwc).

@Flrian, just in case, the config route to fixing this would be:
```
function("FocusOrMinimize") {
  [!Focused] Focus
  [Focused | Minimized] Focus
  [Focused | !Minimized] Minimize
}
```
and in the taskbar declaration:
```
action = Function "FocusOrMinimize"
```

**Comment by Consolatis** [comment]
That wouldn't fix the CSS id of the tray buttons though.

**Comment by LBCrion** [comment]
Do you mean the button for the last window will retain focused style when
minimised? I don't think we want to change this.  If the window is still
considered active by the compositor,  the bar should mark it as such.

**Comment by Consolatis** [comment]
@Flrian it is absolutely relevant. Thanks for finding that commit.,maybe it doesn't completely fix the issue. I'll try to verify this tonight.

**Comment by Consolatis** [comment]
It seems the state is set somewhat correctly:
```
08:35:06.30 new state for 0xaaaaaadfcc00: Activated,
08:35:09.74 new state for 0xaaaaaadfcc00: Activated, Minimized,
08:35:09.74 new state for 0xaaaaaadfcc00: Minimized,
```

This will likely break other stuff but seems to solve the visually active taskbar button even though the last state didn't contain the `active` flag.
```diff
diff --git a/src/wayland/foreign-toplevel.c b/src/wayland/foreign-toplevel.c
index d0a6ce9..7a6150d 100644
--- a/src/wayland/foreign-toplevel.c
+++ b/src/wayland/foreign-toplevel.c
@@ -75,9 +75,17 @@ static void toplevel_handle_state(void *data, wlr_fth *tl,
       win->state |= WS_FULLSCREEN;
       break;
     case ZWLR_FOREIGN_TOPLEVEL_HANDLE_V1_STATE_ACTIVATED:
+      win->state |= WS_FOCUSED;
       wintree_set_focus(win->uid);
       break;
     }
+
+  g_message("new state for %p: %s%s%s%s", win->uid,
+    win->state & WS_FOCUSED ? "Activated, " : "",
+    win->state & WS_MINIMIZED ? "Minimized, " : "",
+    win->state & WS_MAXIMIZED ? "Maximized, " : "",
+    win->state & WS_FULLSCREEN ? "Fullscreen" : ""
+  );
 }

 static void toplevel_handle_parent(void *data, wlr_fth *tl, wlr_fth *pt)
diff --git a/src/wintree.c b/src/wintree.c
index ca10bdf..512382e 100644
--- a/src/wintree.c
+++ b/src/wintree.c
@@ -74,7 +74,11 @@ gpointer wintree_get_focus ( void )

 gboolean wintree_is_focused ( gpointer id )
 {
-  return ( id == wt_focus );
+  window_t *win;
+  win = wintree_from_id(id);
+  if(!win)
+    return FALSE;
+  return (win->state & WS_FOCUSED) != 0;
 }

 window_t *wintree_from_id ( gpointer id 
```

**Comment by LBCrion** [comment]
Thank you. I added this to the current git version (slightly modified to
fit with the wintree abstraction).
