### ISSUE TITLE
Vertical sfwbar

### ISSUE THREAD

**Issue by devosalain** [LBCrion/sfwbar#50]
Is there a procedure to have a vertical sfwbar on the left of the screen ?

**Comment by LBCrion** [comment]
The example config file vertical.config places sfwbar on the left side of the screen.

**Comment by devosalain** [comment]
This did not worked for me. In that case no bar was seen. Should you change a .css file s?

**Comment by LBCrion** [comment]
This shouldn't be happening. Which compositor (and version) are you using and which version of sfwbar? Are you starting it with sfwbar -f vertical.config? 
Can you check if there is a local copy of old vertical.config somewhere (usually in ~/.config/sfwbar) or is there is vertical.css there?

**Comment by devosalain** [comment]
I use labwc-0.5.3                    Wayland stacking compositor
and t2.config which works very fine.
But vertical.config shows nothing.
I did  a git pull & build so i have the latest version of sfwbar.

**Comment by LBCrion** [comment]
This sounds like an issue with mpd client then.  Do you have an mpd server
running? Can you post the mpd related output from sfwbar -d ?

**Comment by LBCrion** [comment]
Closing this, since mpd support has been completely rewritten in the last couple of years. Please feel free to reopen if you still encounter this issue.
