### ISSUE TITLE
Hyprland Minimize, Maximize, Focus not working

### ISSUE THREAD

**Issue by Karagra** [LBCrion/sfwbar#51]
Hello was wondering if you could add support for those features to work with hyprland? 
https://github.com/hyprwm/Hyprland 
I am not sure if this is even possible but I did see a feature called "special workspaces" that might be what would be used..

**Comment by LBCrion** [comment]
Oof. This is a fun one. Looking at Hyprland, it doesn't support minimize or maximize requests of the foreign toplevel protocol. It does however have it's own socket based IPC (which of course differs from that of sway), and it does have the concept of a scratchpad (special workspace) to park the windows.
The bad news is that to get minimize/maximize functionality, we'll need to implement full support for this IPC, which is a significant piece of work.
The good news is that we already support sway IPC protocol so have all the abstractions in place and it's a question plumbing another protocol into these.
The even better news is that Hyprland is one of the compositors with experimental support of ext-workspace wayland protocol which gives me a very good excuse to add support for it.

**Comment by Karagra** [comment]
Well thats good news! Thanks for the quick response

**Comment by Consolatis** [comment]
> The bad news is that to get minimize/maximize functionality, we'll need to implement full support for this IPC, which is a significant piece of work.

Maybe they would instead be open to emulate the minimize and maximize requests via foreign toplevel protocol?
That would allow all panels to work instead of further fragmentation via yet another custom IPC solution.

> The even better news is that Hyprland is one of the compositors with experimental support of ext-workspace wayland protocol which gives me a very good excuse to add support for it.

That would actually be nice. We (labwc) would love to implement ext-workspace if it is ever [merged](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/40) into wayland-protocols so having a nice panel to test our implementation would be very useful.

**Comment by LBCrion** [comment]
I've been playing with Hyprland IPC and I can probably make the bar work with it, but there are some limitations:
1) There is no way to get current state of windows - i.e. if the bar is started after some windows are already open or the bar is restarted, there is no way to tell which windows are maximized. Once the bar is running it should be able to keep track of window states.
2) Minimizing windows will be a complex. Special workspace doesn't allow floating windows (unlike sway's scratchpad), so to minimize window we'll need to save it's geometry, change it to tiled, move it special workspace. To unminimize, we'll move back to it's original workspace, flip it to floating and restore it's geometry.
3) Using the IPC, we can probably support features currently supported for sway, but not wayland IPC - i.e. placer and pager.
My biggest problem with testing so far has been stability, I've experienced random lockups and crashes a few times, which makes testing code difficult.

@Karagra, do you think Hyprland developers would be open to supporting maximize and minimize commands via wlr foreign toplevel protocol? Hyprland implements support for the protocol and implements support for maximize command outside of the protocol, so it should be just a matter of plumbing the two together. Minimize would be more work I guess.

**Comment by LBCrion** [comment]
@Consolatis, the older version of ext-workspace would explain why my test code failed to register the protocol. I'll play with the older version when I get a chance, but I guess it's not the best test platform for the current protocol.

**Comment by vaxerski** [comment]
> Hyprland developers

thank you for recognizing my 19 personalities.

I can of course make the toplevel minimize request handled, but the most important question would be how? Can't see a good solution for such things on a *tiling* window manager.

We could indeed use the special workspace (i3: scratchpad) for that. The reasons why the special workspace doesn't support floating windows was mostly due to me being lazy. Floating windows there were creating a bit of code clashing with moving them around and shiz.

Regarding maximize - yeah sure that makes sense.

**Comment by vaxerski** [comment]
> Be aware though that Hyprland seems to use an older version of the protocol which has minor naming differences

yeah thats what you get for protocols that aren't merged yet. Got the protocol a couple months ago and haven't touched it since.

**Comment by LBCrion** [comment]
> I can of course make the toplevel minimize request handled, but the most important question would be how? Can't see a good solution for such things on a _tiling_ window manager. 
> We could indeed use the special workspace (i3: scratchpad) for that. The reasons why the special workspace doesn't support floating windows was mostly due to me being lazy. Floating windows there were creating a bit of code clashing with moving them around and shiz.

I think using the special workspace is the most sensible solution in the tiling world. That's what most users use in lieu of minimzie. Simply binding the minimize request to move to special workspace action and uniminize to move back to the original workspace should do the trick. (but of course would need some way of moving floating windows to special workspace).

> Regarding maximize - yeah sure that makes sense.

While on this topic, would it be possible to add window state info to IPC /clients request? I.e. information on whether the window is focused, maximized or minimized (if supported) or fullscreen.

**Comment by LBCrion** [comment]
> > Be aware though that Hyprland seems to use an older version of the protocol which has minor naming differences
> 
> yeah thats what you get for protocols that aren't merged yet. Got the protocol a couple months ago and haven't touched it since.

This is understandable and expected. I don't expect to maintain any code I write for this until the protocol is merged either.

**Comment by LBCrion** [comment]
@Karagra, I pushed initial hyprland IPC support into main git branch. At this point it loads the window list and follows focus, but non of the actions are working yet.

**Comment by vaxerski** [comment]
Hyprland now handles the maximize requests https://github.com/hyprwm/Hyprland/commit/ead0e744714891f9b56469347f43b7e4e334f441

I'll try to get the floating windows working when I have some time if I don't forget.

**Comment by LBCrion** [comment]
@vaxerski , thank you! 
 And while it's Christmas,  would it be possible to get active and visible workspaces via ipc? Probably best to include these in workspaces request. I.e. "active" boolean for currently selected workspace and "visible" boolean for workspaces currently visible on all monitors.

**Comment by LBCrion** [comment]
> it's already in the `monitors` request though
Indeed I can! Thanks, will use this.

**Comment by LBCrion** [comment]
The current version should support pager functionality, including previews.

**Comment by LBCrion** [comment]
@vaxerski, it looks like openwindow ipc event is currently emitted before the window size is known ("clients" request right after openwindow event returns size of 5x5). This makes placing the window tricky. Would it be very complicated to emit it after the size has been determined? Or is there a way to watch for another ipc event that would tell me when the newly open window has been mapped and the size is known?

**Comment by vaxerski** [comment]
it's known by then, but fixed in e4527c6b60c524aa7f78e47c4e1be32215f0604b

**Comment by LBCrion** [comment]
Window placement should work now. Which brings hyprland functionality to par with sway. The only issue I see is focusing windows. focuswindow dispatcher focuses a floating window, but doesn't raise it. I do use follow_mouse=0 and no_cursor_warps=true in my hyprland config.
@Karagra, would you mind torture testing the bar to see if you can find anything that doesn't work?

**Comment by LBCrion** [comment]
Hi @Karagra, have you found any bugs in hyprland IPC support?

**Comment by Karagra** [comment]
Hey sorry I went MIA for a bit, I am back now though sorry about that!
 Everything works that you added. I have a few small issues but I think those are on me.
1.Left clicking on "launcher" icons sometimes opens a different "launcher" for example if I click firefox sometimes it opens my foot terminal launcher..
2.Left Clicking a taskbar icon to minimize then remaximize puts the mouse over the window as focus instead of keepign the mouse on the taskbar below.

**Comment by LBCrion** [comment]
The mouse jumps can be disabled in your hyprland config.  I believe you need to set no_mouse_warps to true in the general section. 

The launcher mix-ups are more worrying.  Do these happen randomly or does it always happen to some launchers and not others?

**Comment by Karagra** [comment]
you were right setting no_cursor_warps = 1 fixed this issue.. Also turns out I had set "image" and not "button" swapping it to button fixed the issue.

**Comment by Karagra** [comment]
Before I close this.. how would I get this working on 2 monitors? I tried
`function("SfwbarInit") {
  SetBarId "bar-1"
  SetLayer "top"
  SetMonitor "DP-2"
#  SetBarSize "bar1","800" 
}

function("SfwbarInit") {
  SetBarId "bar-0"
  SetLayer "top"
  SetMonitor "DP-3"
#  SetBarSize "bar1","800" 
}`

But thats me stringing it together hoping for the best lol

**Comment by 01micko** [comment]
Try something like this

```
function("SfwbarInit") {
  SetLayer "bar-1", "top"
  SetMonitor "bar-1", "DP-2"
  SetBarSize "bar-1", "800"
  SetLayer "bar-0", "top"
  SetMonitor "bar-0", "DP-3"
  SetBarSize "bar-0", "800"
}
```

**Comment by Karagra** [comment]
yeah nothing hmm

**Comment by LBCrion** [comment]
To have multiple bars,  you need to have multiple layouts in your config,
I.e. for the above unit function,  you will need:

Layout "bar-0" {
...
}

Layout "bar-1" {
...
}

You can just copy the same layout section of you want the same bar on two
monitors.

**Comment by 01micko** [comment]
I forgot to mention that!

**Comment by Karagra** [comment]
That was it! Thanks

**Comment by iggut** [comment]
Hi, apologies for reviving an old issue. I was not sure if I should post a new one or not. 
I was using version beta 9 on Hyprland running in NixOS and everything (some app icons did not show up) was working. I was able to minimize, restore, focus, use pager and close windows. 
After installing beta 10, all taskbar interaction with open windows, switcher and pager stopped working. Although the missing icons are now all there lol. I tried the example configs to make sure I did not mess something up in my config and got the same results.
I am still learning, any help would be highly appreciated.

**Comment by LBCrion** [comment]
This is a bug indeed. Can you please try with the latest git version? It should be fixed now.

**Comment by iggut** [comment]
> This is a bug indeed. Can you please try with the latest git version? It should be fixed now.

Sadly on nixos I am only able to compile a364a31ff9a10b0a1ec36597ea2fc24d7bd3f88e https://github.com/LBCrion/sfwbar/tree/a364a31ff9a10b0a1ec36597ea2fc24d7bd3f88e
Anything after you add bsdctl throws an error on NixOS and prevents me from compiling.
Error:
`  ~ ❯ cd Documents/GamiNiX-main                                                                                        impure  23:05:56
  ~/Documents/GamiNiX-main ❯ bash install.sh                                                                           impure  23:06:10
Hello iggut!
Have you customized the setup to your needs? [y/N] y
[sudo] password for iggut:           
Removing firefox profiles ini for iggut...
building the system configuration...
error: builder for '/nix/store/z88n1c0w1wrgbg9r91192rak28lgx2ww-sfwbar-git.drv' failed with exit code 1;
       last 10 log lines:
       > [33/71] Compiling C object sfwbar.p/src_switcheritem.c.o
       > [34/71] Compiling C object sfwbar.p/src_taskbargroup.c.o
       > [35/71] Compiling C object sfwbar.p/src_taskbaritem.c.o
       > [36/71] Compiling C object sfwbar.p/src_wintree.c.o
       > [37/71] Compiling C object sfwbar.p/src_scanner.c.o
       > [38/71] Compiling C object sfwbar.p/src_hypr_ipc.c.o
       > [39/71] Compiling C object sfwbar.p/src_sway_ipc.c.o
       > [40/71] Compiling C object sfwbar.p/src_expr.c.o
       > [41/71] Compiling C object sfwbar.p/src_basewidget.c.o
       > ninja: build stopped: subcommand failed.
       For full logs, run 'nix log /nix/store/z88n1c0w1wrgbg9r91192rak28lgx2ww-sfwbar-git.drv'.
error: 1 dependencies of derivation '/nix/store/dnasfkbmxim2909shh9c23g4yjiz4f36-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/nxyhj95s17jrpqkpydhksv28z76iirhl-nixos-system-nixos-23.05.20230417.f00994e.drv' failed to build
Nix generation was successful!
Rebooting, abort by pressing 'CTRL + C'
Rebooting in 8 seconds...^C
  ~/Documents/GamiNiX-main ❯ nix-prefetch-github --rev 83678203cd84310c7b4d88de65f9458aea5f37e7 LBCrion sfwbar
{
    "owner": "LBCrion",
    "repo": "sfwbar",
    "rev": "83678203cd84310c7b4d88de65f9458aea5f37e7",
    "sha256": "REzQMCcL6UF0xhGocHbN6QxEAXXCLWZZEmAx4mBk1LY=",
    "fetchSubmodules": false,
    "leaveDotGit": false,
    "deepClone": false
}
  ~/Documents/GamiNiX-main ❯ bash install.sh                                                                           impure  23:07:29
Hello iggut!
Have you customized the setup to your needs? [y/N] y
Removing firefox profiles ini for iggut...
building the system configuration...
error: builder for '/nix/store/0xyhg8dps7j3x6fsxbgm5d153nrzz6ia-sfwbar-git.drv' failed with exit code 1;
       last 10 log lines:
       > [33/71] Compiling C object sfwbar.p/src_wintree.c.o
       > [34/71] Compiling C object sfwbar.p/src_taskbaritem.c.o
       > [35/71] Compiling C object sfwbar.p/src_taskbargroup.c.o
       > [36/71] Compiling C object sfwbar.p/src_scanner.c.o
       > [37/71] Compiling C object sfwbar.p/src_jpath.c.o
       > [38/71] Compiling C object sfwbar.p/src_sway_ipc.c.o
       > [39/71] Compiling C object sfwbar.p/src_exprlib.c.o
       > [40/71] Compiling C object sfwbar.p/src_hypr_ipc.c.o
       > [41/71] Compiling C object sfwbar.p/src_basewidget.c.o
       > ninja: build stopped: subcommand failed.
       For full logs, run 'nix log /nix/store/0xyhg8dps7j3x6fsxbgm5d153nrzz6ia-sfwbar-git.drv'.
error: 1 dependencies of derivation '/nix/store/hcrr20zkivl6gmgrf1pkg5mmlzsn5gyn-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/di3jl41ida9ngl3g65v655lbj09lvgsp-nixos-system-nixos-23.05.20230417.f00994e.drv' failed to bucompilation terminated.
[11/71] Compiling C object xkbmap.so.p/modules_xkbmap.c.o
[12/71] Compiling C object mpd.so.p/modules_mpd.c.o
[13/71] Compiling C object pulsectl.so.p/modules_pulsectl.c.o
[14/71] Compiling C object network.so.p/modules_network.c.o
[15/71] Compiling C object sfwbar.p/src_misc.c.o
[16/71] Compiling C object sfwbar.p/src_button.c.o
[17/71] Compiling C object sfwbar.p/src_client.c.o
[18/71] Compiling C object sfwbar.p/src_grid.c.o
[19/71] Compiling C object sfwbar.p/src_switcheritem.c.o
[20/71] Compiling C object sfwbar.p/src_image.c.o
[21/71] Compiling C object sfwbar.p/src_cchart.c.o
[22/71] Compiling C object sfwbar.p/src_chart.c.o
[23/71] Compiling C object sfwbar.p/src_css.c.o
[24/71] Compiling C object sfwbar.p/src_scale.c.o
[25/71] Compiling C object sfwbar.p/src_label.c.o
[26/71] Compiling C object sfwbar.p/src_flowitem.c.o
[27/71] Compiling C object sfwbar.p/src_expr.c.o
[28/71] Compiling C object sfwbar.p/src_taskbar.c.o
[29/71] Compiling C object sfwbar.p/src_sfwbar.c.o
[30/71] Compiling C object sfwbar.p/src_bar.c.o
[31/71] Compiling C object sfwbar.p/src_menu.c.o
[32/71] Compiling C object sfwbar.p/src_switcher.c.o
[33/71] Compiling C object sfwbar.p/src_wintree.c.o
[34/71] Compiling C object sfwbar.p/src_taskbaritem.c.o
[35/71] Compiling C object sfwbar.p/src_taskbargroup.c.o
[36/71] Compiling C object sfwbar.p/src_scanner.c.o
[37/71] Compiling C object sfwbar.p/src_jpath.c.o
[38/71] Compiling C object sfwbar.p/src_sway_ipc.c.o
[39/71] Compiling C object sfwbar.p/src_exprlib.c.o
[40/71] Compiling C object sfwbar.p/src_hypr_ipc.c.o
[41/71] Compiling C object sfwbar.p/src_basewidget.c.o
ninja: build stopped: subcommand failed.`

This is the .nix file I use to compile and install sfwbar:
`{
  lib,
  stdenv,
  fetchFromGitHub,
  meson,
  ninja,
  pkgconfig,
  wrapGAppsHook,
  gtk3,
  libpulseaudio,
  libmpdclient,
  libxkbcommon,
  gtk-layer-shell,
  json_c,
  glib,
}:
stdenv.mkDerivation rec {
  pname = "sfwbar";
  version = "git";

  src = fetchFromGitHub {
    owner = "LBCrion";
    repo = pname;
    rev = "a364a31ff9a10b0a1ec36597ea2fc24d7bd3f88e";
    sha256 = "4VTOgvj+td1lq4+qgoAUInFRfTFYpXyXv91BHD5Q1GE=";
  };

  nativeBuildInputs = [
    meson
    ninja
    pkgconfig
    wrapGAppsHook
  ];
  buildInputs = [gtk3 gtk-layer-shell json_c glib libpulseaudio libmpdclient libxkbcommon];

  #mesonFlags = [];

  doCheck = false;

  postPatch = ''
    sed -i 's|gio/gdesktopappinfo.h|gio-unix-2.0/gio/gdesktopappinfo.h|' src/scaleimage.c
  '';

  meta = with lib; {
    description = "Sway Floating Window Bar";
    homepage = "https://github.com/LBCrion/sfwbar";
    license = licenses.lgpl21Plus;
    platforms = platforms.unix;
  };
}`

**Comment by LBCrion** [comment]
Interesting,  bsdctl shouldn't be built by default. Do you know how nixos
configures meson? Does it enable all features by default? To explicitly
disable it,  you can configure meson with -Dbsdctl=disabled . I've not used
nixos myself,  but maybe try adding this to mesonFlags?

**Comment by LBCrion** [comment]
Ah. It looks like nixos sets meson auto features to enabled,  try adding
this to your .nix file: mesonAutoFeatures = auto;

**Comment by iggut** [comment]
mesonFlags = [
        "-Dbsdctl=disabled"
      ]
Like you suggested earlier worked :D Only saw the last msg just now.
The interaction with workspaces now works, minimizing and focus taskbar
items also works. Bringing back minimized windows is not possible though.

**Comment by LBCrion** [comment]
It looks like window addresses in hyprland are now using at least 96bit
identifier. 64bit used to be enough. I'll need to update the ipc code to
account for this.

**Comment by vaxerski** [comment]
No, we now use 64-bit. We used 32 before.

**Comment by LBCrion** [comment]
Indeed, my bad. I was assuming 32bit in sfwbar. This should be fixed now. 
@vaxerski - it looks like "movewindow" event isn't emitted on .socket2.sock anymore when the window moves to a new workspace. Is this intentional? I think this is the remaining problem with the "minimize" functionality in sfwbar (since minimize is really just moving the window to/from the special workspace).

**Comment by vaxerski** [comment]
bug

**Comment by vaxerski** [comment]
fixed

**Comment by LBCrion** [comment]
Awesome! Thank you @vaxerski. Just tested with the hyprwm/hyprland@c0f4e9f and minimize is working again.
@iggut - please let me know if you still see any issue with the latest git versions of sfwbar and hyprland.

**Comment by iggut** [comment]
@LBCrion Thank you for such quick replies. I am waiting on a fix [Hyprland/issues/2120](https://github.com/hyprwm/Hyprland/issues/2120) to be able to test this. The latest hyprland fails to build because of missing **wayland: 1.21.0 -> 1.22.0 #226283** in nixpkgs

[`github:hyprwm/Hyprland/2df0d034bc4a18fafb3524401eeeceaa6b23e753`](https://github.com/hyprwm/Hyprland/tree/2df0d034bc4a18fafb3524401eeeceaa6b23e753)
is the last Hyprland nix can use for now and it is affected by the bug when using the latest sfwbar commit.

**Comment by iggut** [comment]
> Awesome! Thank you @vaxerski. Just tested with the [hyprwm/Hyprland@c0f4e9f](https://github.com/hyprwm/Hyprland/commit/c0f4e9f) and minimize is working again. @iggut - please let me know if you still see any issue with the latest git versions of sfwbar and hyprland.

fixed! :dancers:
