### ISSUE TITLE
Width for taskbar items

### ISSUE THREAD

**Issue by joshuataylor** [LBCrion/sfwbar#54]
Hi!

I'm trying to set a width for the taskbar items, similar to the way XFCE works here: https://i.imgur.com/dsjdjUO.png , where the taskbar items have a max width, then there is whitespace until the end of the items.

Is this possible through sfwbar (or gtk(?))?

I'm not completely sure how it works, but from what I can see you can't set a max width?

When setting my taskbar like this:
```
  taskbar {
    rows = 1
    style = "taskbar"
    icons = true
    labels = true
    filter_output = true
    action[3] = Menu "winops"
    title_width = 15
    sort = false
  }
```

then setting my CSS like this:
```css
grid#taskbar button { 
    min-width: 200px;
}
```

This seems to show okay, but the grid is next to the taskbar (and then the items):
![image](https://user-images.githubusercontent.com/225131/197541435-e2d1d756-011e-43c9-98d5-2f7c6636455b.png)

Is there a way to add a spacer or something in between the items and the grid, where the items can take the full width if there are enough items?

(I'm using the latest git builds)

**Comment by Consolatis** [comment]
A max-width setting would be really neat.
I solved this same issue by layering the taskbar grid into another expanding grid:
<details><summary>Config</summary>

```
function("SfwbarInit") {
	SetLayer "bottom"
}

function("ToggleMinimize") {
	[!Minimized] Minimize
	[Minimized] UnMinimize
}

function("ToggleMaximize") {
	[!Maximized] Maximize
	[Maximized] UnMaximize
}

menu("winops") {
	item("(un)Minimize", Function "ToggleMinimize" );
	item("(un)Maximize", Function "ToggleMaximize" );
	separator;
	item("Close", Close );
}

# Panel layout
layout {
	image {
		style = "launcher"
		value = "firefox"
		action = "firefox"
	}
	image {
		style = "launcher"
		value = "foot"
		action = "foot"
	}
	grid {
		# Small hack to stretch the grid
		# without stretching the taskbar.
		# Having a button { max-size: 240px }
		# would be much much easier
		#.
		# Also allows to place slight
		# separators on either end.
		style = "taskbarlayout"
		taskbar {
			style = "taskbar"
			icons = true
			labels = true
			sort = false
			filter_output = true
			action[3] = Menu "winops"
		}
	}
	tray {
		style = "tray"
	}
	label {
		style = "clock"
		value = Time("%a %b %e, %H:%M")
	}
}

#CSS

#layout {
	padding: 0 10px;
}

#taskbarlayout {
	-GtkWidget-hexpand: true;
	/* Slightly visible separator */
	border-left: 2px solid rgba(128, 128, 128, 0.2);
	border-right: 2px solid rgba(128, 128, 128, 0.2);
	margin: 0 10px;
	padding: 0 10px;
}

#tray {
	padding-right: 10px;
}

#taskbar button {
	min-width: 240px;
	border-radius: 0;
	border: 0;
}

#taskbar_active,
#taskbar_normal:hover {
	box-shadow: 0px 0px 5px rgba(128, 128, 128, 0.7) inset;
}

image {
	min-width: 24px;
	min-height: 24px;
	padding: 0 5px;
}
```
</details>

For a spacer I am using this in another area:
```
...
label { style = "spacer" }
...

#spacer {
	-GtkWidget-hexpand: true;
}

```

**Comment by LBCrion** [comment]
@joshuataylor, for your use case an expandable spacer is probably more useful than a max width option. The version posted by @Consolatis would do the trick, or a short version of:

```label { css = " * { -GtkWidget-hexpand: true; }" }```

More generally, implementing max-width/height wouldn't be too difficult. The hard bit would be implementing a proper size-style CSS property (i.e. px, cm, em etc). I don't think gtk exposes this functionality, so we can either implement the property as an integer and assume it's always in pixels or implement it as a string and deal with all the parsing and conversions (this would be a fairly major piece of work).

**Comment by joshuataylor** [comment]
Absolutely perfect, thanks @Consolatis  and @LBCrion !

I'll try and whip up a XFCE config example for proposed inclusion in the config folder (I don't have it locally right now, I'll install it and compare the two).

**Comment by LBCrion** [comment]
I mplemented basic widget clamping with size specified in pixels in the current git. You can now limit the width or height of a widget using -GtkWidget-max-width and -GtkWidget-max-height CSS properties.

**Comment by Consolatis** [comment]
Had a quick test with the new config and something seems off regarding padding:

![20221025_22h26m28s_grim](https://user-images.githubusercontent.com/35009135/197874969-79f6b160-975f-4617-9687-a885da1dec40.png)


<details><summary>Test config</summary>

```
function("SfwbarInit") {
	SetLayer "bottom"
}

# Panel layout
layout {
	taskbar {
		style = "taskbar"
		icons = true
		labels = true
		sort = false
	}
	label { style="spacer" }
	label {
		style = "clock"
		value = Time("%a %b %e, %H:%M")
	}
}

#CSS

#layout {
	padding: 0 10px;
}

#spacer {
	-GtkWidget-hexpand: true;
}

#taskbar {
	background-color: red;
}

#taskbar button {
	border: 0;
	border-radius: 0;
	min-width: 200px;
	-GtkWidget-max-width: 200;

	/**
	 * Comment out to suddenly
	 * see the red background
	 * between buttons.
	 */
	padding: 4px 0;
}

#taskbar_active,
#taskbar_normal:hover {
	box-shadow: 0px 0px 5px rgba(128, 128, 128, 0.7) inset;
}

image {
	min-width: 24px;
	min-height: 24px;
	padding: 0 5px;
}
```
</details>

**Comment by LBCrion** [comment]
Indeed, I needed to clamp the other side of the size negotiation logic. Should be done in the latest git. I also set the logic to respect the minimum size of the widget when clamping.
