### ISSUE TITLE
Feature request: MapId to be able to map a class name for an icon in the taskbar

### ISSUE THREAD

**Issue by joshuataylor** [LBCrion/sfwbar#55]
When using apps that run under XWayland, they may not have an app_id.

For example the Jetbrains products run java, so they run on XWayland and don't have an app_id (`app_id": null,`).

They do however seem to have the following:

```json
              "window_properties": {
                "class": "jetbrains-clion",
                "instance": "jetbrains-clion",
                "title": "sfwbar – wintree.c",
                "transient_for": null,
                "window_type": "normal"
              }
```

So we could use the class for xwayland apps as a workaround. I checked a few other apps and it seems the class and instance is set to the name of the process?

Could the `MapAppId app_id, pattern` be used for this?

**Comment by joshuataylor** [comment]
It looks like it should be possible to use the app_id, as it falls back to using the instance anyway (from sway_ipc.c):
```c
  if(!app_id)
  {
    json_object_object_get_ex(container,"window_properties",&ptr);
    if(ptr)
      app_id = json_string_by_name(ptr,"instance");
  }
```

**Comment by LBCrion** [comment]
Indeed, the logic for app_id determination is as following:
1) Use wayland app_id if available
2) If (1) is not available use xwayland instance (on sway)
3) If (1) and (2) produce a blank, try to get an app_id from MapAppId

I'm not 100% sure on this, but I think Hyprland will natively use xwayland class if app_id isn't available for xwayland windows.
