### ISSUE TITLE
In `pager`, using `cols` instead of `rows` causes crash

### ISSUE THREAD

**Issue by humanplayer2** [LBCrion/sfwbar#61]
I cannot seem to be able to use `cols` instead of `rows` in `pager` without getting a crash.

Consider the following minimal config, which runs fine:

```
function("SfwbarInit") {
  SetBarId "bar-0"
}

layout {
    pager{
       rows = 2
    }
}
```

If I replace `rows`  with `cols`, I get following error:

```
(sfwbar:6743): Gtk-WARNING **: 00:06:35.342: Negative content height -5 (allocation 1, extents 3x3) while allocating gadget (node button, owner GtkButton)
```

Am I doing something wrong? Missing something?

**Comment by LBCrion** [comment]
Is this without any anchors on the window? if you specify cols, the pager grid has no minimum vertical size, and without anchors, window is likely set to zero height. You may need to set minimum height for the window by specifying min-height css property for one of the objects in it.

**Comment by humanplayer2** [comment]
I suppose without any anchors? I am unsure of what exactly sets an anchor, but my impression is that `SetBarSize` is required, and I'm seeking to avoid using that so I can get a bar that varies in width with its content (mainly the pager). I get the error with the exact config from my first comment.

As I am rather novice in CSS and Gtk, may I ask what objects more specifically you suggest I assign min-height to?

I tried assigning it to the pager buttons, but I still get the same error. Specifically, I still get the same error with the following config (which runs fine with `rows = 1`):

```
function("SfwbarInit") {
  SetBarId "bar-0"
}

layout {
  pager{
    cols = 1
  }
}

#CSS

button#pager_normal {
  background-color: red;
  min-height: 30px;
}
```

**Comment by LBCrion** [comment]
try adding a label to your layout with a min-height property. You want to have it in the same row as your pager (which will be by default for horizontal bars, but not for vertical bars). Something like this should be universal:

```
layout {
  label {
    css = "* { min-height: 200px; }"
    loc (1,1)
  }
  pager {
    cols = 1
    loc (2,1)
  }
}
```

**Comment by humanplayer2** [comment]
Yes, that did it! Thank you very much!
