### ISSUE TITLE
In `pager`, `numeric = true` sorts 10 between 1 and 2

### ISSUE THREAD

**Issue by humanplayer2** [LBCrion/sfwbar#62]
In the pager, `numeric = true` sorts workspaces differently than I would expect: If I have windows on workspaces 1, 2, 10, 11, the pager lists lhe workspaces as `1`, `10`, `11`, `2` where I would expect `1`, `2`, `10`, `11`.

I used the following config:

```
function("SfwbarInit") {
  SetBarId "bar-0"
}

layout {
    pager{
      rows = 1
      sort = true
      numeric = true
    }
}
```

Is sorting 10 before 2 intended? If so, is there a way to get the pager to list the workspace as `1`, `2`, `10`, `11`? I apologize if I missed something.

**Comment by LBCrion** [comment]
Looks like this is a bug from widget system rewrite. Should be fixed now.

**Comment by humanplayer2** [comment]
Yep! Thank you!
