### ISSUE TITLE
`killall -SIGUSR1 sfwbar` to only show items in workspace when filter = workspace is set

### ISSUE THREAD

**Issue by joshuataylor** [LBCrion/sfwbar#63]
It would be really nice if `killall -SIGUSR1 sfwbar` only showed items on the current workspace, similar to how xfce4, kde, etc work.

Right now it shows all applications across all workspaces.

**Comment by LBCrion** [comment]
Do you mean filtering the switcher to show items on the current workspace only?

**Comment by joshuataylor** [comment]
yes, so it'll only show the items on the current workspace

**Comment by LBCrion** [comment]
This will be a matter of implementing filtering for switcheritem class. Should be reasonably straightforward,  since most of the code can be copied from taskbaritem. It may take a few days before I get to it. I want to land initial support for dynamically loadable modules first.

**Comment by joshuataylor** [comment]
There is absolutely no rush at all, thought this would be a good feature suggestion :). I tried looking at the code, but wasn't sure how to implement it safely

**Comment by LBCrion** [comment]
Can you try the latest git version please? You need to add ```filter = workspace``` to switcher section in the config.

**Comment by joshuataylor** [comment]
Woo! That works perfectly, cheers!
