### ISSUE TITLE
Vertically center text inside label 

### ISSUE THREAD

**Issue by mozlima** [LBCrion/sfwbar#65]
I'm trying to vertically center the text . 

![Screenshot from 2022-11-29 11-25-26](https://user-images.githubusercontent.com/128335/204564442-4e847ad7-26f7-4b7c-951f-1c97de694398.png)

The code I'm trying:

```
grid {
		css = "* { -GtkWidget-hexpand: false; -GtkWidget-vexpand: true; -GtkWidget-valign: center;  }"
		label {
			interval = 300000
			value = $Shutdown
			action[1] = "executor-shutdown.sh 0 0 0"
			action[2] = "executor-shutdown.sh 5 240 240"
			action[3] = "executor-shutdown.sh 5 240 15"
			css = "* {padding: 0.20rem;  -GtkWidget-align: 0.5; }"
		}
		label {
			interval = 300000
			value = $Volume
			action[2] = "pavucontrol -m"
			action[3] = "executor-volume.sh mute"
			action[5] = "executor-volume.sh '2%+'"
			action[4] = "executor-volume.sh '2%-'"
			css = "* {padding: 0.20rem; -GtkWidget-align: 0.5; }"
		}
	}
```

Tested both inside grid and label only

**Comment by LBCrion** [comment]
You need to add ```-GtkWidget-vexpand: true; -GtkWidget-valign: center;``` to css property of labels, as well as the grid, to center them vertically.  Your current config centers the grid vertically within the bar,  but the labels are still positioned at the top of the grid.  -GtkWidget-align css property only aligns your labels in the direction of the text (I.e. horizontally).

**Comment by mozlima** [comment]
HI,

Still dont work.


![Screenshot from 2022-11-30 10-25-23](https://user-images.githubusercontent.com/128335/204811317-9f99f56d-7379-4127-9c16-99981ff76b6c.png)

```
	grid {
		css = "* { -GtkWidget-hexpand: false; -GtkWidget-vexpand: true; -GtkWidget-valign: center; background-color: green; }"
		label {
			css = "* { -GtkWidget-vexpand: true; -GtkWidget-valign: center; background-color: red; }"
			interval = 300000
			value = $Shutdown
			action[2] = "pavucontrol -m"
		}
		label {
			css = "* { -GtkWidget-vexpand: true; -GtkWidget-valign: center; background-color: blue; }"
			interval = 300000
			value = $Volume
			action[2] = "pavucontrol -m"
		}
	}
```
Tested with:

Setting  big min-height on sibling widget :

![Screenshot from 2022-11-30 10-36-11](https://user-images.githubusercontent.com/128335/204811631-ad24b07b-50d1-4912-9b86-096cf4f2dad4.png)

Setting  big min-height on grid :

![Screenshot from 2022-11-30 10-47-03](https://user-images.githubusercontent.com/128335/204813655-25f59e15-d532-4c69-8a77-0bbb09e67fea.png)

Setting  big min-height on label :


![Screenshot from 2022-11-30 10-51-03](https://user-images.githubusercontent.com/128335/204813813-e03b6af7-8f6f-4c9e-925e-66daa7f941b3.png)

-GtkWidget-vexpand: true  not working, the grid and label only grow by setting min-height.


Playing on Glade , this only work if a set `row-homogeneous`  and `column-homogeneous` on grid

**Comment by mozlima** [comment]
Found the problem: the text returned by the scripts, has a newline char and Grab() dont trim them

![Screenshot from 2022-11-30 12-06-36](https://user-images.githubusercontent.com/128335/204833939-bc117ab2-3cc7-400c-b4a3-709f45d7f775.png)
