### ISSUE TITLE
taskbar: Is there a way to only show floating windows and exclude tiled windows?

### ISSUE THREAD

**Issue by winteriscariot** [LBCrion/sfwbar#67]
In general, since tiled windows are often always visible (tabs aside) i was wondering if there was an option to only show windows that are floating? Thanks!

**Comment by LBCrion** [comment]
There is now. In the latest git version you can set ```filter = floating``` to filter out tiled windows. The option only works on sway for now. It should be possible to implement on Hyprland, but we'll need an event on the compositor side to monitor floating state. It's also not yet possible to combine floating filter with output or workspace filter. I.e. you can't just have floating windows on a single output.

**Comment by LBCrion** [comment]
Closing this as fixed. Please reopen if anything isn't working as expected.
