### ISSUE TITLE
CSS themes conflict with GTK_THEME for icons

### ISSUE THREAD

**Issue by joshuataylor** [LBCrion/sfwbar#68]
Hi!

I've recently changed from a dark theme to a light theme for GTK apps, and noticed that sfwbar will correctly render the theme behind icons when they are hovered or active:

This is the correct behaviour, as my GTK Theme is set to `Breeze`:
![gif1](https://user-images.githubusercontent.com/225131/211244334-d387d813-ea0c-4b4a-bcde-ef25706b016e.gif)

```bash
gsettings set org.gnome.desktop.interface gtk-theme Breeze
```

I think documenting that starting sfwbar with the following should be a good workaround (and is the recommended solution, according to [archwiki](https://wiki.archlinux.org/title/GTK#Themes) :-):

```
GTK_THEME=Adwaita:dark sfwbar
```

Which then results in:
![foo](https://user-images.githubusercontent.com/225131/211244613-1c232e95-f0e2-44be-92b8-1a93a896d213.gif)

This is not a sfwbar bug I believe, and not an issue, but there isn't discussions here :-).

**Comment by LBCrion** [comment]
This is very timely. I just started working on light/dark theme handling last week. 

If I understand the issue correctly,  you have the window background set to a dark colour.  This works well with a dark theme,  but not the light theme? And the workaround is to start sfwbar with a dark theme?

You can also override the hover color in css using ``image:hover`` node.

What I am thinking for a more general approach to light/dark theme handling, is implementing theme conditional styling. My current line of thought is to introduce an expression function GtkTheme, to query dark vs light theme (based on avg rgb of background vs foreground). I.e.
```
Label {
Style = if( GtkTheme("dark"), "mylabel_dark", "mylabel_light"
}

#CSS
label#mylabel_light {...}
label#mylabel_dark {...}
```
The problem I don't see a good solution for so far is handling this for built in styles (I.e. taskbar and tray item styles). These are internally set. I could bifurcate the naming for these,  but that will break a lot of configs.

**Comment by joshuataylor** [comment]
> If I understand the issue correctly, you have the window background set to a dark colour

Yeah, I use the light version of [Breeze](https://www.gnome-look.org/p/1197982/) now, as I prefer that for GUI apps, but prefer the dark sfwbar at the bottom :-).

> theme conditional styling

Maybe an override as well, so [users like me](https://xkcd.com/1172/) who sometimes prefer dark themes can set that as a setting?

**Comment by LBCrion** [comment]
I added a toplevel option Theme, i.e. you can add ``Theme = "Adwaita-dark"``

**Comment by joshuataylor** [comment]
Awesome! Sorry, missed this notification. Works great.
