### ISSUE TITLE
Taskbar: margin breaks taskbar group popup behavior

### ISSUE THREAD

**Issue by Vimux** [LBCrion/sfwbar#69]
If there is a margin around the taskbar elements, then any mouse movement over the margin area shows a popup and hides it when hovering over the item itself. Increasing the margin area on all sides shows this even more clearly.

**Low-res video demonstration:**

<details>
  <summary>Spoiler</summary>

https://user-images.githubusercontent.com/21033483/211586593-0a4f5bf7-c424-4441-8b92-5b26407fef4c.mp4

</details>

**Program version:**

* sfwbar [commit d072b35fa879c31cac34da26ae27763c7ea08b32]

**Comment by LBCrion** [comment]
Can you post your config please? I tried adding large margins to w10.config, but couldn't replicate this behaviour so far.

**Comment by LBCrion** [comment]
I think I found the issue. Can you try the current git version please?

**Comment by Vimux** [comment]
I haven't tested it thoroughly yet, but now the popup doesn't disappear when hovering over menu items. Thanks.
