### ISSUE TITLE
foreign_toplevel `output_enter` handler seems to miss a commit

### ISSUE THREAD

**Issue by Consolatis** [LBCrion/sfwbar#74]
Found while debugging https://github.com/labwc/labwc/issues/744

```diff
diff --git a/src/wayland/foreign-toplevel.c b/src/wayland/foreign-toplevel.c
index fec6c72..8029e70 100644
--- a/src/wayland/foreign-toplevel.c
+++ b/src/wayland/foreign-toplevel.c
@@ -119,6 +119,7 @@ static void toplevel_handle_output_enter(void *data, wlr_fth *tl,
     return;
   g_free(win->output);
   win->output = g_strdup(name);
+  wintree_commit(win);
 }
 
 static const struct zwlr_foreign_toplevel_handle_v1_listener toplevel_impl = {
```

I think the behavior of sfwbar could still be improved a bit as a window may be on multiple outputs at once.

Example:
2 outputs, `A` and `B`. There is a panel on each output, both using `filter = output`.

We spawn a window on output `A`, everything is fine. We start to move the window to output `B`, as soon as we touch `B` (without leaving `A`) the window will be shown on the `B` panel only. When we then move the window back to output `A` the window will still only show up on the `B` panel because it never received a `output_enter` event for output `A` (as it never left it in the first place).

Only if we move the window completely to output `B` (leaving `A`) and then moving it back it will work correctly.

Another related issue would be having a single window span multiple outputs on purpose (not just while moving), it would only show up on one of the panels.

**Comment by LBCrion** [comment]
Thank you @boris3812 for spotting this and @Consolatis for the fix! The fix is in and I added tracking of windows across multiple outputs. I don't have a multi-monitor setup handy so if anyone can test this, I would very much appreciate it.

**Comment by Consolatis** [comment]
Usually you can run wlroots based compositors nested by just starting them from your active wayland (or even X11) session: `WLR_WL_OUTPUTS=2 $compositor` when using the wayland backend with 2 virtual outputs. Bare in mind that we didn't yet merge our end of the fix so test results from labwc 0.6.1 / master might not show the full picture. I will give it a test ride in a few hours with our fix applied as well.

**Comment by boris3812** [comment]
> Thank you @boris3812 for spotting this and @Consolatis for the fix! The fix is in and I added tracking of windows across multiple outputs. I don't have a multi-monitor setup handy so if anyone can test this, I would very much appreciate it.

https://github.com/labwc/labwc/issues/744#issuecomment-1414347979
i mentionated what we have , so i understand that we have to wait from some test ride from @Consolatis , so yes , it's not full picture 😁

**Comment by Consolatis** [comment]
```diff
diff --git a/src/wayland/foreign-toplevel.c b/src/wayland/foreign-toplevel.c
index e4ba36f..22ad81a 100644
--- a/src/wayland/foreign-toplevel.c
+++ b/src/wayland/foreign-toplevel.c
@@ -113,7 +113,7 @@ static void toplevel_handle_output_leave(void *data, wlr_fth *tl,
   win = wintree_from_id(tl);
   if(!win)
     return;
-  link = g_list_find(win->outputs,name);
+  link = g_list_find_custom(win->outputs, name, (GCompareFunc)g_strcmp0);
   if(!link)
     return;
   g_free(link->data);
```

With this applied it seems to work fine.

**Comment by boris3812** [comment]
so... yep , thats it !)   
```diff
-  link = g_list_find(win->outputs,name);
+  link = g_list_find_custom(win->outputs, name, (GCompareFunc)g_strcmp0);
```
now it seems working fine and our sfwbar :)
 🎉🎉🎉 )

https://filedn.com/lyCLU10bkY6FUrIxXH2IUHz/2023-02-03_05-20-45.mp4

**Comment by LBCrion** [comment]
Excellent. I also fixed tracking issue with hyprland and cleanup the foreign toplevel code. Hopefully all should be good now.

**Comment by Consolatis** [comment]
Thanks for the fast response and solution, as always when dealing with sfwbar :)

Closing this issue, I assume the other one can be closed as well
- #66
