### ISSUE TITLE
Make 'minimized' windows accessible on all workspaces?

### ISSUE THREAD

**Issue by winteriscariot** [LBCrion/sfwbar#76]
Right now minimized windows are 'sticky' to their workspace: even though i see all minimized windows on all workspaces, clicking a 'minimized' window will take me to that workspace.

Desired behavior: i want it to be more like 'scratchpad show', where the minimized windows will restore on whatever workspace i'm currently on, not the workspace in which it was minimized. I have a scratchpad toggle button in my waybar config that does this, but i would prefer to use sfwbar as sfwbar will show me all of the minimized/scratchpad windows, instead of just a number of windows (and also lets me restore multiple scratchpad windows, not 1 at a time)

Is this possible?

Here's my taskbar config. I tried setting output filter to see if that would do what i want (just a laptop with a single output) but doesn't seem to

```
 taskbar {
    rows = 1
    icons = false 
    labels = true
    filter = output
    filter = floating
    action[3] = Menu "winops"
    title_width = 30
  }
```

Thanks!

**Comment by LBCrion** [comment]
This would be easy to implement for sway and hyprland, but impossible for compositors using wlr-foreign-toplevel protocol (since there is no wayland protocol to manipulate windows across workspaces yet). I'll try to implement this once I'm done with the feature I'm working on right now.

**Comment by LBCrion** [comment]
It looks like the config option to enable this would need to be global, since this isn't a feature we can enable on a per-taskbar basis. If this option is enabled, a window when minimized will lose association with it's workspace. It will then appear on all taskbars (even if they have ``filter = workspace`` enabled) and will be unminimized to the current workplace. 

This is how we already handle any windows that were opened and minimized prior to sfwbar launching.

**Comment by LBCrion** [comment]
This should now work on sway and hyprland. You'll need to add a global option ``DisownMinimized = true``

**Comment by iggut** [comment]
> This should now work on sway and hyprland. You'll need to add a global option `DisownMinimized = true`

Could you please elaborate where I would add a global option when using Hyprland? I am quite new to the terminology.

**Comment by LBCrion** [comment]
This should go into sfwbar config file on the top level (i.e. outside of
any {} sections). If you haven't made a config yet, just copy
/usr/share/sfwbar/sfwbar.config to $HOME/.config/sfwbar/sfwbar.config and
insert the above option as the first line of the config.

**Comment by LBCrion** [comment]
Closing this as fixed. If anything else is needed for this feature, please feel free to reopen this issue.
