### ISSUE TITLE
icons in general need a sane default

### ISSUE THREAD

**Issue by keshto** [LBCrion/sfwbar#79]
Without specifying `min-height/width` for an image the icons for task/tray/menu etc or tiny or non existent. For an out of the box experience it sorta is strange (ex use menu widget with tint2 example config and all the menu icons are tiny). This also has a weird side effect (again for zoom) that it uses a 64x64 icon which then gets clipped and looks strange (this is not the case in waybar).

**Comment by LBCrion** [comment]
Zoom icon cropping is a bug - this should be fixed now. 
Let me think about the best way to implement default icon sizes.

**Comment by keshto** [comment]
You are on fire! Will test and report back. Thanks!

**Comment by keshto** [comment]
It would be nice if the v/hexpand (assuming it respects padding/margin) would work for images that would be a good default

**Comment by keshto** [comment]
Changes look like they broke more than they fixed. nm-applet is weird size it used to be same as others. zoom is same
![image](https://user-images.githubusercontent.com/766237/227403392-e5d33e03-ef7e-45e1-b48c-ca84ea52759b.png)

**Comment by keshto** [comment]
latest change fixes the clipping. Thanks!
We should probably keep this open until you decide what to do about sane defaults.

**Comment by LBCrion** [comment]
I added 16x16px default to the code. If min-wdith / min-height are set to zero, they will default to 16px, otherwise specified number will be used.

**Comment by keshto** [comment]
I will test and report back shortly

**Comment by keshto** [comment]
World of a difference! now if someone does not stylize their icons they can still see them as opposed to before where they were tiny and in some cases invisible. Great job!
