### ISSUE TITLE
[feature request] programtic way to reload config

### ISSUE THREAD

**Issue by keshto** [LBCrion/sfwbar#82]
Would be nice to have a `sfwbar --reload/reconfigure` especially when testings config changes

**Comment by LBCrion** [comment]
This can be done, but would essentially involve reloading the process in it's entirety, since the config populates all of the internal structures and not all of them are setup to be torn down gracefully. I'll need to have a look at doing this in a clean fashion.

**Comment by LBCrion** [comment]
The current git version should reload on -HUP signal.

**Comment by keshto** [comment]
What do you think about adding a `-reload/-exit` like cmdline option like labwc has. It could take a an optional bar id. Rationale being that sometimes one might want to reload the config which is great but what happens when there is more than one panel open? How do we exit one (some how figure out which one maps to what process) or reload all etc.

**Comment by LBCrion** [comment]
This would be a bit trickier, since we'll need an IPC to communicate between sfwbar processes. It should be doable of course - as I learned, 90% of any status bar development is implementing various IPCs.

**Comment by LBCrion** [comment]
Trying to think how this should work. Currently the bar_id is assigned on the level of a bar. Each sfwbar instance may have multiple bars defined. So if a user calls sfwbar -reload bar_id, should we reload all instances containing that id?

**Comment by Consolatis** [comment]
An alternative would be to just reload all bars managed by a given process that receives a SIGHUP if there are no further effects than maybe a short flicker due to layershell exclusive zone changes.
Some `--reconfigure` / `--reload` argument could then search for sfwbar processes (of the same user?) and just send them a SIGHUP signal. That way there is no new IPC required to make it work.

The reason it is easier for a compositor like labwc to target a specific instance is that labwc can set the labwc instance PID as environment variable which is then available for all applications, other than in the panel case.

**Comment by keshto** [comment]
hmm @LBCrion didn't think about that. I would say it might be more trouble than it is worth. I saw the SIGHUB you implemented is enough and we can close this issue. The initial intention was just for seeing changes in config other than that I don't see a need thus the effort to do this does not out weight the benefit.

**Comment by LBCrion** [comment]
I think that would make life easier (for me :) ).

**Comment by keshto** [comment]
Reopening because `sighup` \`hup` does not seem to do anything and doing it twice in a row kills sfwbar

**Comment by LBCrion** [comment]
That shouldn't be happening of course! Are you sending sighup via ``killall -HUP sfwbar`` or ``kill -HUP <pid>``?
Would it be possible to run sfwbar in gdb and get a stack trace of a crash?

**Comment by keshto** [comment]
I used both `kill` and `killall`. The first HUP does nothing and the second does not crash just hangsup

```
◗ kill -HUP 25601
◗ kill -HUP 25601
[1]+  Hangup                  sfwbar
```

**Comment by LBCrion** [comment]
Can you please try running the latest git with ``sfwbar -d -g reload``, send SIGHUP to the process and check the output?

**Comment by keshto** [comment]
```
◗ sfwbar -d -g reload
14:57:43.62 app_id: 'Firefox', title '[feature request] programtic way to reload config · Issue #82 · LBCrion/sfwbar — Mozilla Firefox'
14:58:24.51 reload: closing fd's 3 to 1024
14:58:24.51 reload: exec: sfwbar
```
it fails on the exec with exit code 1

**Comment by LBCrion** [comment]
Doh! 1 missing character in code. Can you try with the latest git please?
