### ISSUE TITLE
sfwbar-git on AUR

### ISSUE THREAD

**Issue by joshuataylor** [LBCrion/sfwbar#85]
Hi!

I think you're the maintainer for the [sfwbar](https://aur.archlinux.org/packages/sfwbar) aur package, I would love a git version of this (`sfwbar-git`).

Would you like to submit this to AUR? I would also be happy to maintain it, but IMHO it's pretty low effort, as it's the same as the main `sfwbar`, just with a pkgver step.

I've been using this locally, based off your work:

```PKGBUILD
pkgname=sfwbar-git
_pkgname=sfwbar
pkgver=r942.de920df
pkgrel=1

pkgdesc='S* Floating Window taskBar, git version'
arch=('x86_64' 'aarch64')
url='https://github.com/LBCrion/sfwbar'
license=('GPL3')
depends=(
    'wayland'
    'gtk3'
    'json-c'
    'gtk-layer-shell'
    'wayland-protocols'
    )
optdepends=(
    'libpulse: pulse audio volume control',
    'libmpdclient: music player daemon control',
    'libxkbcommon: xkb layout conversion support'
    )
makedepends=('meson')

source=("${pkgname%-*}::git+https://github.com/LBCrion/sfwbar.git")
md5sums=('SKIP')
sha512sums=('SKIP')

pkgver() {
    cd "$_pkgname"
    printf "r%s.%s" "$(git rev-list --count HEAD)" "$(git rev-parse --short HEAD)"
}

build() {
    cd "$_pkgname"
    meson --prefix=/usr \
          --buildtype=plain \
          build
    ninja -C build
}

package() {
    cd "$_pkgname"
    DESTDIR="$pkgdir" ninja -C build install
}
```

srcinfo:
```
pkgbase = sfwbar-git
    pkgdesc = S* Floating Window taskBar, git version
    pkgver = r942.de920df
    pkgrel = 1
    url = https://github.com/LBCrion/sfwbar
    arch = x86_64
    arch = aarch64
    license = GPL3
    makedepends = meson
    depends = wayland
    depends = gtk3
    depends = json-c
    depends = gtk-layer-shell
    depends = wayland-protocols
    optdepends = libpulse: pulse audio volume control,
    optdepends = libmpdclient: music player daemon control,
    optdepends = libxkbcommon: xkb layout conversion support
    source = sfwbar::git+https://github.com/LBCrion/sfwbar.git
    md5sums = SKIP
    sha512sums = SKIP

pkgname = sfwbar-git
```

**Comment by LBCrion** [comment]
Does this automatically follow the latest git version,  or does pkgver need
bumping?
I'm a bit wary of maintaining aur packages, since I don't use arch. The
current package in aur is my best attempt at making one. Ideally it would
be good to find an arch user who can test and maintain these.

**Comment by joshuataylor** [comment]
Apologies for the delayed response; I didn't see the notification earlier.

Yes, the package will update automatically, so there's no need to bump these. Paru/yay (package managers for AUR) will check packages that rely on git, for example.

In ArchLinux, -git packages cater to those who want to follow the main branch.

Some popular examples include [mesa-git](https://aur.archlinux.org/packages/mesa-git), [sway-git](https://aur.archlinux.org/packages/sway-git).

Additionally, I would be more than happy to co-maintain the AUR packages. I use Arch on both my desktop and laptop, and on both I happily use sfwbar. :-)

**Comment by LBCrion** [comment]
Ok, I added the -git package to AUR. Do you know how I can add you as a co-maintainer for the aur packages?

**Comment by LBCrion** [comment]
Closing this for now, since sfwbar-git has been on AUR for over a year :), if there is anything else that needs doing, please do reopen,
