### ISSUE TITLE
default sfwbar.config needs ToggleMinimize & ToggleMaximize functions for winops menu

### ISSUE THREAD

**Issue by jonleivent** [LBCrion/sfwbar#88]
Might be useful to make the default winops menu and its functions be a separate included module.

**Comment by LBCrion** [comment]
Thank you for flashing this.  Moving the win ops menu to a separate widget does make sense. It may take me a while,  as my laptop has died,  so I need to get and configure a new machine before I'm coding again.

**Comment by LBCrion** [comment]
This should be fixed in the latest git version.

**Comment by LBCrion** [comment]
Alas, I've never used AppArmor, so can't comment on this. sfwbar configs
use python for very limited tasks - generating start menu and detecting
battery /sys files, so the only permissions it should need is access to
desktop files and /sys filesystem. (not sure how much this helps).

**Comment by jonleivent** [comment]
On Tue, 25 Apr 2023 10:20:13 -0700
LBCrion ***@***.***> wrote:

> Alas, I've never used AppArmor, so can't comment on this. sfwbar
> configs use python for very limited tasks - generating start menu and
> detecting battery /sys files, so the only permissions it should need
> is access to desktop files and /sys filesystem. (not sure how much
> this helps).

I accidentally posted that message to the wrong github page.  Sorry!  I
deleted it immediately, but I guess it still went through.  My fault
for having too many tabs open at the same time.

**Comment by LBCrion** [comment]
Phew! That's good,  since I was clueless on this topic.

**Comment by LBCrion** [comment]
I think this one is safe to close as it's been fixed for a while now.
