### ISSUE TITLE
Crashes on launch (Arch Linux)

### ISSUE THREAD

**Issue by WTechNinja** [LBCrion/sfwbar#9]
I installed the AUR package, tried running it and it crashed, so I tried building it from the source here, ran that binary with ./sfwbar, and got this same error.

This is what is printed in the terminal: 
[terminal.txt](https://github.com/LBCrion/sfwbar/files/7740178/terminal.txt)
And this is the wget-log
[wget-log.txt](https://github.com/LBCrion/sfwbar/files/7740177/wget-log.txt)

**Comment by LBCrion** [comment]
Most of the output looks to be wget related. The actual error is freeing an invalid pointer. Any chance you have gdb installed? In that case can you run "gdb sfwbar"? Once at prompt type "run" and once it crashes out, type"backtrace" and post the output?

**Comment by WTechNinja** [comment]
Done, here you go
[gdb.txt](https://github.com/LBCrion/sfwbar/files/7740921/gdb.txt)

**Comment by WTechNinja** [comment]
It doesn't crash as completely when I run it through gdb, it seems, because it still has the bottom area where it would be, reserved... There's nothing there, but yeah.
![2021-12-19T07:20:45,737284508-07:00](https://user-images.githubusercontent.com/64444934/146678249-1a58cd55-e36d-4550-8101-9dbd903dcd59.png) 
(this screenshot is from a second run I did to make sure it was reproduceable, I killed off the first run's sfwbar process and then ran it through gdb a second time)

**Comment by LBCrion** [comment]
It does crash, gdb just keeps the process in it's crashed state until you quit it. It looks like an improper initialization of AttnMov SNI property, I pushed a fix for it, would you mind trying the latest git version?

**Comment by WTechNinja** [comment]
Yep, fixed! Now the only problem is the vibrating/rapid movement the other guy on reddit mentioned...
