### ISSUE TITLE
More elegant failures

### ISSUE THREAD

**Issue by keshto** [LBCrion/sfwbar#91]
```
◗ sfwbar -f config/wbar.config 
09:07:17.56 hypr: can't open socket
Segmentation fault
```

Maybe something more like waybar:
```
[warning] module sway/workspaces: Disabling module "sway/workspaces", Socket path is empty
```

**Comment by keshto** [comment]
Note that the error is not the reason for the segfault.

```
@@ -1,6 +1,6 @@
-scanner {
-  SwayClient("") {}  # launch sway client to get "sway" trigger
-}
+#scanner {
+#  SwayClient("") {}  # launch sway client to get "sway" trigger
+#}
 
 # Window Placer
 placer {
@@ -45,7 +45,7 @@ layout ":start" {
 }
 
 layout ":end" {
-  include("wbar-mpd.widget")
+#  include("wbar-mpd.widget")
 #  include("wbar-bluetooth.widget")
   include("wbar-idleinhibit.widget")
   include("wbar-pulse.widget")
@@ -54,7 +54,7 @@ layout ":end" {
   include("wbar-memory.widget")
   include("wbar-temp.widget")
   include("wbar-backlight.widget")
-  include("wbar-sway-lang.widget")
+#  include("wbar-sway-lang.widget")
```
makes seg fault go away

**Comment by LBCrion** [comment]
Any chance you can get a backtrace of the segfault? I'll take a look at the
hypr error.  Is this with huprland?

**Comment by LBCrion** [comment]
Thank you! You're way ahead of me.

**Comment by keshto** [comment]
backtrace already included :) no i am not running hyperland

**Comment by keshto** [comment]
I believe it has to do with `include("wbar-mpd.widget")`

**Comment by LBCrion** [comment]
Can you try with the latest git please? Hyprland message isn't fixed,  but
the segfault hopefully should be.

**Comment by keshto** [comment]
Yay no more segfault! I think the hyper message is fine. Maybe make it more like a warning?

Closing as the segfault was the scary part (if a new user were to try to use sfwbar there should be no segfault no matter the config or their env)

**Comment by LBCrion** [comment]
Yes,  it should have only reported these in debug mode. Should be fixed
now.
