### ISSUE TITLE
Floating panel

### ISSUE THREAD

**Issue by alttabber** [LBCrion/sfwbar#93]
Is it possible to have a floating panel? I have tried to add the properties `margin` and `width` to `window#sfwbar`, but it did nothing.

**Comment by LBCrion** [comment]
If you just want some space between the edge of the screen and the bar,
you should be able to do this with the margin, try applying it to
"window#sfwbar box", you may need to set transparent background on the
window to achieve the floating effect.

**Comment by alttabber** [comment]
You also need to add the background back in `window#showbar box`.

This does the trick:
```
window#showbar{
    background: rgba(0,0,0,0);
}
window#showbar box{
    margin: foo px;
    background: bar;
}
```

Thank you very much.
