### ISSUE TITLE
taskbar: Is there a way to filter apps by title to avoid show them in the taskbar?

### ISSUE THREAD

**Issue by efmgit** [LBCrion/sfwbar#95]
I am not sure if it is possible to filter apps in the taskbar. I didn't find how to do it yet but it would be nice. I am trying to integrate labwc+sfwbar+pcmanfm-qt --desktop. In general it works fine but the "pcmanqt-desktop0" title is shown in the taskbar as a normal app. It is a bit annoying. Any thoughts are welcome :)

Thank you!

**Comment by Consolatis** [comment]
If you use the latest (unreleased) version of labwc you can add `skipTaskbar="yes"` to your pcmanfm-qt --desktop rule, it should prevent it showing up in panels, including in sfwbar. See https://github.com/labwc/labwc/pull/933 for reference.

**Comment by LBCrion** [comment]
If you think this functionality would be useful to have in the bar, I can add it. It looks like it won't add much for labwc, but I guess it could be of use with other compositors.

**Comment by efmgit** [comment]
At the moment it's fine for me with labwc. Maybe it would be useful for others compositors but I am not sure for which ones at this moment. 
_btw ... many thanks for your great job with sfwbar_

**Comment by LBCrion** [comment]
I added toplevel options ``FilterTitle`` and ``FilterAppId`` to allow filtering out windows either by their title or app id respectively. Both take regular expressions as input and filter out windows matching the regex from both taskbars and a switcher.
