### ISSUE TITLE
How to theme taskbar group

### ISSUE THREAD

**Issue by clemencyworld1** [LBCrion/sfwbar#96]
After theming the taskbar i realised the group feature so i added it. However the buttons are just white while the grouped windows retain the themed colors.

I have tried using different css syntax (ie button#taskbar group, button#taskbar_group) but could not get to match the group button widget.

Any help will be appreciated

**Comment by LBCrion** [comment]
You should be able to use ``#taskbar_group_active`` and ``#taskbar_group_norma``l names. w10.config is a good example of grouped taskbar configuration.

**Comment by clemencyworld1** [comment]
Thanks. It worked
