### ISSUE TITLE
Taskbar grouping when only 1 instance is running

### ISSUE THREAD

**Issue by takase1121** [LBCrion/sfwbar#97]
When only one instance of a program is running (e.g. one Firefox window), the taskbar shouldn't create a group with one task in it; instead it should just be a normal taskbar button.

**Comment by LBCrion** [comment]
This would indeed be tidier. I just committed support for this to the latest git version. Can you try it please and see if it works as expected?

**Comment by takase1121** [comment]
Yes, now it looks better.
