### ISSUE TITLE
Menus only close by mouse clicking a GTK area.

### ISSUE THREAD

**Issue by 01micko** [LBCrion/sfwbar#98]
I realise this is the same with _all_ GTK applications. If you open a menu and choose not to click the menu entry then to close you must click in any GTK area for the menu to close.

ATM, I'm using left click on desktop to close the menu by `killall -HUP sfwbar` in my `labwc/rc.xml` config file by mouse bind. A snippet:

```xml
   <context name="Root">
      <mousebind button="Left" action="Press">
        <action name="Execute"><command>killall -HUP sfwbar</command></action>
      </mousebind>
      <mousebind button="Right" action="Press">
        <action name="ShowMenu" menu="root-menu"/>
      </mousebind>
      <mousebind button="Middle" action="Press">
        <action name="ShowMenu" menu="none"/>
      </mousebind>
      <mousebind direction="Up" action="Scroll">
        <action name="GoToDesktop" to="left" wrap="yes"/>
      </mousebind>
      <mousebind direction="Down" action="Scroll">
        <action name="GoToDesktop" to="right" wrap="yes"/>
      </mousebind>
     </context>
```

This approach is a little harsh because we are restarting the bar just to close a menu!

Is there another way? 

Thanks!

**Comment by LBCrion** [comment]
This seems to be a compositor specific behavior. I just tested this and on sway and hyprland, the menu closes if I click outside of the bar, but on labwc it doesn't. I suspect some event is sent by sway but not by labwc?

**Comment by 01micko** [comment]
Thanks for testing. I'll raise an issue on labwc and close this. I'd better update labwc!

**Comment by Consolatis** [comment]
Pretty sure its a labwc bug, it seems we are not resetting the keyboard focus on desktop click. Instead, it requires a click on another surface to reset the keyboard focus and thus close the context menu.
